import Vsa.Elf

/-! Code-region predicate + fetch-hypothesis lemmas for `__malloc_lock`
(generated by experiments/gen_code_lemmas.py — do not hand-edit).
2 instructions at [0x80005068, 0x80005070). -/

open Std (ExtHashMap)

namespace Vsa.Sim.Code

def __malloc_lockChunk0 (mem : ExtHashMap Nat (BitVec 8)) : Prop :=
  mem[(0x80005068 : Nat)]? = some (0x13 : BitVec 8) ∧
  mem[(0x80005069 : Nat)]? = some (0x85 : BitVec 8) ∧
  mem[(0x8000506a : Nat)]? = some (0x81 : BitVec 8) ∧
  mem[(0x8000506b : Nat)]? = some (0x4c : BitVec 8) ∧
  mem[(0x8000506c : Nat)]? = some (0x6f : BitVec 8) ∧
  mem[(0x8000506d : Nat)]? = some (0x10 : BitVec 8) ∧
  mem[(0x8000506e : Nat)]? = some (0x50 : BitVec 8) ∧
  mem[(0x8000506f : Nat)]? = some (0x77 : BitVec 8)

/-- The whole `__malloc_lock` code region is loaded. -/
def __malloc_lockLoaded (mem : ExtHashMap Nat (BitVec 8)) : Prop :=
  __malloc_lockChunk0 mem

theorem __malloc_lock_chunk0 {mem : ExtHashMap Nat (BitVec 8)}
    (h : __malloc_lockLoaded mem) : __malloc_lockChunk0 mem :=
  h

theorem __malloc_lock_at_80005068 {mem : ExtHashMap Nat (BitVec 8)}
    (h : __malloc_lockLoaded mem) :
      mem[(0x80005068 : Nat)]? = some (0x13 : BitVec 8) ∧
      mem[(0x80005069 : Nat)]? = some (0x85 : BitVec 8) ∧
      mem[(0x8000506a : Nat)]? = some (0x81 : BitVec 8) ∧
      mem[(0x8000506b : Nat)]? = some (0x4c : BitVec 8) :=
  have hc := __malloc_lock_chunk0 h
  ⟨hc.1, hc.2.1, hc.2.2.1, hc.2.2.2.1⟩

theorem __malloc_lock_at_8000506c {mem : ExtHashMap Nat (BitVec 8)}
    (h : __malloc_lockLoaded mem) :
      mem[(0x8000506c : Nat)]? = some (0x6f : BitVec 8) ∧
      mem[(0x8000506d : Nat)]? = some (0x10 : BitVec 8) ∧
      mem[(0x8000506e : Nat)]? = some (0x50 : BitVec 8) ∧
      mem[(0x8000506f : Nat)]? = some (0x77 : BitVec 8) :=
  have hc := __malloc_lock_chunk0 h
  -- discipline: allow(R6-anon-projection-tower) generated code-pin projections (bounded, chunked)
  ⟨hc.2.2.2.2.1, hc.2.2.2.2.2.1, hc.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2⟩

end Vsa.Sim.Code
