import Vsa.Elf

/-! Code-region predicate + fetch-hypothesis lemmas for `_write`
(generated by experiments/gen_code_lemmas.py — do not hand-edit).
12 instructions at [0x8000003c, 0x8000006c). -/

open Std (ExtHashMap)

namespace Vsa.Sim.Code

def _writeChunk0 (mem : ExtHashMap Nat (BitVec 8)) : Prop :=
  mem[(0x8000003c : Nat)]? = some (0x63 : BitVec 8) ∧
  mem[(0x8000003d : Nat)]? = some (0x04 : BitVec 8) ∧
  mem[(0x8000003e : Nat)]? = some (0x06 : BitVec 8) ∧
  mem[(0x8000003f : Nat)]? = some (0x02 : BitVec 8) ∧
  mem[(0x80000040 : Nat)]? = some (0x13 : BitVec 8) ∧
  mem[(0x80000041 : Nat)]? = some (0x07 : BitVec 8) ∧
  mem[(0x80000042 : Nat)]? = some (0x10 : BitVec 8) ∧
  mem[(0x80000043 : Nat)]? = some (0x10 : BitVec 8) ∧
  mem[(0x80000044 : Nat)]? = some (0xb3 : BitVec 8) ∧
  mem[(0x80000045 : Nat)]? = some (0x86 : BitVec 8) ∧
  mem[(0x80000046 : Nat)]? = some (0xc5 : BitVec 8) ∧
  mem[(0x80000047 : Nat)]? = some (0x00 : BitVec 8) ∧
  mem[(0x80000048 : Nat)]? = some (0x13 : BitVec 8) ∧
  mem[(0x80000049 : Nat)]? = some (0x17 : BitVec 8) ∧
  mem[(0x8000004a : Nat)]? = some (0x07 : BitVec 8) ∧
  mem[(0x8000004b : Nat)]? = some (0x03 : BitVec 8) ∧
  mem[(0x8000004c : Nat)]? = some (0x83 : BitVec 8) ∧
  mem[(0x8000004d : Nat)]? = some (0xc7 : BitVec 8) ∧
  mem[(0x8000004e : Nat)]? = some (0x05 : BitVec 8) ∧
  mem[(0x8000004f : Nat)]? = some (0x00 : BitVec 8) ∧
  mem[(0x80000050 : Nat)]? = some (0x93 : BitVec 8) ∧
  mem[(0x80000051 : Nat)]? = some (0x85 : BitVec 8) ∧
  mem[(0x80000052 : Nat)]? = some (0x15 : BitVec 8) ∧
  mem[(0x80000053 : Nat)]? = some (0x00 : BitVec 8) ∧
  mem[(0x80000054 : Nat)]? = some (0xb3 : BitVec 8) ∧
  mem[(0x80000055 : Nat)]? = some (0xe7 : BitVec 8) ∧
  mem[(0x80000056 : Nat)]? = some (0xe7 : BitVec 8) ∧
  mem[(0x80000057 : Nat)]? = some (0x00 : BitVec 8) ∧
  mem[(0x80000058 : Nat)]? = some (0x17 : BitVec 8) ∧
  mem[(0x80000059 : Nat)]? = some (0xb8 : BitVec 8) ∧
  mem[(0x8000005a : Nat)]? = some (0x01 : BitVec 8) ∧
  mem[(0x8000005b : Nat)]? = some (0x00 : BitVec 8) ∧
  mem[(0x8000005c : Nat)]? = some (0x23 : BitVec 8) ∧
  mem[(0x8000005d : Nat)]? = some (0x34 : BitVec 8) ∧
  mem[(0x8000005e : Nat)]? = some (0xf8 : BitVec 8) ∧
  mem[(0x8000005f : Nat)]? = some (0xca : BitVec 8) ∧
  mem[(0x80000060 : Nat)]? = some (0xe3 : BitVec 8) ∧
  mem[(0x80000061 : Nat)]? = some (0x96 : BitVec 8) ∧
  mem[(0x80000062 : Nat)]? = some (0xd5 : BitVec 8) ∧
  mem[(0x80000063 : Nat)]? = some (0xfe : BitVec 8) ∧
  mem[(0x80000064 : Nat)]? = some (0x13 : BitVec 8) ∧
  mem[(0x80000065 : Nat)]? = some (0x05 : BitVec 8) ∧
  mem[(0x80000066 : Nat)]? = some (0x06 : BitVec 8) ∧
  mem[(0x80000067 : Nat)]? = some (0x00 : BitVec 8) ∧
  mem[(0x80000068 : Nat)]? = some (0x67 : BitVec 8) ∧
  mem[(0x80000069 : Nat)]? = some (0x80 : BitVec 8) ∧
  mem[(0x8000006a : Nat)]? = some (0x00 : BitVec 8) ∧
  mem[(0x8000006b : Nat)]? = some (0x00 : BitVec 8)

/-- The whole `_write` code region is loaded. -/
def _writeLoaded (mem : ExtHashMap Nat (BitVec 8)) : Prop :=
  _writeChunk0 mem

theorem _write_chunk0 {mem : ExtHashMap Nat (BitVec 8)}
    (h : _writeLoaded mem) : _writeChunk0 mem :=
  h

theorem _write_at_8000003c {mem : ExtHashMap Nat (BitVec 8)}
    (h : _writeLoaded mem) :
      mem[(0x8000003c : Nat)]? = some (0x63 : BitVec 8) ∧
      mem[(0x8000003d : Nat)]? = some (0x04 : BitVec 8) ∧
      mem[(0x8000003e : Nat)]? = some (0x06 : BitVec 8) ∧
      mem[(0x8000003f : Nat)]? = some (0x02 : BitVec 8) :=
  have hc := _write_chunk0 h
  ⟨hc.1, hc.2.1, hc.2.2.1, hc.2.2.2.1⟩

theorem _write_at_80000040 {mem : ExtHashMap Nat (BitVec 8)}
    (h : _writeLoaded mem) :
      mem[(0x80000040 : Nat)]? = some (0x13 : BitVec 8) ∧
      mem[(0x80000041 : Nat)]? = some (0x07 : BitVec 8) ∧
      mem[(0x80000042 : Nat)]? = some (0x10 : BitVec 8) ∧
      mem[(0x80000043 : Nat)]? = some (0x10 : BitVec 8) :=
  have hc := _write_chunk0 h
  -- discipline: allow(R6-anon-projection-tower) generated code-pin projections (bounded, chunked)
  ⟨hc.2.2.2.2.1, hc.2.2.2.2.2.1, hc.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.1⟩

theorem _write_at_80000044 {mem : ExtHashMap Nat (BitVec 8)}
    (h : _writeLoaded mem) :
      mem[(0x80000044 : Nat)]? = some (0xb3 : BitVec 8) ∧
      mem[(0x80000045 : Nat)]? = some (0x86 : BitVec 8) ∧
      mem[(0x80000046 : Nat)]? = some (0xc5 : BitVec 8) ∧
      mem[(0x80000047 : Nat)]? = some (0x00 : BitVec 8) :=
  have hc := _write_chunk0 h
  -- discipline: allow(R6-anon-projection-tower) generated code-pin projections (bounded, chunked)
  ⟨hc.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.1⟩

theorem _write_at_80000048 {mem : ExtHashMap Nat (BitVec 8)}
    (h : _writeLoaded mem) :
      mem[(0x80000048 : Nat)]? = some (0x13 : BitVec 8) ∧
      mem[(0x80000049 : Nat)]? = some (0x17 : BitVec 8) ∧
      mem[(0x8000004a : Nat)]? = some (0x07 : BitVec 8) ∧
      mem[(0x8000004b : Nat)]? = some (0x03 : BitVec 8) :=
  have hc := _write_chunk0 h
  -- discipline: allow(R6-anon-projection-tower) generated code-pin projections (bounded, chunked)
  ⟨hc.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1⟩

theorem _write_at_8000004c {mem : ExtHashMap Nat (BitVec 8)}
    (h : _writeLoaded mem) :
      mem[(0x8000004c : Nat)]? = some (0x83 : BitVec 8) ∧
      mem[(0x8000004d : Nat)]? = some (0xc7 : BitVec 8) ∧
      mem[(0x8000004e : Nat)]? = some (0x05 : BitVec 8) ∧
      mem[(0x8000004f : Nat)]? = some (0x00 : BitVec 8) :=
  have hc := _write_chunk0 h
  -- discipline: allow(R6-anon-projection-tower) generated code-pin projections (bounded, chunked)
  ⟨hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1⟩

theorem _write_at_80000050 {mem : ExtHashMap Nat (BitVec 8)}
    (h : _writeLoaded mem) :
      mem[(0x80000050 : Nat)]? = some (0x93 : BitVec 8) ∧
      mem[(0x80000051 : Nat)]? = some (0x85 : BitVec 8) ∧
      mem[(0x80000052 : Nat)]? = some (0x15 : BitVec 8) ∧
      mem[(0x80000053 : Nat)]? = some (0x00 : BitVec 8) :=
  have hc := _write_chunk0 h
  -- discipline: allow(R6-anon-projection-tower) generated code-pin projections (bounded, chunked)
  ⟨hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1⟩

theorem _write_at_80000054 {mem : ExtHashMap Nat (BitVec 8)}
    (h : _writeLoaded mem) :
      mem[(0x80000054 : Nat)]? = some (0xb3 : BitVec 8) ∧
      mem[(0x80000055 : Nat)]? = some (0xe7 : BitVec 8) ∧
      mem[(0x80000056 : Nat)]? = some (0xe7 : BitVec 8) ∧
      mem[(0x80000057 : Nat)]? = some (0x00 : BitVec 8) :=
  have hc := _write_chunk0 h
  -- discipline: allow(R6-anon-projection-tower) generated code-pin projections (bounded, chunked)
  ⟨hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1⟩

theorem _write_at_80000058 {mem : ExtHashMap Nat (BitVec 8)}
    (h : _writeLoaded mem) :
      mem[(0x80000058 : Nat)]? = some (0x17 : BitVec 8) ∧
      mem[(0x80000059 : Nat)]? = some (0xb8 : BitVec 8) ∧
      mem[(0x8000005a : Nat)]? = some (0x01 : BitVec 8) ∧
      mem[(0x8000005b : Nat)]? = some (0x00 : BitVec 8) :=
  have hc := _write_chunk0 h
  -- discipline: allow(R6-anon-projection-tower) generated code-pin projections (bounded, chunked)
  ⟨hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1⟩

theorem _write_at_8000005c {mem : ExtHashMap Nat (BitVec 8)}
    (h : _writeLoaded mem) :
      mem[(0x8000005c : Nat)]? = some (0x23 : BitVec 8) ∧
      mem[(0x8000005d : Nat)]? = some (0x34 : BitVec 8) ∧
      mem[(0x8000005e : Nat)]? = some (0xf8 : BitVec 8) ∧
      mem[(0x8000005f : Nat)]? = some (0xca : BitVec 8) :=
  have hc := _write_chunk0 h
  -- discipline: allow(R6-anon-projection-tower) generated code-pin projections (bounded, chunked)
  ⟨hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1⟩

theorem _write_at_80000060 {mem : ExtHashMap Nat (BitVec 8)}
    (h : _writeLoaded mem) :
      mem[(0x80000060 : Nat)]? = some (0xe3 : BitVec 8) ∧
      mem[(0x80000061 : Nat)]? = some (0x96 : BitVec 8) ∧
      mem[(0x80000062 : Nat)]? = some (0xd5 : BitVec 8) ∧
      mem[(0x80000063 : Nat)]? = some (0xfe : BitVec 8) :=
  have hc := _write_chunk0 h
  -- discipline: allow(R6-anon-projection-tower) generated code-pin projections (bounded, chunked)
  ⟨hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1⟩

theorem _write_at_80000064 {mem : ExtHashMap Nat (BitVec 8)}
    (h : _writeLoaded mem) :
      mem[(0x80000064 : Nat)]? = some (0x13 : BitVec 8) ∧
      mem[(0x80000065 : Nat)]? = some (0x05 : BitVec 8) ∧
      mem[(0x80000066 : Nat)]? = some (0x06 : BitVec 8) ∧
      mem[(0x80000067 : Nat)]? = some (0x00 : BitVec 8) :=
  have hc := _write_chunk0 h
  -- discipline: allow(R6-anon-projection-tower) generated code-pin projections (bounded, chunked)
  ⟨hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1⟩

theorem _write_at_80000068 {mem : ExtHashMap Nat (BitVec 8)}
    (h : _writeLoaded mem) :
      mem[(0x80000068 : Nat)]? = some (0x67 : BitVec 8) ∧
      mem[(0x80000069 : Nat)]? = some (0x80 : BitVec 8) ∧
      mem[(0x8000006a : Nat)]? = some (0x00 : BitVec 8) ∧
      mem[(0x8000006b : Nat)]? = some (0x00 : BitVec 8) :=
  have hc := _write_chunk0 h
  -- discipline: allow(R6-anon-projection-tower) generated code-pin projections (bounded, chunked)
  ⟨hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2⟩

end Vsa.Sim.Code
