#!/usr/bin/env python3
"""Capstone part 1: compose svfProA..svfProE (Spec27-31): 0x80007654 -> 0x80007728."""

# transition agree window counts (number of ¬-hyps each hg takes)
NW = {1: 7, 2: 1, 3: 1, 4: 12, 5: 8}

# hoff names for slot rewrites (slot off-hex -> byte key K)
SLOT_K = {0x248: 584, 0x018: 24, 0x008: 8, 0x240: 576, 0x238: 568, 0x210: 528,
          0x050: 80, 0x048: 72, 0x230: 560, 0x228: 552, 0x220: 544, 0x218: 536,
          0x208: 520, 0x200: 512, 0x1f8: 504, 0x1f0: 496, 0x1e8: 488,
          0x0f0: 240, 0x0e0: 224, 0x028: 40, 0x040: 64, 0x058: 88, 0x068: 104,
          0x080: 128, 0x060: 96, 0x010: 16, 0x000: 0}

def om(n):
    return " ".join("(by omega)" for _ in range(n))

def slot_transport(name, off, val, t, prev):
    K = SLOT_K[off]
    conds = " ".join(f"(by rw [hoffC{K}] at ha1 ha2; omega)" for _ in range(NW[t]))
    return (f"  have {name}_{t} : SlotHolds vsp 0x{off:03x} {val} c{t}.σ.mem :=\n"
            f"    slotHolds_agree_pro vsp 0x{off:03x} {val} _ _\n"
            f"      (fun a ha1 ha2 => hg{t} a {conds}) {name}_{t-1}\n")

def byte_transport(name, keyexpr, val, t, prev):
    return (f"  have {name}_{t} : c{t}.σ.mem[{keyexpr}]? = some {val} :=\n"
            f"    (hg{t} _ {om(NW[t])}).trans {name}_{t-1}\n")

def pin4_transport(name, keyexpr, w, t):
    return (f"  have {name}_{t} : Pin4 c{t}.σ.mem ({keyexpr}) ({w}) :=\n"
            f"    Pin4_frame (fun k hk1 hk2 => hg{t} k {om(NW[t])}) {name}_{t-1}\n")

L = []
E = L.append

E("""import Vsa.Sim.SnprintfSpec27
import Vsa.Sim.SnprintfSpec28
import Vsa.Sim.SnprintfSpec29
import Vsa.Sim.SnprintfSpec30
import Vsa.Sim.SnprintfSpec31

/-!
# M3 Layer-3 — `SnprintfSpec35` : the composed svfprintf PROLOGUE
## `0x80007654` (entry) → `0x80007728` (parse-loop head)

Glue for segments A–E (SnprintfSpec27–31): one `Steps` chain over the whole
prologue — `sp -= 592`, the 15 callee-save/arg spills, `_localeconv_r` +
`strlen(".")` + `memset(sp+200,0,8)` inlined, the FILE `_flags` check, the
uio/iov and parse-state slot inits, and the locale loads — with every
Spec26-relevant slot fact transported to the exit memory.
Generated by /tmp/gen_spec35.py.
-/

open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail ConcurrencyInterfaceV1 Vsa
open Register
open Sail.ConcurrencyInterfaceV1.PreSail
open Vsa.Machine (MState Config Step Steps)
open Vsa.Logic

set_option maxHeartbeats 8000000
set_option maxRecDepth 1000000

namespace Vsa.Sim

/-- **The svfprintf prologue**, composed: `0x80007654 → 0x80007728` with all
fifteen spill slots, the uio/iov/parse-state inits, and the locale loads. -/
theorem svfPrologue_spec
    (vsp vra0 va0 vfile vfmt vva : BitVec 64)
    (vS0o vS1o vS2o vS3o vS4o vS5o vS6o vS7o vS8o vS9o vS10o vS11o : BitVec 64)
    (fl0 fl1 : BitVec 8)
    (c : Config)
    (hG : GoodState c.σ)
    (hsl0 : Vsa.Sim.Code.SvfprintfSliceLoaded c.σ.mem)
    (hlc0 : Vsa.Sim.Code._localeconv_rLoaded c.σ.mem)
    (hstr0 : Vsa.Sim.Code.StrlenLoaded c.σ.mem)
    (hms0 : Vsa.Sim.Code.MemsetLoaded c.σ.mem)
    (hlm0 : Vsa.Sim.Code.__locale_mb_cur_maxLoaded c.σ.mem)
    (hamb0 : Vsa.Sim.Code.__ascii_mbtowcLoaded c.σ.mem)
    (hpc : c.σ.regs.get? Register.PC = some (0x80007654#64))
    (hx2 : c.σ.regs.get? Register.x2 = some (vsp + (592#64)))
    (hx1 : c.σ.regs.get? Register.x1 = some vra0)
    (hx3 : c.σ.regs.get? Register.x3 = some (0x8001b510#64))
    (hx10 : c.σ.regs.get? Register.x10 = some va0)
    (hx11 : c.σ.regs.get? Register.x11 = some vfile)
    (hx12 : c.σ.regs.get? Register.x12 = some vfmt)
    (hx13 : c.σ.regs.get? Register.x13 = some vva)
    (hx8 : c.σ.regs.get? Register.x8 = some vS0o)
    (hx9 : c.σ.regs.get? Register.x9 = some vS1o)
    (hx22 : c.σ.regs.get? Register.x22 = some vS6o)
    (hx18 : c.σ.regs.get? Register.x18 = some vS2o)
    (hx19 : c.σ.regs.get? Register.x19 = some vS3o)
    (hx20 : c.σ.regs.get? Register.x20 = some vS4o)
    (hx21 : c.σ.regs.get? Register.x21 = some vS5o)
    (hx23 : c.σ.regs.get? Register.x23 = some vS7o)
    (hx24 : c.σ.regs.get? Register.x24 = some vS8o)
    (hx25 : c.σ.regs.get? Register.x25 = some vS9o)
    (hx26 : c.σ.regs.get? Register.x26 = some vS10o)
    (hx27 : c.σ.regs.get? Register.x27 = some vS11o)
    -- static data (ELF image facts)
    (hdp0 : c.σ.mem[(0x8001b898 : Nat)]? = some (0x70#8))
    (hdp1 : c.σ.mem[(0x8001b898 : Nat) + 1]? = some (0x97#8))
    (hdp2 : c.σ.mem[(0x8001b898 : Nat) + 2]? = some (0x01#8))
    (hdp3 : c.σ.mem[(0x8001b898 : Nat) + 3]? = some (0x80#8))
    (hdp4 : c.σ.mem[(0x8001b898 : Nat) + 4]? = some (0x00#8))
    (hdp5 : c.σ.mem[(0x8001b898 : Nat) + 5]? = some (0x00#8))
    (hdp6 : c.σ.mem[(0x8001b898 : Nat) + 6]? = some (0x00#8))
    (hdp7 : c.σ.mem[(0x8001b898 : Nat) + 7]? = some (0x00#8))
    (hdb0 : c.σ.mem[(0x80019770 : Nat)]? = some (0x2e#8))
    (hdb1 : c.σ.mem[(0x80019770 : Nat) + 1]? = some (0x00#8))
    (hdb2 : c.σ.mem[(0x80019770 : Nat) + 2]? = some (0x00#8))
    (hdb3 : c.σ.mem[(0x80019770 : Nat) + 3]? = some (0x00#8))
    (hdb4 : c.σ.mem[(0x80019770 : Nat) + 4]? = some (0x00#8))
    (hdb5 : c.σ.mem[(0x80019770 : Nat) + 5]? = some (0x00#8))
    (hdb6 : c.σ.mem[(0x80019770 : Nat) + 6]? = some (0x00#8))
    (hdb7 : c.σ.mem[(0x80019770 : Nat) + 7]? = some (0x00#8))
    (hfn0 : c.σ.mem[(0x8001b880 : Nat)]? = some (0x68#8))
    (hfn1 : c.σ.mem[(0x8001b880 : Nat) + 1]? = some (0x22#8))
    (hfn2 : c.σ.mem[(0x8001b880 : Nat) + 2]? = some (0x01#8))
    (hfn3 : c.σ.mem[(0x8001b880 : Nat) + 3]? = some (0x80#8))
    (hfn4 : c.σ.mem[(0x8001b880 : Nat) + 4]? = some (0x00#8))
    (hfn5 : c.σ.mem[(0x8001b880 : Nat) + 5]? = some (0x00#8))
    (hfn6 : c.σ.mem[(0x8001b880 : Nat) + 6]? = some (0x00#8))
    (hfn7 : c.σ.mem[(0x8001b880 : Nat) + 7]? = some (0x00#8))
    -- the FILE `_flags` halfword (caller struct; __SCLE clear)
    (hfl0B : c.σ.mem[vfile.toNat + 16]? = some fl0)
    (hfl1B : c.σ.mem[vfile.toNat + 17]? = some fl1)
    (hflagB : (zero_extend (m := 64) ((fl1.append fl0) : BitVec (8 * 2)) : BitVec 64)
        &&& sign_extend (m := 64) (0x080#12) = 0#64)
    (hfilelo : vsp.toNat + 592 ≤ vfile.toNat)
    (hfilehi : vfile.toNat + 24 ≤ 0x100000000)
    (hfileal : vfile.toNat % 8 = 0)
    (hsplo : 0x8001c000 ≤ vsp.toNat)
    (hsphi : vsp.toNat + 592 ≤ 0x100000000)
    (hspal : vsp.toNat % 8 = 0)
    (htick : c.tick < 2) :
    ∃ c' : Config, Steps c c' ∧ GoodState c'.σ ∧
      c'.σ.regs.get? Register.PC = some (0x80007728#64) ∧
      c'.σ.regs.get? Register.x2 = some vsp ∧
      c'.σ.regs.get? Register.x3 = some (0x8001b510#64) ∧
      c'.σ.regs.get? Register.x8 = some va0 ∧
      c'.σ.regs.get? Register.x9 = some (0x8001b798#64) ∧
      c'.σ.regs.get? Register.x22 = some vfmt ∧
      c'.σ.regs.get? Register.x20 = some (0x80012268#64) ∧
      c'.σ.regs.get? Register.x18 = some (16#64) ∧
      c'.σ.regs.get? Register.x19 = some (37#64) ∧
      c'.σ.regs.get? Register.x21 = some (vsp + sign_extend (m := 64) (0x160#12)) ∧
      c'.σ.regs.get? Register.x23 = some (vsp + sign_extend (m := 64) (0x160#12)) ∧
      c'.σ.regs.get? Register.x24 = some vS8o ∧
      c'.σ.regs.get? Register.x25 = some vS9o ∧
      c'.σ.regs.get? Register.x26 = some vS10o ∧
      c'.σ.regs.get? Register.x27 = some vS11o ∧
      SlotHolds vsp 0x248 vra0 c'.σ.mem ∧
      SlotHolds vsp 0x018 vva c'.σ.mem ∧
      SlotHolds vsp 0x008 vfile c'.σ.mem ∧
      SlotHolds vsp 0x240 vS0o c'.σ.mem ∧
      SlotHolds vsp 0x238 vS1o c'.σ.mem ∧
      SlotHolds vsp 0x230 vS2o c'.σ.mem ∧
      SlotHolds vsp 0x228 vS3o c'.σ.mem ∧
      SlotHolds vsp 0x220 vS4o c'.σ.mem ∧
      SlotHolds vsp 0x218 vS5o c'.σ.mem ∧
      SlotHolds vsp 0x210 vS6o c'.σ.mem ∧
      SlotHolds vsp 0x208 vS7o c'.σ.mem ∧
      SlotHolds vsp 0x200 vS8o c'.σ.mem ∧
      SlotHolds vsp 0x1f8 vS9o c'.σ.mem ∧
      SlotHolds vsp 0x1f0 vS10o c'.σ.mem ∧
      SlotHolds vsp 0x1e8 vS11o c'.σ.mem ∧
      SlotHolds vsp 0x050 (0x80019770#64) c'.σ.mem ∧
      SlotHolds vsp 0x048 (1#64) c'.σ.mem ∧
      SlotHolds vsp 0x0f0 (0#64) c'.σ.mem ∧
      Pin4 c'.σ.mem (vsp.toNat + 232) (swData (0#64)) ∧
      SlotHolds vsp 0x0e0 (vsp + sign_extend (m := 64) (0x160#12)) c'.σ.mem ∧
      SlotHolds vsp 0x028 (0#64) c'.σ.mem ∧
      SlotHolds vsp 0x040 (0#64) c'.σ.mem ∧
      SlotHolds vsp 0x058 (0#64) c'.σ.mem ∧
      SlotHolds vsp 0x068 (0#64) c'.σ.mem ∧
      SlotHolds vsp 0x080 (0#64) c'.σ.mem ∧
      SlotHolds vsp 0x060 (0#64) c'.σ.mem ∧
      SlotHolds vsp 0x010 (0#64) c'.σ.mem ∧
      SlotHolds vsp 0x000 vfmt c'.σ.mem ∧
      (c'.σ.mem[vsp.toNat + 200]? = some (0x00#8) ∧
        c'.σ.mem[vsp.toNat + 201]? = some (0x00#8) ∧
        c'.σ.mem[vsp.toNat + 202]? = some (0x00#8) ∧
        c'.σ.mem[vsp.toNat + 203]? = some (0x00#8) ∧
        c'.σ.mem[vsp.toNat + 204]? = some (0x00#8) ∧
        c'.σ.mem[vsp.toNat + 205]? = some (0x00#8) ∧
        c'.σ.mem[vsp.toNat + 206]? = some (0x00#8) ∧
        c'.σ.mem[vsp.toNat + 207]? = some (0x00#8)) ∧
      (∀ a : Nat, ¬(vsp.toNat ≤ a ∧ a < vsp.toNat + 592) →
        c'.σ.mem[a]? = c.σ.mem[a]?) ∧
      Vsa.Sim.Code.SvfprintfSliceLoaded c'.σ.mem ∧
      Vsa.Sim.Code.__locale_mb_cur_maxLoaded c'.σ.mem ∧
      Vsa.Sim.Code.__ascii_mbtowcLoaded c'.σ.mem ∧
      c'.tick < 2 ∧ (∃ u, c'.σ.regs.get? Register.minstret = some u) := by""")

# hoffCs (capstone copies of the slot-key rewrites)
E("  have htoh : tohostAddr = 0x8001ad00 := rfl")
for off, K in SLOT_K.items():
    E(f"  have hoffC{K} : (vsp + sign_extend (m := 64) (0x{off:03x}#12)).toNat"
      f" = vsp.toNat + {K} := ptr_addoff vsp _ {K} (by decide) (by omega)")

# ---- segment A ----
E("""  -- ===== segment A (Spec27): 0x7654 → 0x768c =====
  obtain ⟨c1, hs1, hG1, hpc1, h1x2, h1x1, h1x3, h1x8, h1x9, h1x22, h1x10, h1x14,
      h1x12, h1x13, h1x18, h1x19, h1x20, h1x21, h1x23, h1x24, h1x25, h1x26, h1x27,
      hS248_1, hS018_1, hS008_1, hS240_1, hS238_1, hS210_1, hS050_1,
      hg1, hsl1, hlc1, hstr1, hms1, hlm1, hamb1, hi1, hmi1⟩ :=
    svfProA_spec vsp vra0 va0 vfile vfmt vva vS0o vS1o vS2o vS3o vS4o vS5o vS6o vS7o
      vS8o vS9o vS10o vS11o c hG hsl0 hlc0 hstr0 hms0 hlm0 hamb0 hpc hx2 hx1 hx3
      hx10 hx11 hx12 hx13 hx8 hx9 hx22 hx18 hx19 hx20 hx21 hx23 hx24 hx25 hx26 hx27
      hdp0 hdp1 hdp2 hdp3 hdp4 hdp5 hdp6 hdp7 hsplo hsphi hspal htick
  -- ===== segment B (Spec28): 0x768c → 0x76a0 =====
  obtain ⟨c2, hs2, hG2, hpc2, h2x2, h2x1, h2x3, h2x8, h2x9, h2x22, h2x10, h2x11,
      h2x12, h2x18, h2x19, h2x20, h2x21, h2x23, h2x24, h2x25, h2x26, h2x27,
      hS048_2, hg2, hsl2, hms2, hlm2, hamb2, hi2, hmi2⟩ :=
    svfProB_spec vsp va0 vfile vfmt vS2o vS3o vS4o vS5o vS7o vS8o vS9o vS10o vS11o
      c1 hG1 hsl1 hstr1 hms1 hlm1 hamb1 hpc1 h1x2 h1x3 h1x8 h1x9 h1x22 h1x10
      h1x18 h1x19 h1x20 h1x21 h1x23 h1x24 h1x25 h1x26 h1x27
      ((hg1 _ (by omega) (by omega) (by omega) (by omega) (by omega) (by omega)
        (by omega)).trans hdb0)
      ((hg1 _ (by omega) (by omega) (by omega) (by omega) (by omega) (by omega)
        (by omega)).trans hdb1)
      ((hg1 _ (by omega) (by omega) (by omega) (by omega) (by omega) (by omega)
        (by omega)).trans hdb2)
      ((hg1 _ (by omega) (by omega) (by omega) (by omega) (by omega) (by omega)
        (by omega)).trans hdb3)
      ((hg1 _ (by omega) (by omega) (by omega) (by omega) (by omega) (by omega)
        (by omega)).trans hdb4)
      ((hg1 _ (by omega) (by omega) (by omega) (by omega) (by omega) (by omega)
        (by omega)).trans hdb5)
      ((hg1 _ (by omega) (by omega) (by omega) (by omega) (by omega) (by omega)
        (by omega)).trans hdb6)
      ((hg1 _ (by omega) (by omega) (by omega) (by omega) (by omega) (by omega)
        (by omega)).trans hdb7)
      hsplo hsphi hspal hi1
  -- ===== segment C (Spec29): 0x76a0 → 0x76bc =====
  obtain ⟨c3, hs3, hG3, hpc3, h3x2, h3x1, h3x3, h3x8, h3x9, h3x22, h3x18, h3x19,
      h3x20, h3x21, h3x23, h3x24, h3x25, h3x26, h3x27,
      hz200_3, hz201_3, hz202_3, hz203_3, hz204_3, hz205_3, hz206_3, hz207_3,
      hg3, hsl3, hms3, hlm3, hamb3, hi3, hmi3⟩ :=
    svfProC_spec vsp va0 vfile vfmt vS2o vS3o vS4o vS5o vS7o vS8o vS9o vS10o vS11o
      fl0 fl1 c2 hG2 hsl2 hms2 hlm2 hamb2 hpc2 h2x2 h2x3 h2x8 h2x9 h2x22 h2x10
      h2x11 h2x12 h2x18 h2x19 h2x20 h2x21 h2x23 h2x24 h2x25 h2x26 h2x27
      ((hg2 _ (by omega)).trans ((hg1 _ (by omega) (by omega) (by omega) (by omega)
        (by omega) (by omega) (by omega)).trans hfl0B))
      ((hg2 _ (by omega)).trans ((hg1 _ (by omega) (by omega) (by omega) (by omega)
        (by omega) (by omega) (by omega)).trans hfl1B))
      hflagB hfilelo hfilehi hfileal hsplo hsphi hspal hi2
  -- ===== segment D (Spec30): 0x76bc → 0x76f4 =====
  obtain ⟨c4, hs4, hG4, hpc4, h4x2, h4x3, h4x8, h4x9, h4x22, h4x18, h4x19, h4x20,
      h4x21, h4x23, h4x24, h4x25, h4x26, h4x27,
      hS230_4, hS228_4, hS220_4, hS218_4, hS208_4, hS200_4, hS1f8_4, hS1f0_4,
      hS1e8_4, hS0f0_4, hP232_4, hS0e0_4, hg4, hsl4, hms4, hlm4, hamb4, hi4, hmi4⟩ :=
    svfProD_spec vsp va0 vfile vfmt vS2o vS3o vS4o vS5o vS7o vS8o vS9o vS10o vS11o
      c3 hG3 hsl3 hms3 hlm3 hamb3 hpc3 h3x2 h3x3 h3x8 h3x9 h3x22 h3x18 h3x19
      h3x20 h3x21 h3x23 h3x24 h3x25 h3x26 h3x27 hsplo hsphi hspal hi3
  -- ===== segment E (Spec31): 0x76f4 → 0x7728 =====
  obtain ⟨c5, hs5, hG5, hpc5, h5x2, h5x3, h5x8, h5x9, h5x22, h5x20, h5x18, h5x19,
      h5x21, h5x23, h5x24, h5x25, h5x26, h5x27,
      hS028_5, hS040_5, hS058_5, hS068_5, hS080_5, hS060_5, hS010_5, hS000_5,
      hg5, hsl5, hms5, hlm5, hamb5, hi5, hmi5⟩ :=
    svfProE_spec vsp va0 vfile vfmt vS8o vS9o vS10o vS11o c4 hG4 hsl4 hms4 hlm4
      hamb4 hpc4 h4x2 h4x3 h4x8 h4x9 h4x22 h4x21 h4x23 h4x24 h4x25 h4x26 h4x27
      (hbelow4 _ (by omega) |>.trans hfn0) (hbelow4 _ (by omega) |>.trans hfn1)
      (hbelow4 _ (by omega) |>.trans hfn2) (hbelow4 _ (by omega) |>.trans hfn3)
      (hbelow4 _ (by omega) |>.trans hfn4) (hbelow4 _ (by omega) |>.trans hfn5)
      (hbelow4 _ (by omega) |>.trans hfn6) (hbelow4 _ (by omega) |>.trans hfn7)
      hsplo hsphi hspal hi4""")

body = "\n".join(L)

# insert hbelow4 before segment E application
hbelow = """  -- pointwise below-frame agreement c4 ↔ c0 (for the static locale bytes)
  have hbelow4 : ∀ a : Nat, a < vsp.toNat → c4.σ.mem[a]? = c.σ.mem[a]? := by
    intro a ha
    exact (hg4 a (by omega) (by omega) (by omega) (by omega) (by omega) (by omega)
        (by omega) (by omega) (by omega) (by omega) (by omega) (by omega)).trans
      ((hg3 a (by omega)).trans ((hg2 a (by omega)).trans
        (hg1 a (by omega) (by omega) (by omega) (by omega) (by omega) (by omega)
          (by omega))))
"""
body = body.replace("  -- ===== segment E (Spec31): 0x76f4 → 0x7728 =====",
                    hbelow + "  -- ===== segment E (Spec31): 0x76f4 → 0x7728 =====")

# ---- transports to c5 ----
T = []
# Spec27 slots through T2..T5
for (nm, off, val) in [("hS248", 0x248, "vra0"), ("hS018", 0x018, "vva"),
                       ("hS008", 0x008, "vfile"), ("hS240", 0x240, "vS0o"),
                       ("hS238", 0x238, "vS1o"), ("hS210", 0x210, "vS6o"),
                       ("hS050", 0x050, "(0x80019770#64)")]:
    for t in (2, 3, 4, 5):
        T.append(slot_transport(nm, off, val, t, None))
# Spec28 slot through T3..T5
for t in (3, 4, 5):
    T.append(slot_transport("hS048", 0x048, "(1#64)", t, None))
# Spec29 bytes through T4, T5
for j in range(8):
    for t in (4, 5):
        T.append(byte_transport(f"hz{200+j}", f"vsp.toNat + {200+j}", "(0x00#8)", t, None))
# Spec30 slots + Pin4 through T5
for (nm, off, val) in [("hS230", 0x230, "vS2o"), ("hS228", 0x228, "vS3o"),
                       ("hS220", 0x220, "vS4o"), ("hS218", 0x218, "vS5o"),
                       ("hS208", 0x208, "vS7o"), ("hS200", 0x200, "vS8o"),
                       ("hS1f8", 0x1f8, "vS9o"), ("hS1f0", 0x1f0, "vS10o"),
                       ("hS1e8", 0x1e8, "vS11o"), ("hS0f0", 0x0f0, "(0#64)"),
                       ("hS0e0", 0x0e0, "(vsp + sign_extend (m := 64) (0x160#12))")]:
    T.append(slot_transport(nm, off, val, 5, None))
T.append(pin4_transport("hP232", "vsp.toNat + 232", "swData (0#64)", 5))

# combined out-of-frame agree
T.append("""  have hgAll : ∀ a : Nat, ¬(vsp.toNat ≤ a ∧ a < vsp.toNat + 592) →
      c5.σ.mem[a]? = c.σ.mem[a]? := by
    intro a ha
    exact (hg5 a (by omega) (by omega) (by omega) (by omega) (by omega) (by omega)
        (by omega) (by omega)).trans
      ((hg4 a (by omega) (by omega) (by omega) (by omega) (by omega) (by omega)
        (by omega) (by omega) (by omega) (by omega) (by omega) (by omega)).trans
      ((hg3 a (by omega)).trans ((hg2 a (by omega)).trans
        (hg1 a (by omega) (by omega) (by omega) (by omega) (by omega) (by omega)
          (by omega)))))
""")

final = """  exact ⟨c5, ((((hs1.trans hs2).trans hs3).trans hs4).trans hs5), hG5, hpc5,
    h5x2, h5x3, h5x8, h5x9, h5x22, h5x20, h5x18, h5x19, h5x21, h5x23,
    h5x24, h5x25, h5x26, h5x27,
    hS248_5, hS018_5, hS008_5, hS240_5, hS238_5, hS230_5, hS228_5, hS220_5,
    hS218_5, hS210_5, hS208_5, hS200_5, hS1f8_5, hS1f0_5, hS1e8_5,
    hS050_5, hS048_5, hS0f0_5, hP232_5, hS0e0_5,
    hS028_5, hS040_5, hS058_5, hS068_5, hS080_5, hS060_5, hS010_5, hS000_5,
    ⟨hz200_5, hz201_5, hz202_5, hz203_5, hz204_5, hz205_5, hz206_5, hz207_5⟩,
    hgAll, hsl5, hlm5, hamb5, hi5, hmi5⟩

end Vsa.Sim
"""

out = body + "\n" + "".join(T) + final
open("Vsa/Sim/SnprintfSpec35.lean", "w").write(out)
print("wrote Vsa/Sim/SnprintfSpec35.lean", len(out.splitlines()), "lines")
