import Vsa.Sim.ErrorSiteRows
import Vsa.Sim.ErrorSiteApplied
import Vsa.Sim.InterpSimBundle
import Vsa.Sim.InterpSimFinal
import Vsa.Sim.rows.ErrSitesBatch0
import Vsa.Sim.rows.ErrSitesBatch1
import Vsa.Sim.rows.ErrSitesBatch2
import Vsa.Sim.rows.ErrSitesBatch3

/-!
# `ErrorRouting` — the M5 error-family routing (herrFam, GENERATED)

Every `errFamily_of_sites` minor premise (`InterpSimBundle.lean`) is
discharged UNIFORMLY by one `errRow` application (`ErrorSiteRows.lean`),
exactly as `ErrorSiteApplied.row_hNegType_applied` discharges `hNegType`:
`SitePre` is pinned to the site's `JalErrPre g inp m0 <pc> <bytes>`, the
per-site `Triple T` is supplied by the generated `errSite_<pc> g inp m0`
(proved unconditionally by `#derive_error_site`), and the shared L7/L8
`SC`/`out`/`HT` are threaded once via the `ErrShared` bundle.

The ONLY per-premise residual is `hsite` — the M4 caller-linkage that the
config `c` is parked at this error node's `jal runtime_error`.  `errRow` is
polymorphic in `SitePre`, so the premise→site assignment (`m5_error_routing.tsv`)
only fixes the `JalErrPre <pc>` shape of that reachability residual.

Two premises are NOT `jal runtime_error` sites (`hBadClosure`, `hTopAbrupt`):
they carry no `JalErrPre`/`errSite`/`route_` and are threaded straight through
`errFamily_of_sites` as raw `hsite` residuals.

GENERATED by `scripts/gen_m5_error_routing.py`.  DO NOT hand-edit.
NO sorry/axiom/native_decide/bv_decide; no Mathlib.
-/

open LeanRV64DExecutable Vsa
open Vsa.Machine (MState Config Steps Halts)
open Vsa.Logic (Triple)
open Vsa.While
open Register

namespace Vsa.Sim

local notation "SpecSt" => Vsa.While.St

/-- **The shared L7/L8 error bundle** — the SAME for all 42 rows: the ghost
frame `g`, the ErrorIn pointer `inp`, the captured callee-saveds, the entry
memory `m0`, the `SnprintfContract SC` (M3 snprintf input), and the error
message `out` with its `ErrorTailChain HT` (M6 exit-tail input). -/
structure ErrShared where
  g : (R : Register) → Option (RegisterType R)
  inp : BitVec 64
  ra0 : BitVec 64
  s0v : BitVec 64
  s1v : BitVec 64
  s2v : BitVec 64
  s3v : BitVec 64
  s4v : BitVec 64
  s5v : BitVec 64
  s6v : BitVec 64
  s7v : BitVec 64
  s8v : BitVec 64
  s9v : BitVec 64
  s10v : BitVec 64
  s11v : BitVec 64
  spv : BitVec 64
  m0 : Std.ExtHashMap Nat (BitVec 8)
  SC : SnprintfContract g inp ra0 s0v s1v s2v s3v s4v s5v s6v s7v s8v s9v s10v s11v spv m0
  out : String
  HT : ErrorTailChain ra0 ExitStorePreExit out

/-- Route `hVarUndef` → `errSite_80003b54` (var lookup miss (EvalErr.varUndef)). -/
theorem route_hVarUndef (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003b54#64 0xef#8 0xf0#8 0x4f#8 0xa5#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (x : String),
      st.store.get? env x = none → ErrHalts c :=
  fun c _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003b54#64 0xef#8 0xf0#8 0x4f#8 0xa5#8)
      (errSite_80003b54 S.g S.inp S.m0) c (hsite c)

/-- Route `hAssignE` → `errSite_80003b9c` (assign rhs error (EvalErr.assignE)). -/
theorem route_hAssignE (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003b9c#64 0xef#8 0xf0#8 0xcf#8 0xa0#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (x : String) (e : Expr),
      EvalErr st d env e → ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003b9c#64 0xef#8 0xf0#8 0xcf#8 0xa0#8)
      (errSite_80003b9c S.g S.inp S.m0) c (hsite c)

/-- Route `hAssignUnbound` → `errSite_80003bc8` (assign unbound (EvalErr.assignUnbound)). -/
theorem route_hAssignUnbound (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003bc8#64 0xef#8 0xf0#8 0x0f#8 0x9e#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (x : String) (e : Expr)
      (st' : SpecSt) (v : Value),
      EvalE st d env e st' v → st'.store.set? env x v = none → ErrHalts c :=
  fun c _ _ _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003bc8#64 0xef#8 0xf0#8 0x0f#8 0x9e#8)
      (errSite_80003bc8 S.g S.inp S.m0) c (hsite c)

/-- Route `hBinaryL` → `errSite_80003c10` (binary lhs error (EvalErr.binaryL)). -/
theorem route_hBinaryL (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003c10#64 0xef#8 0xf0#8 0x8f#8 0x99#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (op : BinOp) (l r : Expr),
      EvalErr st d env l → ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003c10#64 0xef#8 0xf0#8 0x8f#8 0x99#8)
      (errSite_80003c10 S.g S.inp S.m0) c (hsite c)

/-- Route `hBinaryR` → `errSite_80003c7c` (binary rhs error (EvalErr.binaryR)). -/
theorem route_hBinaryR (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003c7c#64 0xef#8 0xf0#8 0xcf#8 0x92#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (op : BinOp) (l r : Expr)
      (st' : SpecSt) (lv : Value),
      EvalE st d env l st' lv → EvalErr st' d env r → ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003c7c#64 0xef#8 0xf0#8 0xcf#8 0x92#8)
      (errSite_80003c7c S.g S.inp S.m0) c (hsite c)

/-- Route `hBinaryOp` → `errSite_80003cc4` (binary op none (EvalErr.binaryOp)). -/
theorem route_hBinaryOp (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003cc4#64 0xef#8 0xf0#8 0x4f#8 0x8e#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (op : BinOp) (l r : Expr)
      (st' st'' : SpecSt) (lv rv : Value),
      EvalE st d env l st' lv → EvalE st' d env r st'' rv →
      binOpSem st''.store op lv rv = none → ErrHalts c :=
  fun c _ _ _ _ _ _ _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003cc4#64 0xef#8 0xf0#8 0x4f#8 0x8e#8)
      (errSite_80003cc4 S.g S.inp S.m0) c (hsite c)

/-- Route `hOrL` → `errSite_80003ce8` (or lhs error (EvalErr.orL)). -/
theorem route_hOrL (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003ce8#64 0xef#8 0xf0#8 0x0f#8 0x8c#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (l r : Expr),
      EvalErr st d env l → ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003ce8#64 0xef#8 0xf0#8 0x0f#8 0x8c#8)
      (errSite_80003ce8 S.g S.inp S.m0) c (hsite c)

/-- Route `hOrR` → `errSite_80003d14` (or rhs error (EvalErr.orR)). -/
theorem route_hOrR (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003d14#64 0xef#8 0xf0#8 0x4f#8 0x89#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (l r : Expr) (st' : SpecSt)
      (lv : Value),
      EvalE st d env l st' lv → lv.truthy = false → EvalErr st' d env r →
      ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003d14#64 0xef#8 0xf0#8 0x4f#8 0x89#8)
      (errSite_80003d14 S.g S.inp S.m0) c (hsite c)

/-- Route `hAndL` → `errSite_80003d5c` (and lhs error (EvalErr.andL)). -/
theorem route_hAndL (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003d5c#64 0xef#8 0xf0#8 0xcf#8 0x84#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (l r : Expr),
      EvalErr st d env l → ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003d5c#64 0xef#8 0xf0#8 0xcf#8 0x84#8)
      (errSite_80003d5c S.g S.inp S.m0) c (hsite c)

/-- Route `hAndR` → `errSite_80003da0` (and rhs error (EvalErr.andR)). -/
theorem route_hAndR (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003da0#64 0xef#8 0xf0#8 0x8f#8 0x80#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (l r : Expr) (st' : SpecSt)
      (lv : Value),
      EvalE st d env l st' lv → lv.truthy = true → EvalErr st' d env r →
      ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003da0#64 0xef#8 0xf0#8 0x8f#8 0x80#8)
      (errSite_80003da0 S.g S.inp S.m0) c (hsite c)

/-- Route `hUnaryE` → `errSite_80003950` (unary sub error (EvalErr.unaryE)). -/
theorem route_hUnaryE (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003950#64 0xef#8 0xf0#8 0x8f#8 0xc5#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (op : UnOp) (e : Expr),
      EvalErr st d env e → ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003950#64 0xef#8 0xf0#8 0x8f#8 0xc5#8)
      (errSite_80003950 S.g S.inp S.m0) c (hsite c)

/-- Route `hNegType` → `errSite_800034e4` (neg type error (EvalErr.negType) PROVEN). -/
theorem route_hNegType (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x800034e4#64 0xef#8 0xf0#8 0x5f#8 0x8c#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (e : Expr) (st' : SpecSt)
      (v : Value),
      EvalE st d env e st' v → (∀ n : Int, v ≠ .int n) → ErrHalts c :=
  fun c _ _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x800034e4#64 0xef#8 0xf0#8 0x5f#8 0x8c#8)
      (errSite_800034e4 S.g S.inp S.m0) c (hsite c)

/-- Route `hCallF` → `errSite_80003de8` (call fn error (EvalErr.callF)). -/
theorem route_hCallF (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003de8#64 0xef#8 0xe0#8 0x1f#8 0xfc#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (f : Expr) (args : List Expr),
      EvalErr st d env f → ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003de8#64 0xef#8 0xe0#8 0x1f#8 0xfc#8)
      (errSite_80003de8 S.g S.inp S.m0) c (hsite c)

/-- Route `hCallArgs` → `errSite_80003e98` (call args error (EvalErr.callArgs)). -/
theorem route_hCallArgs (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003e98#64 0xef#8 0xe0#8 0x1f#8 0xf1#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (f : Expr) (args : List Expr)
      (st' : SpecSt) (fv : Value),
      EvalE st d env f st' fv → EvalArgsErr st' d env args → ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003e98#64 0xef#8 0xe0#8 0x1f#8 0xf1#8)
      (errSite_80003e98 S.g S.inp S.m0) c (hsite c)

/-- Route `hCallC` → `errSite_80003f58` (call callErr (EvalErr.callC)). -/
theorem route_hCallC (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003f58#64 0xef#8 0xe0#8 0x1f#8 0xe5#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (f : Expr) (args : List Expr)
      (st' st'' : SpecSt) (fv : Value) (vs : List Value),
      EvalE st d env f st' fv → EvalArgs st' d env args st'' vs →
      CallErr st'' d fv vs → ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003f58#64 0xef#8 0xe0#8 0x1f#8 0xe5#8)
      (errSite_80003f58 S.g S.inp S.m0) c (hsite c)

/-- Route `hArgsHead` → `errSite_80003fac` (args head error (EvalArgsErr.head)). -/
theorem route_hArgsHead (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003fac#64 0xef#8 0xe0#8 0xdf#8 0xdf#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (e : Expr) (es : List Expr),
      EvalErr st d env e → ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003fac#64 0xef#8 0xe0#8 0xdf#8 0xdf#8)
      (errSite_80003fac S.g S.inp S.m0) c (hsite c)

/-- Route `hArgsTail` → `errSite_80003fdc` (args tail error (EvalArgsErr.tail)). -/
theorem route_hArgsTail (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003fdc#64 0xef#8 0xe0#8 0xdf#8 0xdc#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (e : Expr) (es : List Expr)
      (st' : SpecSt) (v : Value),
      EvalE st d env e st' v → EvalArgsErr st' d env es → ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003fdc#64 0xef#8 0xe0#8 0xdf#8 0xdc#8)
      (errSite_80003fdc S.g S.inp S.m0) c (hsite c)

/-- Route `hNotCallable` → `errSite_80002e90` (not callable (CallErr.notCallable)). -/
theorem route_hNotCallable (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80002e90#64 0xef#8 0xf0#8 0x9f#8 0xf1#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (fv : Value) (vs : List Value),
      (∀ a, fv ≠ .closure a) → (∀ f, fv ≠ .native f) → ErrHalts c :=
  fun c _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80002e90#64 0xef#8 0xf0#8 0x9f#8 0xf1#8)
      (errSite_80002e90 S.g S.inp S.m0) c (hsite c)

/-- Route `hArity` → `errSite_80002ebc` (arity mismatch (CallErr.arity)). -/
theorem route_hArity (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80002ebc#64 0xef#8 0xf0#8 0xdf#8 0xee#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (a : Addr) (cd : ClosureData) (vs : List Value),
      st.store.closures[a]? = some cd → vs.length ≠ cd.params.length → ErrHalts c :=
  fun c _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80002ebc#64 0xef#8 0xf0#8 0xdf#8 0xee#8)
      (errSite_80002ebc S.g S.inp S.m0) c (hsite c)

/-- Route `hDepth` → `errSite_80002e90` (depth exceeded (CallErr.depth)). -/
theorem route_hDepth (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80002e90#64 0xef#8 0xf0#8 0x9f#8 0xf1#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (a : Addr) (cd : ClosureData) (vs : List Value),
      st.store.closures[a]? = some cd → vs.length = cd.params.length →
      ¬ d < maxCallDepth → ErrHalts c :=
  fun c _ _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80002e90#64 0xef#8 0xf0#8 0x9f#8 0xf1#8)
      (errSite_80002e90 S.g S.inp S.m0) c (hsite c)

/-- Route `hBody` → `errSite_80002ebc` (call body error (CallErr.body)). -/
theorem route_hBody (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80002ebc#64 0xef#8 0xf0#8 0xdf#8 0xee#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (a : Addr) (cd : ClosureData) (vs : List Value)
      (store' : Store) (frame : Addr),
      st.store.closures[a]? = some cd → vs.length = cd.params.length →
      d < maxCallDepth → st.store.allocFrame (some cd.env) = (store', frame) →
      ExecSeqErr ⟨(cd.params.zip vs).foldl (fun s (x, v) => s.define frame x v) store',
        st.out⟩ (d + 1) frame cd.body → ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80002ebc#64 0xef#8 0xf0#8 0xdf#8 0xee#8)
      (errSite_80002ebc S.g S.inp S.m0) c (hsite c)

/-- Route `hEscape` → `errSite_80002e90` (break/cont escape (CallErr.escape)). -/
theorem route_hEscape (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80002e90#64 0xef#8 0xf0#8 0x9f#8 0xf1#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (a : Addr) (cd : ClosureData) (vs : List Value)
      (store' : Store) (frame : Addr) (st' : SpecSt) (status : Status),
      st.store.closures[a]? = some cd → vs.length = cd.params.length →
      d < maxCallDepth → st.store.allocFrame (some cd.env) = (store', frame) →
      ExecSeq ⟨(cd.params.zip vs).foldl (fun s (x, v) => s.define frame x v) store',
        st.out⟩ (d + 1) frame cd.body st' status →
      (status = .brk ∨ status = .cont) → ErrHalts c :=
  fun c _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80002e90#64 0xef#8 0xf0#8 0x9f#8 0xf1#8)
      (errSite_80002e90 S.g S.inp S.m0) c (hsite c)

/-- Route `hAssertFail` → `errSite_80002ebc` (assert fail (CallErr.assertFail)). -/
theorem route_hAssertFail (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80002ebc#64 0xef#8 0xf0#8 0xdf#8 0xee#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (vs : List Value) (v m : Value),
      (vs = [v] ∨ vs = [v, m]) → v.truthy = false → ErrHalts c :=
  fun c _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80002ebc#64 0xef#8 0xf0#8 0xdf#8 0xee#8)
      (errSite_80002ebc S.g S.inp S.m0) c (hsite c)

/-- Route `hAssertArity` → `errSite_80002e90` (assert arity (CallErr.assertArity)). -/
theorem route_hAssertArity (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80002e90#64 0xef#8 0xf0#8 0x9f#8 0xf1#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (vs : List Value),
      (∀ v, vs ≠ [v]) → (∀ v m, vs ≠ [v, m]) → ErrHalts c :=
  fun c _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80002e90#64 0xef#8 0xf0#8 0x9f#8 0xf1#8)
      (errSite_80002e90 S.g S.inp S.m0) c (hsite c)

/-- Route `hExpr` → `errSite_80003b54` (stmt expr error (ExecErr.expr)). -/
theorem route_hExpr (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003b54#64 0xef#8 0xf0#8 0x4f#8 0xa5#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (e : Expr),
      EvalErr st d env e → ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003b54#64 0xef#8 0xf0#8 0x4f#8 0xa5#8)
      (errSite_80003b54 S.g S.inp S.m0) c (hsite c)

/-- Route `hVarInit` → `errSite_80003b9c` (var init error (ExecErr.varInit)). -/
theorem route_hVarInit (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003b9c#64 0xef#8 0xf0#8 0xcf#8 0xa0#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (x : String) (e : Expr),
      EvalErr st d env e → ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003b9c#64 0xef#8 0xf0#8 0xcf#8 0xa0#8)
      (errSite_80003b9c S.g S.inp S.m0) c (hsite c)

/-- Route `hBlock` → `errSite_80003bc8` (block error (ExecErr.block)). -/
theorem route_hBlock (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003bc8#64 0xef#8 0xf0#8 0x0f#8 0x9e#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (ss : List Stmt) (store' : Store)
      (inner : Addr),
      st.store.allocFrame (some env) = (store', inner) →
      ExecSeqErr ⟨store', st.out⟩ d inner ss → ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003bc8#64 0xef#8 0xf0#8 0x0f#8 0x9e#8)
      (errSite_80003bc8 S.g S.inp S.m0) c (hsite c)

/-- Route `hIfCond` → `errSite_80003c10` (if cond error (ExecErr.ifCond)). -/
theorem route_hIfCond (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003c10#64 0xef#8 0xf0#8 0x8f#8 0x99#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (cnd : Expr) (t : Stmt)
      (e : Option Stmt),
      EvalErr st d env cnd → ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003c10#64 0xef#8 0xf0#8 0x8f#8 0x99#8)
      (errSite_80003c10 S.g S.inp S.m0) c (hsite c)

/-- Route `hIfThen` → `errSite_80003c7c` (if then error (ExecErr.ifThen)). -/
theorem route_hIfThen (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003c7c#64 0xef#8 0xf0#8 0xcf#8 0x92#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (cnd : Expr) (t : Stmt)
      (e : Option Stmt) (st' : SpecSt) (v : Value),
      EvalE st d env cnd st' v → v.truthy = true → ExecErr st' d env t →
      ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003c7c#64 0xef#8 0xf0#8 0xcf#8 0x92#8)
      (errSite_80003c7c S.g S.inp S.m0) c (hsite c)

/-- Route `hIfElse` → `errSite_80003cc4` (if else error (ExecErr.ifElse)). -/
theorem route_hIfElse (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003cc4#64 0xef#8 0xf0#8 0x4f#8 0x8e#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (cnd : Expr) (t e : Stmt)
      (st' : SpecSt) (v : Value),
      EvalE st d env cnd st' v → v.truthy = false → ExecErr st' d env e →
      ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003cc4#64 0xef#8 0xf0#8 0x4f#8 0x8e#8)
      (errSite_80003cc4 S.g S.inp S.m0) c (hsite c)

/-- Route `hWhileCond` → `errSite_80003ce8` (while cond error (ExecErr.whileCond)). -/
theorem route_hWhileCond (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003ce8#64 0xef#8 0xf0#8 0x0f#8 0x8c#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (cnd : Expr) (b : Stmt),
      EvalErr st d env cnd → ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003ce8#64 0xef#8 0xf0#8 0x0f#8 0x8c#8)
      (errSite_80003ce8 S.g S.inp S.m0) c (hsite c)

/-- Route `hWhileBody` → `errSite_80003d14` (while body error (ExecErr.whileBody)). -/
theorem route_hWhileBody (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003d14#64 0xef#8 0xf0#8 0x4f#8 0x89#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (cnd : Expr) (b : Stmt)
      (st' : SpecSt) (v : Value),
      EvalE st d env cnd st' v → v.truthy = true → ExecErr st' d env b →
      ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003d14#64 0xef#8 0xf0#8 0x4f#8 0x89#8)
      (errSite_80003d14 S.g S.inp S.m0) c (hsite c)

/-- Route `hWhileLoop` → `errSite_80003d5c` (while loop error (ExecErr.whileLoop)). -/
theorem route_hWhileLoop (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003d5c#64 0xef#8 0xf0#8 0xcf#8 0x84#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (cnd : Expr) (b : Stmt)
      (st' st'' : SpecSt) (v : Value) (status : Status),
      EvalE st d env cnd st' v → v.truthy = true → ExecS st' d env b st'' status →
      (status = .normal ∨ status = .cont) → ExecErr st'' d env (.whileStmt cnd b) →
      ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003d5c#64 0xef#8 0xf0#8 0xcf#8 0x84#8)
      (errSite_80003d5c S.g S.inp S.m0) c (hsite c)

/-- Route `hForInit` → `errSite_80003da0` (for init error (ExecErr.forInit)). -/
theorem route_hForInit (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003da0#64 0xef#8 0xf0#8 0x8f#8 0x80#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (init : Stmt) (cnd : Option Expr)
      (step : Option Expr) (b : Stmt) (store' : Store) (outer : Addr),
      st.store.allocFrame (some env) = (store', outer) →
      ExecErr ⟨store', st.out⟩ d outer init → ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003da0#64 0xef#8 0xf0#8 0x8f#8 0x80#8)
      (errSite_80003da0 S.g S.inp S.m0) c (hsite c)

/-- Route `hForLoop` → `errSite_80003950` (for loop error (ExecErr.forLoop)). -/
theorem route_hForLoop (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003950#64 0xef#8 0xf0#8 0x8f#8 0xc5#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (init : Option Stmt)
      (cnd : Option Expr) (step : Option Expr) (b : Stmt) (store' : Store)
      (outer : Addr) (st' : SpecSt),
      st.store.allocFrame (some env) = (store', outer) →
      ExecInit ⟨store', st.out⟩ d outer init st' →
      ForLoopErr st' d outer cnd step b → ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003950#64 0xef#8 0xf0#8 0x8f#8 0xc5#8)
      (errSite_80003950 S.g S.inp S.m0) c (hsite c)

/-- Route `hRet` → `errSite_800034e4` (return expr error (ExecErr.ret)). -/
theorem route_hRet (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x800034e4#64 0xef#8 0xf0#8 0x5f#8 0x8c#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (e : Expr),
      EvalErr st d env e → ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x800034e4#64 0xef#8 0xf0#8 0x5f#8 0x8c#8)
      (errSite_800034e4 S.g S.inp S.m0) c (hsite c)

/-- Route `hFlCond` → `errSite_80003de8` (forloop cond error (ForLoopErr.cond)). -/
theorem route_hFlCond (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003de8#64 0xef#8 0xe0#8 0x1f#8 0xfc#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (cnd : Expr) (step : Option Expr)
      (b : Stmt),
      EvalErr st d env cnd → ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003de8#64 0xef#8 0xe0#8 0x1f#8 0xfc#8)
      (errSite_80003de8 S.g S.inp S.m0) c (hsite c)

/-- Route `hFlBody` → `errSite_80003e98` (forloop body error (ForLoopErr.body)). -/
theorem route_hFlBody (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003e98#64 0xef#8 0xe0#8 0x1f#8 0xf1#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (cnd : Option Expr)
      (step : Option Expr) (b : Stmt) (st' : SpecSt),
      ForCond st d env cnd st' → ExecErr st' d env b → ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003e98#64 0xef#8 0xe0#8 0x1f#8 0xf1#8)
      (errSite_80003e98 S.g S.inp S.m0) c (hsite c)

/-- Route `hFlStep` → `errSite_80003f58` (forloop step error (ForLoopErr.step)). -/
theorem route_hFlStep (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003f58#64 0xef#8 0xe0#8 0x1f#8 0xe5#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (cnd : Option Expr) (e : Expr)
      (b : Stmt) (st' st'' : SpecSt) (status : Status),
      ForCond st d env cnd st' → ExecS st' d env b st'' status →
      (status = .normal ∨ status = .cont) → EvalErr st'' d env e → ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003f58#64 0xef#8 0xe0#8 0x1f#8 0xe5#8)
      (errSite_80003f58 S.g S.inp S.m0) c (hsite c)

/-- Route `hFlLoop` → `errSite_80003fac` (forloop loop error (ForLoopErr.loop)). -/
theorem route_hFlLoop (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003fac#64 0xef#8 0xe0#8 0xdf#8 0xdf#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (cnd : Option Expr)
      (step : Option Expr) (b : Stmt) (st' st'' st''' : SpecSt) (status : Status),
      ForCond st d env cnd st' → ExecS st' d env b st'' status →
      (status = .normal ∨ status = .cont) → ExecStep st'' d env step st''' →
      ForLoopErr st''' d env cnd step b → ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003fac#64 0xef#8 0xe0#8 0xdf#8 0xdf#8)
      (errSite_80003fac S.g S.inp S.m0) c (hsite c)

/-- Route `hSeqHead` → `errSite_80003fdc` (seq head error (ExecSeqErr.head)). -/
theorem route_hSeqHead (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003fdc#64 0xef#8 0xe0#8 0xdf#8 0xdc#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (s : Stmt) (ss : List Stmt),
      ExecErr st d env s → ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80003fdc#64 0xef#8 0xe0#8 0xdf#8 0xdc#8)
      (errSite_80003fdc S.g S.inp S.m0) c (hsite c)

/-- Route `hSeqTail` → `errSite_80002e90` (seq tail error (ExecSeqErr.tail)). -/
theorem route_hSeqTail (S : ErrShared)
    (hsite : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80002e90#64 0xef#8 0xf0#8 0x9f#8 0xf1#8 c) :
    ∀ (c : Config) (st : SpecSt) (d : Nat) (env : Addr) (s : Stmt) (ss : List Stmt)
      (st' : SpecSt),
      ExecS st d env s st' .normal → ExecSeqErr st' d env ss → ErrHalts c → ErrHalts c :=
  fun c _ _ _ _ _ _ _ _ _ =>
    errRow S.g S.inp S.ra0 S.s0v S.s1v S.s2v S.s3v S.s4v S.s5v S.s6v S.s7v
      S.s8v S.s9v S.s10v S.s11v S.spv S.m0 S.SC S.out S.HT
      (SitePre := JalErrPre S.g S.inp S.m0 0x80002e90#64 0xef#8 0xf0#8 0x9f#8 0xf1#8)
      (errSite_80002e90 S.g S.inp S.m0) c (hsite c)

/-- **The routed error family (`herrFam`), modulo the shared bundle + the 42
reachability links.**  Feeds all 42 `route_<premise>` rows into
`InterpSimBundle.errFamily_of_sites` ⇒ `ErrFamily L`.  Its residuals are
exactly (1) the shared `ErrShared` bundle (L7/L8: `SC`/`HT`, M3/M6 inputs)
and (2) the 42 per-premise reachability hypotheses `hsite<name>` (the M4
caller-linkage that the machine, run to this error node, is parked at its
`jal runtime_error`).  NO other glue. -/
theorem errFamilyClosed (L : Vsa.Refine.Layout) (S : ErrShared)
    (hsite_hVarUndef : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003b54#64 0xef#8 0xf0#8 0x4f#8 0xa5#8 c)
    (hsite_hAssignE : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003b9c#64 0xef#8 0xf0#8 0xcf#8 0xa0#8 c)
    (hsite_hAssignUnbound : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003bc8#64 0xef#8 0xf0#8 0x0f#8 0x9e#8 c)
    (hsite_hBinaryL : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003c10#64 0xef#8 0xf0#8 0x8f#8 0x99#8 c)
    (hsite_hBinaryR : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003c7c#64 0xef#8 0xf0#8 0xcf#8 0x92#8 c)
    (hsite_hBinaryOp : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003cc4#64 0xef#8 0xf0#8 0x4f#8 0x8e#8 c)
    (hsite_hOrL : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003ce8#64 0xef#8 0xf0#8 0x0f#8 0x8c#8 c)
    (hsite_hOrR : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003d14#64 0xef#8 0xf0#8 0x4f#8 0x89#8 c)
    (hsite_hAndL : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003d5c#64 0xef#8 0xf0#8 0xcf#8 0x84#8 c)
    (hsite_hAndR : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003da0#64 0xef#8 0xf0#8 0x8f#8 0x80#8 c)
    (hsite_hUnaryE : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003950#64 0xef#8 0xf0#8 0x8f#8 0xc5#8 c)
    (hsite_hNegType : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x800034e4#64 0xef#8 0xf0#8 0x5f#8 0x8c#8 c)
    (hsite_hCallF : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003de8#64 0xef#8 0xe0#8 0x1f#8 0xfc#8 c)
    (hsite_hCallArgs : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003e98#64 0xef#8 0xe0#8 0x1f#8 0xf1#8 c)
    (hsite_hCallC : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003f58#64 0xef#8 0xe0#8 0x1f#8 0xe5#8 c)
    (hsite_hArgsHead : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003fac#64 0xef#8 0xe0#8 0xdf#8 0xdf#8 c)
    (hsite_hArgsTail : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003fdc#64 0xef#8 0xe0#8 0xdf#8 0xdc#8 c)
    (hsite_hNotCallable : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80002e90#64 0xef#8 0xf0#8 0x9f#8 0xf1#8 c)
    (hsite_hBadClosure : ∀ (c : Config) (st : SpecSt) (d : Nat) (a : Vsa.While.Addr)
      (vs : List Vsa.While.Value), st.store.closures[a]? = none → ErrHalts c)
    (hsite_hArity : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80002ebc#64 0xef#8 0xf0#8 0xdf#8 0xee#8 c)
    (hsite_hDepth : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80002e90#64 0xef#8 0xf0#8 0x9f#8 0xf1#8 c)
    (hsite_hBody : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80002ebc#64 0xef#8 0xf0#8 0xdf#8 0xee#8 c)
    (hsite_hEscape : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80002e90#64 0xef#8 0xf0#8 0x9f#8 0xf1#8 c)
    (hsite_hAssertFail : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80002ebc#64 0xef#8 0xf0#8 0xdf#8 0xee#8 c)
    (hsite_hAssertArity : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80002e90#64 0xef#8 0xf0#8 0x9f#8 0xf1#8 c)
    (hsite_hExpr : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003b54#64 0xef#8 0xf0#8 0x4f#8 0xa5#8 c)
    (hsite_hVarInit : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003b9c#64 0xef#8 0xf0#8 0xcf#8 0xa0#8 c)
    (hsite_hBlock : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003bc8#64 0xef#8 0xf0#8 0x0f#8 0x9e#8 c)
    (hsite_hIfCond : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003c10#64 0xef#8 0xf0#8 0x8f#8 0x99#8 c)
    (hsite_hIfThen : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003c7c#64 0xef#8 0xf0#8 0xcf#8 0x92#8 c)
    (hsite_hIfElse : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003cc4#64 0xef#8 0xf0#8 0x4f#8 0x8e#8 c)
    (hsite_hWhileCond : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003ce8#64 0xef#8 0xf0#8 0x0f#8 0x8c#8 c)
    (hsite_hWhileBody : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003d14#64 0xef#8 0xf0#8 0x4f#8 0x89#8 c)
    (hsite_hWhileLoop : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003d5c#64 0xef#8 0xf0#8 0xcf#8 0x84#8 c)
    (hsite_hForInit : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003da0#64 0xef#8 0xf0#8 0x8f#8 0x80#8 c)
    (hsite_hForLoop : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003950#64 0xef#8 0xf0#8 0x8f#8 0xc5#8 c)
    (hsite_hRet : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x800034e4#64 0xef#8 0xf0#8 0x5f#8 0x8c#8 c)
    (hsite_hFlCond : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003de8#64 0xef#8 0xe0#8 0x1f#8 0xfc#8 c)
    (hsite_hFlBody : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003e98#64 0xef#8 0xe0#8 0x1f#8 0xf1#8 c)
    (hsite_hFlStep : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003f58#64 0xef#8 0xe0#8 0x1f#8 0xe5#8 c)
    (hsite_hFlLoop : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003fac#64 0xef#8 0xe0#8 0xdf#8 0xdf#8 c)
    (hsite_hSeqHead : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003fdc#64 0xef#8 0xe0#8 0xdf#8 0xdc#8 c)
    (hsite_hSeqTail : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80002e90#64 0xef#8 0xf0#8 0x9f#8 0xf1#8 c)
    (hsite_hTopAbrupt : ∀ (p : Vsa.While.Program) (c : Config),
      Vsa.While.TopAbrupt p → ErrHalts c)
    : Vsa.Sim.InterpSimBundle.ErrFamily L :=
  Vsa.Sim.InterpSimBundle.errFamily_of_sites L
    (route_hVarUndef S hsite_hVarUndef)
    (route_hAssignE S hsite_hAssignE)
    (route_hAssignUnbound S hsite_hAssignUnbound)
    (route_hBinaryL S hsite_hBinaryL)
    (route_hBinaryR S hsite_hBinaryR)
    (route_hBinaryOp S hsite_hBinaryOp)
    (route_hOrL S hsite_hOrL)
    (route_hOrR S hsite_hOrR)
    (route_hAndL S hsite_hAndL)
    (route_hAndR S hsite_hAndR)
    (route_hUnaryE S hsite_hUnaryE)
    (route_hNegType S hsite_hNegType)
    (route_hCallF S hsite_hCallF)
    (route_hCallArgs S hsite_hCallArgs)
    (route_hCallC S hsite_hCallC)
    (route_hArgsHead S hsite_hArgsHead)
    (route_hArgsTail S hsite_hArgsTail)
    (route_hNotCallable S hsite_hNotCallable)
    hsite_hBadClosure
    (route_hArity S hsite_hArity)
    (route_hDepth S hsite_hDepth)
    (route_hBody S hsite_hBody)
    (route_hEscape S hsite_hEscape)
    (route_hAssertFail S hsite_hAssertFail)
    (route_hAssertArity S hsite_hAssertArity)
    (route_hExpr S hsite_hExpr)
    (route_hVarInit S hsite_hVarInit)
    (route_hBlock S hsite_hBlock)
    (route_hIfCond S hsite_hIfCond)
    (route_hIfThen S hsite_hIfThen)
    (route_hIfElse S hsite_hIfElse)
    (route_hWhileCond S hsite_hWhileCond)
    (route_hWhileBody S hsite_hWhileBody)
    (route_hWhileLoop S hsite_hWhileLoop)
    (route_hForInit S hsite_hForInit)
    (route_hForLoop S hsite_hForLoop)
    (route_hRet S hsite_hRet)
    (route_hFlCond S hsite_hFlCond)
    (route_hFlBody S hsite_hFlBody)
    (route_hFlStep S hsite_hFlStep)
    (route_hFlLoop S hsite_hFlLoop)
    (route_hSeqHead S hsite_hSeqHead)
    (route_hSeqTail S hsite_hSeqTail)
    hsite_hTopAbrupt

#print axioms errFamilyClosed

/-! ## Wiring check — `errFamilyClosed` fills `interpSimClosed_of_families`'
`herrFam` slot

The `herrFam` argument of `InterpSimFinal.interpSimClosed_of_families` has
type `ErrFamily L`.  `errFamilyClosed L S hsite…` produces exactly that, so
the endgame capstone can be driven from the routed error family directly —
modulo ONLY the shared `ErrShared` bundle and the 42 reachability links. -/
example (L : Vsa.Refine.Layout) (S : ErrShared)
    (hsite_hVarUndef : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003b54#64 0xef#8 0xf0#8 0x4f#8 0xa5#8 c)
    (hsite_hAssignE : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003b9c#64 0xef#8 0xf0#8 0xcf#8 0xa0#8 c)
    (hsite_hAssignUnbound : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003bc8#64 0xef#8 0xf0#8 0x0f#8 0x9e#8 c)
    (hsite_hBinaryL : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003c10#64 0xef#8 0xf0#8 0x8f#8 0x99#8 c)
    (hsite_hBinaryR : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003c7c#64 0xef#8 0xf0#8 0xcf#8 0x92#8 c)
    (hsite_hBinaryOp : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003cc4#64 0xef#8 0xf0#8 0x4f#8 0x8e#8 c)
    (hsite_hOrL : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003ce8#64 0xef#8 0xf0#8 0x0f#8 0x8c#8 c)
    (hsite_hOrR : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003d14#64 0xef#8 0xf0#8 0x4f#8 0x89#8 c)
    (hsite_hAndL : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003d5c#64 0xef#8 0xf0#8 0xcf#8 0x84#8 c)
    (hsite_hAndR : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003da0#64 0xef#8 0xf0#8 0x8f#8 0x80#8 c)
    (hsite_hUnaryE : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003950#64 0xef#8 0xf0#8 0x8f#8 0xc5#8 c)
    (hsite_hNegType : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x800034e4#64 0xef#8 0xf0#8 0x5f#8 0x8c#8 c)
    (hsite_hCallF : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003de8#64 0xef#8 0xe0#8 0x1f#8 0xfc#8 c)
    (hsite_hCallArgs : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003e98#64 0xef#8 0xe0#8 0x1f#8 0xf1#8 c)
    (hsite_hCallC : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003f58#64 0xef#8 0xe0#8 0x1f#8 0xe5#8 c)
    (hsite_hArgsHead : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003fac#64 0xef#8 0xe0#8 0xdf#8 0xdf#8 c)
    (hsite_hArgsTail : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003fdc#64 0xef#8 0xe0#8 0xdf#8 0xdc#8 c)
    (hsite_hNotCallable : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80002e90#64 0xef#8 0xf0#8 0x9f#8 0xf1#8 c)
    (hsite_hBadClosure : ∀ (c : Config) (st : SpecSt) (d : Nat) (a : Vsa.While.Addr)
      (vs : List Vsa.While.Value), st.store.closures[a]? = none → ErrHalts c)
    (hsite_hArity : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80002ebc#64 0xef#8 0xf0#8 0xdf#8 0xee#8 c)
    (hsite_hDepth : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80002e90#64 0xef#8 0xf0#8 0x9f#8 0xf1#8 c)
    (hsite_hBody : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80002ebc#64 0xef#8 0xf0#8 0xdf#8 0xee#8 c)
    (hsite_hEscape : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80002e90#64 0xef#8 0xf0#8 0x9f#8 0xf1#8 c)
    (hsite_hAssertFail : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80002ebc#64 0xef#8 0xf0#8 0xdf#8 0xee#8 c)
    (hsite_hAssertArity : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80002e90#64 0xef#8 0xf0#8 0x9f#8 0xf1#8 c)
    (hsite_hExpr : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003b54#64 0xef#8 0xf0#8 0x4f#8 0xa5#8 c)
    (hsite_hVarInit : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003b9c#64 0xef#8 0xf0#8 0xcf#8 0xa0#8 c)
    (hsite_hBlock : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003bc8#64 0xef#8 0xf0#8 0x0f#8 0x9e#8 c)
    (hsite_hIfCond : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003c10#64 0xef#8 0xf0#8 0x8f#8 0x99#8 c)
    (hsite_hIfThen : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003c7c#64 0xef#8 0xf0#8 0xcf#8 0x92#8 c)
    (hsite_hIfElse : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003cc4#64 0xef#8 0xf0#8 0x4f#8 0x8e#8 c)
    (hsite_hWhileCond : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003ce8#64 0xef#8 0xf0#8 0x0f#8 0x8c#8 c)
    (hsite_hWhileBody : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003d14#64 0xef#8 0xf0#8 0x4f#8 0x89#8 c)
    (hsite_hWhileLoop : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003d5c#64 0xef#8 0xf0#8 0xcf#8 0x84#8 c)
    (hsite_hForInit : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003da0#64 0xef#8 0xf0#8 0x8f#8 0x80#8 c)
    (hsite_hForLoop : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003950#64 0xef#8 0xf0#8 0x8f#8 0xc5#8 c)
    (hsite_hRet : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x800034e4#64 0xef#8 0xf0#8 0x5f#8 0x8c#8 c)
    (hsite_hFlCond : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003de8#64 0xef#8 0xe0#8 0x1f#8 0xfc#8 c)
    (hsite_hFlBody : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003e98#64 0xef#8 0xe0#8 0x1f#8 0xf1#8 c)
    (hsite_hFlStep : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003f58#64 0xef#8 0xe0#8 0x1f#8 0xe5#8 c)
    (hsite_hFlLoop : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003fac#64 0xef#8 0xe0#8 0xdf#8 0xdf#8 c)
    (hsite_hSeqHead : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80003fdc#64 0xef#8 0xe0#8 0xdf#8 0xdc#8 c)
    (hsite_hSeqTail : ∀ c : Config, JalErrPre S.g S.inp S.m0 0x80002e90#64 0xef#8 0xf0#8 0x9f#8 0xf1#8 c)
    (hsite_hTopAbrupt : ∀ (p : Vsa.While.Program) (c : Config),
      Vsa.While.TopAbrupt p → ErrHalts c)
    (hterm : ∀ (p : Program) (c : Config) (out : String),
      Vsa.Refine.Loaded L p c → Vsa.While.BigStep p out → Halts c out 0)
    (htri : Trichotomy) (hdivFam : Vsa.Sim.InterpSimBundle.DivFamily L) :
    Vsa.Refine.InterpSim L :=
  Vsa.Sim.InterpSimFinal.interpSimClosed_of_families L hterm htri hdivFam
    (errFamilyClosed L S
      hsite_hVarUndef
      hsite_hAssignE
      hsite_hAssignUnbound
      hsite_hBinaryL
      hsite_hBinaryR
      hsite_hBinaryOp
      hsite_hOrL
      hsite_hOrR
      hsite_hAndL
      hsite_hAndR
      hsite_hUnaryE
      hsite_hNegType
      hsite_hCallF
      hsite_hCallArgs
      hsite_hCallC
      hsite_hArgsHead
      hsite_hArgsTail
      hsite_hNotCallable
      hsite_hBadClosure
      hsite_hArity
      hsite_hDepth
      hsite_hBody
      hsite_hEscape
      hsite_hAssertFail
      hsite_hAssertArity
      hsite_hExpr
      hsite_hVarInit
      hsite_hBlock
      hsite_hIfCond
      hsite_hIfThen
      hsite_hIfElse
      hsite_hWhileCond
      hsite_hWhileBody
      hsite_hWhileLoop
      hsite_hForInit
      hsite_hForLoop
      hsite_hRet
      hsite_hFlCond
      hsite_hFlBody
      hsite_hFlStep
      hsite_hFlLoop
      hsite_hSeqHead
      hsite_hSeqTail
      hsite_hTopAbrupt
    )

end Vsa.Sim
