#!/usr/bin/env python3
"""Generate the interpreter's code bytes and its per-instruction step table.

The interpreter twin of `gen_alloc_steps.py` (lane H4), over `IW`
(`VsaIris/Interp/IRun.lean`): `SWP` whose read-only list is the interpreter's
code and jump tables (`interpText`, live) followed by a run's persistent data
`D` (AST nodes, strings; `VsaIris/Vsa/SymData.lean`).

Outputs (do not hand-edit):

* `VsaIris/Interp/Code.lean`: `interpCode` (every instruction of `FUNCS`),
  `interpRO` (the three `switch` jump tables in `.rodata`), `interpText`,
  `interpROImg` (the tables as a byte function), `interp_at_<pc>` (four code
  bytes, the shape `chain_facts` consumes) and `interp_code_<pc>` (a jal site's
  code footprint lies in `interpText`).
* `VsaIris/Interp/Steps/Part<k>.lean`: per instruction one `#derive_case`
  segment (two for a branch) and step lemmas over `IW`:
  - `it_<pc>`: ALU, store, branch, `j`, `ret`, `jr`, `jal`, and a load from
    OWNED bytes (value `ldv k Mt ea`);
  - `itD_<pc>`: a load from persistent DATA (value `ldv k Dt ea`, the bytes
    listed in `D`);
  - `itT_<pc>`: a jump-table load (value `ldvf k interpROImg ea`);
  - `jalx_<pc>`: the `JalExec` fact of a `jal` site.

Kinds outside the reflected block model (`seqz`, `jalr`) get no step lemma;
they are listed at the file head.

Usage: python3 scripts/gen_interp_steps.py [--check]
"""
import pathlib
import re
import struct
import sys

from rv_steps import M64, lit64, sx12, classify_word, src as _src

ROOT = pathlib.Path(__file__).resolve().parent.parent
FUNCS = ['eval_expr', 'exec_stmt', 'interp_run']
# `.rodata` jump tables: eval kinds (11), binary operators (13), statements (9).
TABLES = [(0x80019f58, 11), (0x80019f84, 13), (0x80019fb8, 9)]
TABLE_LOADS = {0x800031a4, 0x8000354c, 0x80004028}
PER_FILE = 120
HEADER = '-- Generated by scripts/gen_interp_steps.py; do not edit.'


GPV = 0x8001b510  # `gp`, a read-only constant of every run (`roR`)


def src(r):
    return _src(r, GPV)


# ---------------------------------------------------------------- inputs
W, MN = {}, {}
fn = None
for l in open(ROOT / 'experiments/disasm.txt'):
    m = re.match(r'^([0-9a-f]+) <(.*)>:$', l)
    if m:
        fn = m.group(2)
        continue
    m = re.match(r'^\s+([0-9a-f]+):\t([0-9a-f]{8})\s+\t(\S+)', l)
    if m and fn in FUNCS:
        pc = int(m.group(1), 16)
        W[pc] = int(m.group(2), 16)
        MN[pc] = m.group(3)
PCS = sorted(W)

DEC = {}
for l in open(ROOT / 'scripts/decode_index.tsv'):
    w, mod = l.split()
    DEC[int(w, 16)] = mod

ELF = (ROOT / 'c/while-riscv-htif.elf').read_bytes()


def elf_bytes(addr, n):
    phoff = struct.unpack_from('<Q', ELF, 0x20)[0]
    phentsize, phnum = struct.unpack_from('<HH', ELF, 0x36)
    for i in range(phnum):
        typ, _, off, vaddr, _, filesz, _, _ = struct.unpack_from('<IIQQQQQQ', ELF, phoff + i * phentsize)
        if typ == 1 and vaddr <= addr and addr + n <= vaddr + filesz:
            return list(ELF[off + addr - vaddr: off + addr - vaddr + n])
    raise SystemExit(f'address {addr:#x} not in a loaded segment')


def classify(pc):
    w = W[pc]
    if w & 0x7f == 0x67 and (w >> 7) & 31 == 0 and (w >> 12) & 7 == 0 and (w >> 20) == 0 \
            and (w >> 15) & 31 != 1:
        return ('jr', dict(rs1=(w >> 15) & 31))
    return classify_word(pc, w, GPV)


# ---------------------------------------------------------------- the code bytes
code = []
for pc in PCS:
    for i in range(4):
        code.append((pc + i, (W[pc] >> (8 * i)) & 0xff))
ro = []
for base, n in TABLES:
    ro += [(base + i, b) for i, b in enumerate(elf_bytes(base, 4 * n))]
BYTE = dict(code)
CH = 16
chunks = [code[i:i + CH] for i in range(0, len(code), CH)]
where = {a: j for j, c in enumerate(chunks) for (a, _) in c}


def node_name(lo, hi):
    return f'interpChunk{lo}' if hi - lo == 1 else f'interpNode{lo}_{hi}'


node_defs = []


def build(lo, hi):
    if hi - lo == 1:
        return
    mid = (lo + hi) // 2
    build(lo, mid)
    build(mid, hi)
    node_defs.append(f'def {node_name(lo, hi)} : List (Nat × BitVec 8) :=\n'
                     f'  {node_name(lo, mid)} ++ {node_name(mid, hi)}\n')


build(0, len(chunks))
ROOT_NODE = node_name(0, len(chunks))


def mem_proof(a):
    """Proof term of `(a, BYTE[a]) ∈ interpText`."""
    j = where[a]
    pf = f'(by decide : ((0x{a:x} : Nat), (0x{BYTE[a]:02x}#8 : BitVec 8)) ∈ interpChunk{j})'
    path = []
    lo, hi = 0, len(chunks)
    while hi - lo > 1:
        mid = (lo + hi) // 2
        if j < mid:
            path.append(('L', node_name(mid, hi)))
            hi = mid
        else:
            path.append(('R', node_name(lo, mid)))
            lo = mid
    for side, other in reversed(path):
        pf = (f'List.mem_append_left {other} ({pf})' if side == 'L'
              else f'List.mem_append_right {other} ({pf})')
    return f'List.mem_append_left interpRO ({pf})'


def gen_code():
    C = [HEADER, 'import VsaIris.Vsa.SymData', '',
         '/-! The interpreter\'s code bytes (`eval_expr`, `exec_stmt`, `interp_run`) and its three',
         '`switch` jump tables, as a balanced append tree of 16-byte chunks. -/', '',
         'namespace VsaIris.Sym', '', 'open Vsa.MemRepr Vsa.Sim', '']
    for j, c in enumerate(chunks):
        C.append(f'def interpChunk{j} : List (Nat × BitVec 8) :=')
        C.append('  [' + ', '.join(f'(0x{a:x}, 0x{b:02x}#8)' for a, b in c) + ']\n')
    C += node_defs
    C.append('/-- The interpreter\'s instruction bytes: `(address, byte)`. -/')
    C.append(f'def interpCode : List (Nat × BitVec 8) := {ROOT_NODE}\n')
    C.append('/-- The jump tables `eval_expr` and `exec_stmt` dispatch through (`.rodata`). -/')
    C.append('def interpRO : List (Nat × BitVec 8) :=')
    C.append('  [' + ',\n   '.join(', '.join(f'(0x{a:x}, 0x{b:02x}#8)' for a, b in ro[i:i + 8])
                                  for i in range(0, len(ro), 8)) + ']\n')
    C.append('/-- The read-only bytes every interpreter run fetches or loads. -/')
    C.append('def interpText : List (Nat × BitVec 8) := interpCode ++ interpRO\n')
    C.append('/-- The jump tables as a byte function (`0` off the tables). -/')
    C.append('def interpROImg (a : Nat) : BitVec 8 := (interpRO.lookup a).getD 0\n')
    for pc in PCS:
        bs = [BYTE[pc + i] for i in range(4)]
        C.append(f'theorem interp_at_{pc:08x} {{m : Mem}} (h : TextLoaded interpText m) :')
        C.append('    ' + ' ∧\n    '.join(f'm[(0x{pc + i:x} : Nat)]? = some (0x{bs[i]:02x} : BitVec 8)'
                                           for i in range(4)) + ' :=')
        C.append('  ⟨' + ',\n   '.join(f'h _ ({mem_proof(pc + i)})' for i in range(4)) + '⟩\n')
    for pc in PCS:
        if classify(pc)[0] != 'jal':
            continue
        bs = [BYTE[pc + i] for i in range(4)]
        cs = ', '.join(f'0x{b:02x}#8' for b in bs)
        C.append(f'theorem interp_code_{pc:08x} : ∀ p ∈ codeFoot 0x{pc:x} [{cs}], (p.1, p.2.2) ∈ interpText := by')
        C.append('  intro p hp')
        C.append('  simp only [codeFoot, List.zipIdx, List.zipIdx_cons, List.zipIdx_nil, List.map_cons, List.map_nil,')
        C.append('    List.mem_cons, List.not_mem_nil, or_false] at hp')
        C.append('  rcases hp with rfl | rfl | rfl | rfl')
        for i in range(4):
            C.append(f'  · exact {mem_proof(pc + i)}')
        C.append('')
    C.append('end VsaIris.Sym\n')
    return '\n'.join(C)


# ---------------------------------------------------------------- the step table


def ks_of(regs):
    return sorted({r for r in regs if r != 0})


def lst(xs):
    return '[' + ', '.join(str(x) for x in xs) + ']'


def hR(ks):
    alts = ' | '.join(['rfl'] * len(ks))
    return ('(by intro x hx hg; simp only [List.mem_cons, List.not_mem_nil, or_false] at hx; '
            f'rcases hx with {alts} <;> first | rfl | exact absurd rfl hg)')


def hRo(ks, rd=None):
    if rd is None:
        return '(fun _ _ _ _ => rfl)'
    return f'(fun x _ _ hx => upd_other _ _ (fun e => hx (e ▸ (by decide : {rd} ∈ {lst(ks)}))))'


def hdr(name, pc, extra=''):
    return (f"theorem {name}_{pc:08x} {{live : Nat → Prop}} {{D : List (Nat × BitVec 8)}} {{S : Nat → Prop}}\n"
            f"    {{Q : (Nat → BitVec 64) → (Nat → BitVec 8) → Prop}} {{R : Nat → BitVec 64}} {{Mt : Mem}}{extra}\n"
            f"    (hlive : ∀ p ∈ interpText, live p.1)")


CF = 'chain_facts hm with "VsaIris.Sym.interp_at_"'
def hgp(ks):
    return '(fun _ => rfl)' if 3 in ks else '(fun h => absurd h (by decide))'


def step(seg, ks, lds, LD, Wr, cover, tail, hpc, R, Ro, hk, ind='  '):
    t = f'; {tail}' if tail else ''
    ld = 'hLDS' if LD != '[]' else '(fun a h => by cases h)'
    wr = 'hS' if Wr != '[]' else '(fun a h => by cases h)'
    return (f'{ind}swp_stepD {seg} {lst(ks)} {lds} {LD} {Wr} 0 rfl (by decide) (by decide) (by decide)\n'
            f'{ind}  {cover} hlive\n'
            f'{ind}  (fun m hm hD hLD => by unfold {seg} ChainFacts; {CF}{t})\n'
            f'{ind}  (by decide) (by decide) {hgp(ks)} (by decide) {ld}\n'
            f'{ind}  {wr} {hpc}\n'
            f'{ind}  {R}\n'
            f'{ind}  {Ro} rfl {hk}')


def iw(pc_expr, R='R', Mt='Mt'):
    return f'IW live D S Q {pc_expr} {R} {Mt}'


def emit(pc):
    cls, d = classify(pc)
    w = W[pc]
    bs = [(w >> (8 * i)) & 0xff for i in range(4)]
    nxt = f'0x{pc + 4:x}#64'
    segs, thm = [], []
    if cls == 'unsupported':
        return None, None
    single = f'def ix_{pc:08x} : List BBlock := [{{ body := [mkLine 0x{pc:x}#64 0x{w:08x}#32], term := none }}]'
    tinstr = lambda kind, rs1, rs2, i13, i21: (
        f'⟨0x{pc:x}#64, 0x{w:08x}#32, 0x{bs[0]:02x}#8, 0x{bs[1]:02x}#8, 0x{bs[2]:02x}#8, '
        f'0x{bs[3]:02x}#8, {kind}, {rs1}, {rs2}, 0x{i13 & 0x1fff:x}#13, 0x{i21 & 0x1fffff:x}#21, 0#12⟩')
    tdef = lambda name, kind, rs1, rs2, i13, i21: (
        f'def {name} : List BBlock := [⟨[], some ({tinstr(kind, rs1, rs2, i13, i21)} : TInstr)⟩]')
    NIL = '(fun a _ => trivial)'
    if cls == 'alu':
        segs.append(single)
        ks = ks_of(d['srcs'] + [d['rd']])
        thm.append(hdr('it', pc) + f"""
    (hk : {iw(nxt, f"(upd R {d['rd']} ({d['val']}))")}) :
    {iw(f'0x{pc:x}#64')} :=
""" + step(f'ix_{pc:08x}', ks, '[]', '[]', '[]', NIL, '', 'rfl', hR(ks), hRo(ks, d['rd']), 'hk'))
    elif cls == 'load':
        segs.append(single)
        ea = f"({src(d['rs1'])} + {sx12(d['imm'])}).toNat"
        wd = d['width']
        ks = ks_of([d['rs1'], d['rd']])
        suf = {8: '8', 4: '4', 1: '1', 2: '2'}[wd]
        # owned bytes
        thm.append(hdr('it', pc) + f"""
    (hea : LdOK {ea} {wd})
    (hLDS : ∀ b ∈ accAddrs {ea} {wd}, S b)
    (hk : {iw(nxt, f"(upd R {d['rd']} (ldv .{d['kind']} Mt {ea}))")}) :
    {iw(f'0x{pc:x}#64')} :=
""" + step(f'ix_{pc:08x}', ks, f'[bytesAt (imgM Mt) {ea} {wd}]', f'(accAddrs {ea} {wd})', '[]', NIL,
           f'exact ⟨hea, lpins{suf}_img hLD⟩', 'rfl', hR(ks), hRo(ks, d['rd']), 'hk'))
        # persistent data
        thm.append(hdr('itD', pc, ' {Dt : Mem}') + f"""
    (hea : LdOK {ea} {wd})
    (hLDD : ∀ b ∈ accAddrs {ea} {wd}, (b, imgM Dt b) ∈ D)
    (hk : {iw(nxt, f"(upd R {d['rd']} (ldv .{d['kind']} Dt {ea}))")}) :
    {iw(f'0x{pc:x}#64')} :=
""" + step(f'ix_{pc:08x}', ks, f'[bytesAt (imgM Dt) {ea} {wd}]', '[]', '[]', NIL,
           f'exact ⟨hea, lpins{suf}_img (fun b hb => hD _ (hLDD b hb))⟩', 'rfl', hR(ks),
           hRo(ks, d['rd']), 'hk'))
        if pc in TABLE_LOADS:
            thm.append(hdr('itT', pc) + f"""
    (hea : LdOK {ea} {wd})
    (hLDT : ∀ b ∈ accAddrs {ea} {wd}, (b, interpROImg b) ∈ interpRO)
    (hk : {iw(nxt, f"(upd R {d['rd']} (ldvf .{d['kind']} interpROImg {ea}))")}) :
    {iw(f'0x{pc:x}#64')} :=
""" + step(f'ix_{pc:08x}', ks, f'[bytesAt interpROImg {ea} {wd}]', '[]', '[]', NIL,
           f'exact ⟨hea, lpins{suf}_fn (fun b hb => by rw [hm _ (List.mem_append_right _ (hLDT b hb))]; rfl)⟩',
           'rfl', hR(ks), hRo(ks, d['rd']), 'hk'))
    elif cls == 'store':
        segs.append(single)
        ea = f"({src(d['rs1'])} + {sx12(d['imm'])}).toNat"
        wd = d['width']
        ks = ks_of([d['rs1'], d['rs2']])
        ok = f'StOKb {ea}' if d['kind'] == 'sb' else f'StOK {ea} {wd}'
        thm.append(hdr('it', pc) + f"""
    (hea : {ok})
    (hS : ∀ b ∈ accAddrs {ea} {wd}, S b)
    (hk : {iw(nxt, 'R', f"(writeLog Mt [({ea}, {wd}, {src(d['rs2'])})])")}) :
    {iw(f'0x{pc:x}#64')} :=
""" + step(f'ix_{pc:08x}', ks, '[]', '[]', f'(accAddrs {ea} {wd})', '(fun a ha => outL_single _ ha)',
           'exact hea', 'rfl', hR(ks), hRo(ks), 'hk'))
    elif cls == 'br':
        A, B = src(d['rs1']), src(d['rs2'])
        cond = {'BEQ': f'{A} = {B}', 'BNE': f'{A} ≠ {B}', 'BLT': f'{A}.toInt < {B}.toInt',
                'BGE': f'{B}.toInt ≤ {A}.toInt', 'BLTU': f'{A}.toNat < {B}.toNat',
                'BGEU': f'{B}.toNat ≤ {A}.toNat'}[d['op']]
        gl = {'BEQ': 'guard_beq', 'BNE': 'guard_bne', 'BLT': 'guard_blt', 'BGE': 'guard_bge',
              'BLTU': 'guard_bltu', 'BGEU': 'guard_bgeu'}[d['op']]
        ks = ks_of([d['rs1'], d['rs2']])
        segs.append(tdef(f'ixT_{pc:08x}', f'.br bop.{d["op"]} true', d['rs1'], d['rs2'], d['imm'], 0))
        segs.append(tdef(f'ixF_{pc:08x}', f'.br bop.{d["op"]} false', d['rs1'], d['rs2'], d['imm'], 0))
        tgt = f'0x{d["tgt"]:x}#64'
        thm.append(hdr('it', pc) + f"""
    (hT : {cond} → {iw(tgt)}) (hF : ¬ ({cond}) → {iw(nxt)}) :
    {iw(f'0x{pc:x}#64')} := by
  by_cases hc : {cond}
  · exact
""" + step(f'ixT_{pc:08x}', ks, '[]', '[]', '[]', NIL, f'exact ({gl} _ _).2 hc', 'rfl',
           hR(ks), hRo(ks), '(hT hc)', '    ') + """
  · exact
""" + step(f'ixF_{pc:08x}', ks, '[]', '[]', '[]', NIL, f'exact (guard_false ({gl} _ _)).2 hc',
           'rfl', hR(ks), hRo(ks), '(hF hc)', '    '))
    elif cls == 'j':
        segs.append(tdef(f'ix_{pc:08x}', '.j', 0, 0, 0, d['imm']))
        thm.append(hdr('it', pc) + f"""
    (hk : {iw(f"0x{d['tgt']:x}#64")}) :
    {iw(f'0x{pc:x}#64')} :=
""" + step(f'ix_{pc:08x}', [], '[]', '[]', '[]', NIL, '', 'rfl',
           '(fun _ h => nomatch h)', hRo([]), 'hk'))
    elif cls in ('ret', 'jr'):
        r = 1 if cls == 'ret' else d['rs1']
        segs.append(tdef(f'ix_{pc:08x}', '.jr', r, 0, 0, 0))
        thm.append(hdr('it', pc) + f"""
    (hal : (R {r}).toNat % 4 = 0) (hk : {iw(f'(R {r})')}) :
    {iw(f'0x{pc:x}#64')} :=
""" + step(f'ix_{pc:08x}', [r], '[]', '[]', '[]', NIL,
           f'show (Sail.BitVec.update (R {r} + sign_extend (m := 64) (0x000#12)) 0 0#1).toNat % 4 = 0; '
           'rw [ret_tgt _ hal]; exact hal', '(ret_tgt _ hal)', hR([r]), hRo([r]), 'hk'))
    elif cls == 'jal':
        code_s = ', '.join(f'0x{b:02x}#8' for b in bs)
        hb = '\n'.join(f'  have hb{i} := hb (0x{pc + i:x}, .discard, 0x{bs[i]:02x}#8) (by simp [codeFoot])'
                       for i in range(4))
        imm = d['imm'] & 0x1fffff
        tgt = d['tgt']
        thm.append(f"""open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail in
/-- `jal` at `0x{pc:x}` to `0x{tgt:x}`. -/
theorem jalx_{pc:08x} (live : Nat → Prop)
    (hlive : ∀ p ∈ codeFoot 0x{pc:x} [{code_s}], live p.1) :
    JalExec (vsaModel live) 0x{pc:x} [{code_s}] 0x{tgt:x}#64 := by
  refine jalExec_of_site live _ _ _ hlive fun c hG hi hpc hb => ?_
  obtain ⟨vm, hmi⟩ := hG.minstret
{hb}
  obtain ⟨σ', i', hs, hi', hG', hmem, hobs⟩ :=
    stepObs_jal c.σ c.tick c.steps (0x{pc:x}#64) vm (0x{w:08x}#32) (0x{imm:06x}#21)
      (regidx.Regidx 0x01#5) Register.x1 (BitVec.addInt (0x{pc:x}#64) 4)
      {' '.join(f'(0x{b:02x}#8)' for b in bs)}
      hG hpc hmi hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide)
      (by apply BitVec.eq_of_toNat_eq; decide) (by apply BitVec.eq_of_toNat_eq; decide)
      (Vsa.Sim.DecodeTable.decode_{w:08x} (afterPrelude c.σ)
        (by rw [get?_afterPrelude c.σ _ (by decide)]; exact hG.misa)
        (by rw [get?_afterPrelude c.σ _ (by decide)]; exact hG.cur_privilege)
        (by rw [get?_afterPrelude c.σ _ (by decide)]; exact hG.mseccfg))
      (by decide)
      (by decide) (by decide) (by decide) (by decide) (by decide)
      (wX_bits_x1 _ (BitVec.addInt (0x{pc:x}#64) 4)) hi
  have h := jalStep_of_obs (calleeEntry := 0x{tgt:x}#64) hs hi' hG' hmem hobs
    (by apply BitVec.eq_of_toNat_eq; decide)
  refine ⟨?_, stepConFrame_of_jalObs hs hobs⟩
  rwa [show BitVec.addInt (0x{pc:x}#64 : BitVec 64) 4 = BitVec.ofNat 64 (0x{pc:x} + 4) from by
    apply BitVec.eq_of_toNat_eq; decide] at h
""")
    return segs, thm


def gen_steps():
    unsupported, parts = [], []
    cur = ([], [], set(), [])
    for pc in PCS:
        segs, thms = emit(pc)
        if segs is None:
            unsupported.append(pc)
            continue
        cur[0].extend(segs)
        cur[1].extend(thms)
        cur[2].add(DEC[W[pc]])
        cur[3].append(pc)
        if len(cur[3]) >= PER_FILE:
            parts.append(cur)
            cur = ([], [], set(), [])
    if cur[3]:
        parts.append(cur)
    files = {}
    uns = ', '.join(f'`0x{pc:x}` {MN[pc]}' for pc in unsupported)
    for k, (segs, thms, mods, pcs) in enumerate(parts):
        L = [HEADER, 'import VsaIris.Interp.IRun', 'import Vsa.Sim.EnvNewSites'] + \
            [f'import {m}' for m in sorted(mods)] + ['',
             f'/-! The interpreter\'s step table, `0x{pcs[0]:x}` to `0x{pcs[-1]:x}` (see',
             '`scripts/gen_interp_steps.py`). -/', '',
             'open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail', '',
             'namespace Vsa.Sim', ''] + segs + ['', 'end Vsa.Sim', '',
             'namespace VsaIris.Sym', '', 'open Vsa.Sim Vsa.MemRepr VsaIris.Inst VsaIris.MallocFast', ''] + \
            [t + '\n' for t in thms] + ['end VsaIris.Sym', '']
        files[f'VsaIris/Interp/Steps/Part{k:02d}.lean'] = '\n'.join(L)
    files['VsaIris/Interp/Steps.lean'] = '\n'.join(
        [HEADER, f'-- No step lemma (outside the reflected block model): {uns}.'] +
        [f'import VsaIris.Interp.Steps.Part{k:02d}' for k in range(len(parts))] + [''])
    return files, unsupported


def main():
    check = '--check' in sys.argv
    files, unsupported = gen_steps()
    files['VsaIris/Interp/Code.lean'] = gen_code()
    stale = []
    for rel, text in files.items():
        p = ROOT / rel
        if check:
            if not p.exists() or p.read_text() != text:
                stale.append(rel)
        else:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(text)
    if check:
        for rel in stale:
            print(f'stale: {rel}', file=sys.stderr)
        return 1 if stale else 0
    print(f'{len(PCS)} instructions, {len(code)} code bytes, {len(ro)} table bytes, '
          f'{len(files) - 2} parts; no step lemma: ' + ', '.join(f'0x{pc:x} {MN[pc]}' for pc in unsupported))
    return 0


if __name__ == '__main__':
    sys.exit(main())
