#!/usr/bin/env python3
"""Generate `VsaIris/Vsa/ExitRun.lean` (lane N3): `exit`'s newlib interior
(`0x80004778` to `0x80004788`) as a chain of symbolic-run pieces over newlib's
step table, one chain per `stderr` state (idle at the boundary, or written).

Each piece compacts the state (`nx_forget_sp`: the bytes below `sp`;
`nx_compactR`: one update per register) and runs `N` steps (`nx_run`), so each
declaration stays inside the default elaboration budget. The facts the run
reads (`CloseFacts`, `ErrIdleFacts`/`ErrWrittenFacts`) are the byte facts of
`CloseCommon`/`ExitIdleFile`/`ErrWrittenFile` as load values.

Usage: python3 scripts/gen_exit_run.py [--check] [--steps N] [--pieces K]
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / 'VsaIris/Vsa/ExitRun.lean'
STEPS = int(sys.argv[sys.argv.index("--steps") + 1]) if "--steps" in sys.argv else 200
PIECES = int(sys.argv[sys.argv.index('--pieces') + 1]) if '--pieces' in sys.argv else 16

SIN, SOUT, SERR = 0x8001ba68, 0x8001bb20, 0x8001bbd8
SCLOSE, BUF = 0x8000f0c0, 0x8001bb97


def fact(name, k, a, v):
    return (name, f'  {name} : ldv .{k} Mt {a} = {v:#x}#64')


COMMON = [fact('atexit', 'ld', 0x8001b9f8, 0), fact('handler', 'ld', 0x8001b9b0, 0x80005d18),
          fact('glueNext', 'ld', 0x8001b520, 0), fact('glueCount', 'lw', 0x8001b528, 3),
          fact('glueFiles', 'ld', 0x8001b530, SIN), fact('cleanup', 'ld', 0x8001b580, 0x80005d2c)]


def idle(p, F, fl, fd):
    return [fact(p + 'flagsU', 'lhu', F + 16, fl), fact(p + 'flags', 'lh', F + 16, fl),
            fact(p + 'fd', 'lh', F + 18, fd), fact(p + 'r', 'lw', F + 8, 0), fact(p + 'ur', 'lw', F + 112, 0),
            fact(p + 'cookie', 'ld', F + 48, F), fact(p + 'close', 'ld', F + 80, SCLOSE),
            fact(p + 'ub', 'ld', F + 88, 0), fact(p + 'lb', 'ld', F + 120, 0),
            fact(p + 'lock', 'ld', F + 160, 0), fact(p + 'mode', 'lw', F + 176, 0)]


def written(p, F, fl, fd, base):
    return [fact(p + 'flagsU', 'lhu', F + 16, fl), fact(p + 'flags', 'lh', F + 16, fl),
            fact(p + 'fd', 'lh', F + 18, fd), fact(p + 'base', 'ld', F + 24, base),
            fact(p + 'cursor', 'ld', F, base), fact(p + 'cookie', 'ld', F + 48, F),
            fact(p + 'close', 'ld', F + 80, SCLOSE), fact(p + 'ub', 'ld', F + 88, 0),
            fact(p + 'lb', 'ld', F + 120, 0), fact(p + 'lock', 'ld', F + 160, 0),
            fact(p + 'mode', 'lw', F + 176, 0)]


COMMON += idle('in_', SIN, 4, 0) + written('out_', SOUT, 0x200a, 1, BUF)
ERR = {'Idle': idle('err_', SERR, 0x12, 2), 'Written': written('err_', SERR, 0x201a, 2, SERR + 119)}


def struct(name, facts, doc):
    return (f'/-- {doc} -/\nstructure {name} (Mt : Mem) : Prop where\n' +
            '\n'.join(f for _, f in facts) + '\n')


def using(err):
    names = ['hF.sp', 'hF.s0'] + [f'hC.{n}' for n, _ in COMMON] + [f'hE.{n}' for n, _ in ERR[err]]
    return ', '.join(names)


HEAD = '''-- Generated by scripts/gen_exit_run.py; do not edit.
import VsaIris.Vsa.NTac
import VsaIris.Vsa.StdioErr

/-!
# `exit`'s newlib interior as a symbolic run (lane N3)

From `jal __call_exitprocs` (`0x80004778`) to `mv a0,s0` (`0x80004788`):
`__call_exitprocs` with an empty `__atexit`, the installed
`stdio_exit_handler`, and `_fwalk_sglue` closing `stdin`, `stdout` and
`stderr` (`_fclose_r`, `__sflush_r` with nothing pending, `__sclose`,
`_close_r`). The run prints nothing. The owned bytes are `exitS s`: the 256
bytes below `sp`, newlib's data, `errno`. Two chains, one per `stderr` state
(`ErrIdleFacts`: the boundary; `ErrWrittenFacts`: after a write).
-/

namespace VsaIris.Sym

open Vsa.Sim Vsa.MemRepr VsaIris.Inst VsaIris.MallocFast

/-- The bytes `exit`'s interior owns: 256 bytes of stack below `s`, newlib's
data, `errno`. -/
def exitS (s : Nat) (a : Nat) : Prop := (s - 256 ≤ a ∧ a < s) ∨ Stdio.stdioFoot a ∨ Stdio.errnoFoot a

/-- Byte-set side conditions over `exitS`. -/
macro_rules
  | `(tactic| sx_side) =>
    `(tactic| (intro b hb; simp only [mem_accAddrs_iff] at hb;
               simp only [exitS, Stdio.stdioFoot, Stdio.InRange, Stdio.errnoFoot, Stdio.errnoAddr]; sx_addr))

/-- The registers at the entry. -/
structure ExitRegs (R : Nat → BitVec 64) (s e : BitVec 64) : Prop where
  sp : R 2 = s
  s0 : R 8 = e

/-- The end: `mv a0,s0` with `sp` and `s0`–`s11` as at the entry. -/
def ExitEnd (R0 : Nat → BitVec 64) (rv : Nat → BitVec 64) (_ : Nat → BitVec 8) : Prop :=
  rv 32 = 0x80004788#64 ∧ ∀ x ∈ [2, 8, 9, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27], rv x = R0 x

'''


def gen():
    L = [HEAD]
    L.append(struct('CloseFacts', COMMON,
                    '`CloseCommon` as the load values the close path reads.'))
    L.append(struct('ErrIdleFacts', ERR['Idle'], '`stderr` idle (`ExitIdleFile … 0x12 2`) as load values.'))
    L.append(struct('ErrWrittenFacts', ERR['Written'], '`stderr` after a write (`ErrWrittenFile`) as load values.'))
    for err in ['Idle', 'Written']:
        u = using(err)
        step = (f'(nx_forget_sp (s.toNat - 256); nx_compactR; nx_run [{STEPS}] hlive using [{u}] at 0x80004788)')
        L.append(f'''set_option hygiene false in
/-- One piece of the `{err}` run. -/
macro "exit_step{err}" : tactic => `(tactic| {step})
''')
        P = f'exit{err}'
        L.append(f'''#ix_piece {P}_01 {{live : Nat → Prop}} {{Q : (Nat → BitVec 64) → (Nat → BitVec 8) → Prop}}
    (R : Nat → BitVec 64) (Mt : Mem) (s e : BitVec 64)
    (hlive : ∀ p ∈ newlibText, live p.1)
    (hs : 0x8001ad00 + 16 + 256 ≤ s.toNat) (hs2 : s.toNat ≤ 0x88000000) (hal : s.toNat % 16 = 0)
    (hplace : s.toNat ≤ 0x8001b520 ∨ 0x8001c168 + 256 ≤ s.toNat)
    (hF : ExitRegs R s e) (hC : CloseFacts Mt) (hE : Err{err}Facts Mt) :
    NW live ∅ [] (exitS s.toNat) Q 0x80004778#64 R Mt by
  nx_run [{STEPS}] hlive using [{u}] at 0x80004788
''')
        for k in range(2, PIECES + 1):
            L.append(f'#ix_piece {P}_{k:02d} from {P}_{k - 1:02d} by\n  exit_step{err}\n')
    L.append('end VsaIris.Sym\n')
    return '\n'.join(L)


def main():
    text = gen()
    if '--check' in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print(f'stale: {OUT.relative_to(ROOT)}', file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text)
    return 0


if __name__ == '__main__':
    sys.exit(main())
