#!/usr/bin/env python3
"""Generate VsaIris/Vsa/MallocFastLines.lean: for every instruction of the fast
paths, `line_<pc> : mkLine pc word = <decoded MInstr>` (by rfl), so segment
leftovers normalize with `simp only [line_*]` instead of unfolding the
decoder. Input: the decoded fields, one line per pc
`<pc-hex> Vsa.Sim.MKind.<kind> <rd> <rs1> <rs2> <imm>`, produced by
`#eval mkLine …` (see the command in the file header).

Usage: python3 scripts/gen_malloc_path_lines.py scripts/malloc_fast_lines.tsv
"""
import re, sys, pathlib
W = {}
for l in open('experiments/disasm.txt'):
    m = re.match(r'^\s+([0-9a-f]+):\t([0-9a-f]{8})\s+\t', l)
    if m: W[int(m.group(1), 16)] = int(m.group(2), 16)
L = ['import Vsa.Sim.BlockDecode\n',
     '/-! Decoded `mkLine` normal forms for the malloc fast paths (generated by',
     '`scripts/gen_malloc_path_lines.py`; do not hand-edit). -/\n',
     'namespace VsaIris.MallocFast\n', 'open Vsa.Sim\n']
for line in open(sys.argv[1]):
    parts = line.split()
    if len(parts) != 6: continue
    pc = int(parts[0], 16); kind = parts[1].split('.')[-1]
    rd, rs1, rs2, imm = map(int, parts[2:])
    w = W[pc]; b = [(w >> (8 * i)) & 0xff for i in range(4)]
    L.append(f'theorem line_{pc:08x} : mkLine 0x{pc:x}#64 0x{w:08x}#32 =')
    L.append(f'    {{ pc := 0x{pc:x}#64, word := 0x{w:08x}#32, b0 := 0x{b[0]:02x}#8, b1 := 0x{b[1]:02x}#8,')
    L.append(f'      b2 := 0x{b[2]:02x}#8, b3 := 0x{b[3]:02x}#8, kind := .{kind}, rd := {rd}, rs1 := {rs1},')
    L.append(f'      rs2 := {rs2}, imm := 0x{imm:03x}#12 }} := rfl\n')
names = [f'VsaIris.MallocFast.line_{int(l.split()[0], 16):08x}' for l in open(sys.argv[1]) if len(l.split()) == 6]
L.append('/-- Normalize a segment leftover: decoded lines, register-pin lookups, the')
L.append('reflected state threading. -/')
L.append('macro "seg_norm" : tactic => `(tactic| simp only [' + ', '.join(names) +
         ', guardB, srcVal, runGM, stepGM, lookupG, eraseG, wvalM, List.headD, stepLdsM, ldsRunM, stepMemM, Nat.reduceAdd, Nat.reduceEqDiff, reduceIte, ite_true, ite_false, Option.getD_some])\n')
L.append('end VsaIris.MallocFast\n')
pathlib.Path('VsaIris/Vsa/MallocFastLines.lean').write_text('\n'.join(L))
