#!/usr/bin/env python3
"""gen_bin_dispatch_row.py — emit Vsa/Sim/rows/BinDispatchRow.lean.

The `hBinary` recursor premise (`term_sim`/`execSeq_sim_of_cases`) is closed by
ONE dispatcher shell `eval_binary_row` that inverts `binOpSem st''.store op lv rv
= some v` per op × operand-kind and routes each SUCCEEDING cell through a per-op
row lemma `binRow_<op>` (each = `blockA_binaryArm ≫ eval<Op>Sim(D)`, from the
`EvalEntry (.binary op el er)` recursor entry to `EvalExitD`).

The 9 int-op rows (add/sub/mul/div/mod + lt/le/gt/ge) are SYNTACTICALLY UNIFORM
modulo the 5-tuple `(op token, value form, <Op>Resid struct, sim name, guards)` —
so this generator emits them from `INT_ROWS`.  The eq/ne rows (arbitrary operand
kinds, `evalEqSimD`/`evalNeSimD` — a DIFFERENT precondition: a separate
`hResid`/`hVlSurv` rather than the inline `AddResid`/g-bridge) + the dispatcher
shell are emitted from their own templates.

NO sorry/axiom/native_decide/bv_decide; no Mathlib.
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "Vsa/Sim/rows/BinDispatchRow.lean")

# ---- the 9 uniform int-op rows ---------------------------------------------
# key: op ctor / value form / <Op>Resid struct / sim name / guard binders / guard
#      args passed to the sim (before hIHl).
INT_ROWS = [
    dict(op="add", val=".int (wrap64 (a + b))", resid="AddResid", sim="evalAddSim",
         guards=[], guard_args="", str_cell=False),
    dict(op="sub", val=".int (wrap64 (a - b))", resid="SubResid", sim="evalSubSim",
         guards=[], guard_args="", str_cell=False),
    dict(op="mul", val=".int (wrap64 (a * b))", resid="MulResid", sim="evalMulSim",
         guards=[], guard_args="", str_cell=False),
    dict(op="div", val=".int (wrap64 (a.tdiv b))", resid="DivResid", sim="evalDivSim",
         guards=[("hbNe", "b ≠ 0"), ("hOv", "¬(a = -2^63 ∧ b = -1)")],
         guard_args="hbNe hOv ", str_cell=False),
    dict(op="mod", val=".int (wrap64 (a.tmod b))", resid="ModResid", sim="evalModSim",
         guards=[("hbNe", "b ≠ 0")], guard_args="hbNe ", str_cell=False),
    dict(op="lt", val=".bool (a < b)", resid="LtResid", sim="evalLtSim",
         guards=[], guard_args="", str_cell=False),
    dict(op="le", val=".bool (a ≤ b)", resid="LeResid", sim="evalLeSim",
         guards=[], guard_args="", str_cell=False),
    dict(op="gt", val=".bool (a > b)", resid="GtResid", sim="evalGtSim",
         guards=[], guard_args="", str_cell=False),
    dict(op="ge", val=".bool (a ≥ b)", resid="GeResid", sim="evalGeSim",
         guards=[], guard_args="", str_cell=False),
]

HEADER = '''import Vsa.Sim.rows.BinArmBridge
import Vsa.Sim.rows.EvalAddRow
import Vsa.Sim.rows.EvalSubRow
import Vsa.Sim.rows.EvalLtRow
import Vsa.Sim.rows.EvalLeRow
import Vsa.Sim.rows.EvalGtRow
import Vsa.Sim.rows.EvalGeRow
import Vsa.Sim.rows.EvalMulRow
import Vsa.Sim.rows.EvalDivRow
import Vsa.Sim.rows.EvalModRow
import Vsa.Sim.rows.EvalEqNeFront
import Vsa.Sim.TermCaseBundle

/-!
# `BinDispatchRow` — the `hBinary` dispatcher (GENERATED)

Per-op binary row lemmas `binRow_<op>` (`blockA_binaryArm ≫ eval<Op>Sim(D)`, from
the `EvalEntry (.binary op el er)` recursor entry to `EvalExitD`) + the dispatcher
shell `eval_binary_row` that inverts `binOpSem` per op × operand-kind and routes
each of the 10 landed cells; the 5 str cells are named `EvalIH` residual slots.

GENERATED by `scripts/gen_bin_dispatch_row.py`.  DO NOT hand-edit.
NO `sorry`/`axiom`/`native_decide`/`bv_decide`.
-/

open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail ConcurrencyInterfaceV1 Vsa
open Register
open Sail.ConcurrencyInterfaceV1.PreSail
open Vsa.Machine (MState Config Step Steps)
open Vsa.Logic
open Vsa.RuntimeRepr
open Vsa.MemRepr
open Vsa.While
open Vsa.Alloc
open Vsa.Sim.Code
open Vsa.Sim.TermSimAssembly

set_option maxHeartbeats 8000000
set_option maxRecDepth 1000000

namespace Vsa.Sim
'''

# hVlSurv block (int-value survival; VACUOUS but proved inline).
VLSURV = '''  have hVlSurv : ∀ (φ : Addr → Nat) (mm mm' : Mem),
      ValueRepr mm N φ (sp.toNat - 968) (.int a) →
      (∀ k : Nat, ¬ (SL.lo ≤ k ∧ k < sp.toNat - 1080) → ¬ (A.lo ≤ k ∧ k < A.hi) →
        ¬ ((sp.toNat - 944) ≤ k ∧ k < (sp.toNat - 944) + 24) → mm[k]? = mm'[k]?) →
      ValueRepr mm' N φ (sp.toNat - 968) (.int a) := by
    intro φ mm mm' hv hag
    have hsproom := hBE.sproom
    obtain ⟨hk, hp⟩ := hv
    have hAg : AgreeP (fun k => sp.toNat - 968 ≤ k ∧ k < sp.toNat - 952) mm mm' := by
      intro k hk'
      exact hag k (by omega) (by rcases hBE.arenaStk with h | h <;> omega) (by omega)
    refine ⟨?_, ?_⟩
    · rw [← read32_agreeP hAg (fun j hj => ⟨by omega, by omega⟩)]; exact hk
    · rw [readI64] at hp ⊢
      rw [← read64_agreeP hAg (fun j hj => ⟨by omega, by omega⟩)]; exact hp'''


def emit_int_row(A, r):
    op, val, resid, sim = r["op"], r["val"], r["resid"], r["sim"]
    guard_binders = "".join(f"    ({b} : {t})\n" for b, t in r["guards"])
    A(f"/-- **`binRow_{op}`** — the `.{op}` int cell "
      f"(`{val}`, `{resid}`" + (", + guards" if r["guards"] else "") + "). -/")
    A(f"theorem binRow_{op}")
    A("    (g : (R : Register) → Option (RegisterType R))")
    A("    (N : NativeAddrs) (A : Arena) (SL : StackLayout) (φf φc : Addr → Nat)")
    A("    (st st' st'' : Vsa.While.St) (d : Nat) (env : Addr) (el er : Expr) (a b : Int)")
    A("    (sp r sret aEnv aExpr aLOp aROp Wl : BitVec 64)")
    A("    (m0 : Mem)")
    if guard_binders:
        A(guard_binders.rstrip("\n"))
    A(f"    (hX : BinArmExtras g N A SL .{op} el er sp r sret aExpr aLOp aROp m0)")
    A("    (hIHl : EvalIH st d env el st' (.int a))")
    A("    (hIHr : EvalIH st' d env er st'' (.int b))")
    A(f"    (hEvalE : EvalE st d env (.binary .{op} el er) st'' ({val}))")
    A("    (hSizeF : st'.store.frames.size = st''.store.frames.size)")
    A("    (hSizeC : st'.store.closures.size = st''.store.closures.size)")
    A("    -- ITEM ZERO B1: the post-LEFT store-bodies invariant (threaded to")
    A("    -- `blockA_binaryArm_budgeted` / the sim core's RIGHT budget).")
    A("    (hstoreBodiesR : Vsa.While.StoreBodiesBound st'.store Vsa.While.perCallBudget)")
    A("    (hPost : ∀ (gpre : (R : Register) → Option (RegisterType R))")
    A("        (v8 v9 v18 v19 : BitVec 64),")
    A("      (∀ c' : Vsa.Machine.Config,")
    A("        TwoSubReturn gpre N A SL φf φc st.store.frames.size st.store.closures.size")
    A("          st' st'' (.int a) (.int b) sp r sret v8 v9 v18 m0 c' →")
    A(f"        {resid} gpre N A SL sp r sret aExpr Wl c') ∧")
    A("      g Register.x8 = some v8 ∧ g Register.x9 = some v9 ∧")
    A("      g Register.x18 = some v18 ∧ g Register.x2 = some sp ∧ g Register.x19 = some v19 ∧")
    A("      (∀ R : Register, AbiPreservedNoise R →")
    A("        (Register.x8 == R) = false → (Register.x9 == R) = false →")
    A("        (Register.x18 == R) = false → (Register.x2 == R) = false →")
    A("        gpre R = g R)) :")
    A("    Triple")
    A(f"      (fun c => EvalEntry g N A SL φf φc st d env (.binary .{op} el er) sp r sret aEnv aExpr m0 c)")
    A("      (EvalExitD g N A SL φf φc st.store.frames.size st.store.closures.size")
    A(f"        st'' ({val}) sp r sret m0) := by")
    A("  intro c hc")
    A("  obtain ⟨c1, hs1, gpre', aEnvReg', v8', v9', v18', v19', ment, hArm, hBE, hx11, hx13, hx19,")
    A("    hgframe, hg8w, hg18w, hgx8, hgx18, hgx19, hpayL, hexprL, hpayR, hexprR, hMemExt, hGmt,")
    A("    hsbL, hebL, hstbL, hsbR, hebR, hstbR⟩ :=")
    A(f"    blockA_binaryArm_budgeted g N A SL φf φc st st' d env .{op} el er sp r sret aEnv aExpr aLOp aROp m0 hX hstoreBodiesR c hc")
    A(VLSURV)
    A("  obtain ⟨hResid, hgv8, hgv9, hgv18, hgv2, hgvx19, hbridge⟩ := hPost gpre' v8' v9' v18' v19'")
    A("  obtain ⟨c2, hs2, hExit⟩ :=")
    A(f"    {sim} g gpre' g N A SL φf φc st st' st'' d env el er a b")
    A("      sp r sret aExpr aEnv aLOp aROp aEnvReg' v8' v9' v18' v19' Wl c1.σ.sailOutput m0")
    A(f"      {r['guard_args']}hIHl hIHr hEvalE hSizeF hSizeC")
    A("      c1 ⟨ment, hArm, hBE, hx11, hx13, hx19, hgframe, hg8w, hg18w, hgx8, hgx18, hgx19,")
    A("        hpayL, hexprL, hpayR, hexprR, hMemExt, hGmt,")
    A("        hsbL, hebL, hstbL, hsbR, hebR, hstbR, hResid,")
    A("        hgv8, hgv9, hgv18, hgv2, hgvx19, hbridge⟩")
    A("  exact ⟨c2, hs1.trans hs2, hExit⟩")
    A("")


def emit_eq_row(A, op, val, link, jalPC, jImm, simD):
    A(f"/-- **`binRow_{op}`** — the `.{op}` cell (arbitrary operand kinds, `{simD}`). -/")
    A(f"theorem binRow_{op}")
    A("    (g : (R : Register) → Option (RegisterType R))")
    A("    (N : NativeAddrs) (A : Arena) (SL : StackLayout) (φf φc : Addr → Nat)")
    A("    (st st' st'' : Vsa.While.St) (d : Nat) (env : Addr) (el er : Expr) (vl vr : Value)")
    A("    (sp r sret aEnv aExpr aLOp aROp w19 : BitVec 64)")
    A("    (m0 : Mem)")
    A(f"    (hX : BinArmExtras g N A SL .{op} el er sp r sret aExpr aLOp aROp m0)")
    A("    (hIHl : EvalIH st d env el st' vl)")
    A("    (hIHr : EvalIH st' d env er st'' vr)")
    A(f"    (hEvalE : EvalE st d env (.binary .{op} el er) st'' ({val}))")
    A("    (hSizeF : st'.store.frames.size = st''.store.frames.size)")
    A("    (hSizeC : st'.store.closures.size = st''.store.closures.size)")
    A("    -- ITEM ZERO B1: the post-LEFT store-bodies invariant (threaded to")
    A("    -- `blockA_binaryArm_budgeted` / the sim core's RIGHT budget).")
    A("    (hstoreBodiesR : Vsa.While.StoreBodiesBound st'.store Vsa.While.perCallBudget)")
    A("    (hVlSurv : ∀ (φ : Addr → Nat) (mm mm' : Mem),")
    A("      ValueRepr mm N φ (sp.toNat - 968) vl →")
    A("      (∀ k : Nat, ¬ (SL.lo ≤ k ∧ k < sp.toNat - 1080) → ¬ (A.lo ≤ k ∧ k < A.hi) →")
    A("        ¬ ((sp.toNat - 944) ≤ k ∧ k < (sp.toNat - 944) + 24) → mm[k]? = mm'[k]?) →")
    A("      ValueRepr mm' N φ (sp.toNat - 968) vl)")
    A("    (hResid : ∀ (gpre : (R : Register) → Option (RegisterType R))")
    A("        (v8 v9 v18 v19 : BitVec 64),")
    A("      ∀ c2 : Vsa.Machine.Config,")
    A("      TwoSubReturn gpre N A SL φf φc st.store.frames.size st.store.closures.size")
    A("        st' st'' vl vr sp r sret v8 v9 v18 m0 c2 →")
    A(f"      EqResid .{op} gpre g N A SL φf φc st' st'' sp r sret aExpr v8 v9 v18 v19 w19 vl vr")
    A(f"        ({link}) ({jalPC}) ({jImm}) c2.σ.sailOutput m0 c2) :")
    A("    Triple")
    A(f"      (fun c => EvalEntry g N A SL φf φc st d env (.binary .{op} el er) sp r sret aEnv aExpr m0 c)")
    A("      (EvalExitD g N A SL φf φc st.store.frames.size st.store.closures.size")
    A(f"        st'' ({val}) sp r sret m0) := by")
    A("  intro c hc")
    A("  obtain ⟨c1, hs1, gpre', aEnvReg', v8', v9', v18', v19', ment, hArm, hBE, hx11, hx13, hx19,")
    A("    hgframe, hg8w, hg18w, hgx8, hgx18, hgx19, hpayL, hexprL, hpayR, hexprR, hMemExt, hGmt,")
    A("    hsbL, hebL, hstbL, hsbR, hebR, hstbR⟩ :=")
    A(f"    blockA_binaryArm_budgeted g N A SL φf φc st st' d env .{op} el er sp r sret aEnv aExpr aLOp aROp m0 hX hstoreBodiesR c hc")
    A("  obtain ⟨c2, hs2, hExit⟩ :=")
    A(f"    {simD} g gpre' g N A SL φf φc st st' st'' d env el er vl vr")
    A("      sp r sret aExpr aEnv aLOp aROp aEnvReg' v8' v9' v18' v19' w19 c1.σ.sailOutput m0")
    A("      hIHl hIHr hEvalE hSizeF hSizeC hVlSurv (hResid gpre' v8' v9' v18' v19')")
    A("      c1 ⟨ment, hArm, hBE, hx11, hx13, hx19, hgframe, hg8w, hg18w, hgx8, hgx18, hgx19,")
    A("        hpayL, hexprL, hpayR, hexprR, hMemExt, hGmt,")
    A("        hsbL, hebL, hstbL, hsbR, hebR, hstbR⟩")
    A("  exact ⟨c2, hs1.trans hs2, hExit⟩")
    A("")


def emit():
    L = []
    A = L.append
    A(HEADER)
    for r in INT_ROWS:
        emit_int_row(A, r)
    emit_eq_row(A, "eq", ".bool (vl.equal vr)",
                "0x80003720#64", "0x8000371c#64", "0x1ff140#21", "evalEqSimD")
    emit_eq_row(A, "ne", ".bool (!(vl.equal vr))",
                "0x80003770#64", "0x8000376c#64", "0x1ff0f0#21", "evalNeSimD")
    A(SHELL)
    A("end Vsa.Sim")
    A("")
    open(OUT, "w").write("\n".join(L))
    print(f"wrote {OUT} ({len(INT_ROWS)} int rows + eq/ne + shell)")


# The dispatcher shell + the two cell-residual defs (hand-templated: the
# op × operand-kind case tree is not itself table-uniform).
SHELL = r'''/-! ## The dispatcher shell `eval_binary_row`

Closes the `hBinary` recursor premise by inverting `binOpSem st''.store op lv rv =
some v` per `op` × operand-kind and routing each SUCCEEDING cell through the
matching `binRow_<op>`.  The 10 int cells go through their row lemmas given the
per-op residual providers `hI…`/`hEq`/`hNe` (bridge extras + post-dispatch slot +
store-size stability, ∃-committing the operand nodes + ghosts — the
`evalDivRow`-style row residual, an M6 `EvalCaseGeom` widening).  The 5 STR cells
(`.add`/`.lt`/`.le`/`.gt`/`.ge` on strings — `binOpSem` succeeds, no sim exists)
are NAMED per-cell residual slots `hStr…`, each a whole-node `EvalIH` (NOT hidden
gaps).  The div overflow subcase (`INT64_MIN / -1`) is the residual `hDivOv`. -/

/-- Per-op int-cell residual (∃-commits `aLOp aROp Wl` + size-stability + bridge
extras + post-dispatch slot). Keyed by `opTok` + the `<Op>Resid` `Resid`. -/
def BinIntCellResid
    (opTok : BinOp)
    (Resid : ((R : Register) → Option (RegisterType R)) → NativeAddrs → Arena →
      StackLayout → BitVec 64 → BitVec 64 → BitVec 64 → BitVec 64 → BitVec 64 →
      Vsa.Machine.Config → Prop)
    (g : (R : Register) → Option (RegisterType R))
    (N : NativeAddrs) (A : Arena) (SL : StackLayout) (φf φc : Addr → Nat)
    (st st' st'' : Vsa.While.St) (el er : Expr) (a b : Int)
    (sp r sret aExpr : BitVec 64) (m0 : Mem) : Prop :=
  st'.store.frames.size = st''.store.frames.size ∧
  st'.store.closures.size = st''.store.closures.size ∧
  -- ITEM ZERO B1: the post-LEFT store-bodies invariant (spec-side
  -- preservation residual for the RIGHT sub-call's budget).
  Vsa.While.StoreBodiesBound st'.store Vsa.While.perCallBudget ∧
  ∃ (aLOp aROp Wl : BitVec 64),
    BinArmExtras g N A SL opTok el er sp r sret aExpr aLOp aROp m0 ∧
    (∀ (gpre : (R : Register) → Option (RegisterType R)) (v8 v9 v18 v19 : BitVec 64),
      (∀ c' : Vsa.Machine.Config,
        TwoSubReturn gpre N A SL φf φc st.store.frames.size st.store.closures.size
          st' st'' (.int a) (.int b) sp r sret v8 v9 v18 m0 c' →
        Resid gpre N A SL sp r sret aExpr Wl c') ∧
      g Register.x8 = some v8 ∧ g Register.x9 = some v9 ∧
      g Register.x18 = some v18 ∧ g Register.x2 = some sp ∧ g Register.x19 = some v19 ∧
      (∀ R : Register, AbiPreservedNoise R →
        (Register.x8 == R) = false → (Register.x9 == R) = false →
        (Register.x18 == R) = false → (Register.x2 == R) = false →
        gpre R = g R))

/-- Per-cell eq/ne residual (∃-commits `aLOp aROp w19` + left-value survival +
`EqResid` front residual, for arbitrary operand values `vl vr`). -/
def BinEqCellResid
    (op : Vsa.Sim.EqNeOp) (opTok : BinOp) (link jalPC : BitVec 64) (jImm : BitVec 21)
    (g : (R : Register) → Option (RegisterType R))
    (N : NativeAddrs) (A : Arena) (SL : StackLayout) (φf φc : Addr → Nat)
    (st st' st'' : Vsa.While.St) (el er : Expr) (vl vr : Value)
    (sp r sret aExpr : BitVec 64) (m0 : Mem) : Prop :=
  st'.store.frames.size = st''.store.frames.size ∧
  st'.store.closures.size = st''.store.closures.size ∧
  -- ITEM ZERO B1: the post-LEFT store-bodies invariant (spec-side
  -- preservation residual for the RIGHT sub-call's budget).
  Vsa.While.StoreBodiesBound st'.store Vsa.While.perCallBudget ∧
  ∃ (aLOp aROp w19 : BitVec 64),
    BinArmExtras g N A SL opTok el er sp r sret aExpr aLOp aROp m0 ∧
    (∀ (φ : Addr → Nat) (mm mm' : Mem),
      ValueRepr mm N φ (sp.toNat - 968) vl →
      (∀ k : Nat, ¬ (SL.lo ≤ k ∧ k < sp.toNat - 1080) → ¬ (A.lo ≤ k ∧ k < A.hi) →
        ¬ ((sp.toNat - 944) ≤ k ∧ k < (sp.toNat - 944) + 24) → mm[k]? = mm'[k]?) →
      ValueRepr mm' N φ (sp.toNat - 968) vl) ∧
    (∀ (gpre : (R : Register) → Option (RegisterType R)) (v8 v9 v18 v19 : BitVec 64),
      ∀ c2 : Vsa.Machine.Config,
      TwoSubReturn gpre N A SL φf φc st.store.frames.size st.store.closures.size
        st' st'' vl vr sp r sret v8 v9 v18 m0 c2 →
      Vsa.Sim.EqResid op gpre g N A SL φf φc st' st'' sp r sret aExpr v8 v9 v18 v19 w19 vl vr
        link jalPC jImm c2.σ.sailOutput m0 c2)

/-- **Entry-guarded int cell** — the wave-49 B2-carry.

The BARE `∀ …, BinIntCellResid …` statement is FALSE: at `m0 := ∅` the `∃`-body's
`BinArmExtras.slot6` demands the EX_BINARY jump-table word `KindSlotPinned 6
0x800034e8 m0`, which the empty memory does not carry — 11 kernel refutations in
`experiments/fleet/obstructions/RefutBatteryCur.lean`.  The cure is the one the 6
unary/logic siblings (`NegResid`/`NotResid`/`AndTrueResid`/…) already use: carry
the arm's `EvalEntry`, whose `ground.table.slot6` supplies EXACTLY the missing pin
(`CureValidationCur.evalEntry_supplies_slot6`), and which is itself uninhabited at
`∅` (`evalEntry_empty_false`), so the countermodel that killed the bare form is
gone.  `guard` is the per-op side condition — `fun _ _ => True` for every op but
`div`, whose overflow guard `¬(a = -2^63 ∧ b = -1)` routes the wrap arm to
`hDivOv`. -/
def BinIntCell
    (opTok : BinOp)
    (Resid : ((R : Register) → Option (RegisterType R)) → NativeAddrs → Arena →
      StackLayout → BitVec 64 → BitVec 64 → BitVec 64 → BitVec 64 → BitVec 64 →
      Vsa.Machine.Config → Prop)
    (guard : Int → Int → Prop) : Prop :=
  ∀ (g : (R : Register) → Option (RegisterType R))
    (N : NativeAddrs) (A : Arena) (SL : StackLayout) (φf φc : Addr → Nat)
    (st st' st'' : Vsa.While.St) (d : Nat) (env : Addr) (el er : Expr) (a b : Int),
    guard a b →
    ∀ (sp r sret aEnv aExpr : BitVec 64) (m0 : Mem) (c : Vsa.Machine.Config),
      EvalEntry g N A SL φf φc st d env (.binary opTok el er) sp r sret aEnv aExpr m0 c →
      BinIntCellResid opTok Resid g N A SL φf φc st st' st'' el er a b sp r sret aExpr m0

/-- **Entry-guarded eq/ne cell** — the same wave-49 B2-carry for the two
`BinEqCellResid` cells (`experiments/fleet/obstructions/RefutBatteryCur.lean`
refutes both bare forms at `m0 := ∅`; see `BinIntCell`). -/
def BinEqCell
    (op : Vsa.Sim.EqNeOp) (opTok : BinOp) (link jalPC : BitVec 64) (jImm : BitVec 21) : Prop :=
  ∀ (g : (R : Register) → Option (RegisterType R))
    (N : NativeAddrs) (A : Arena) (SL : StackLayout) (φf φc : Addr → Nat)
    (st st' st'' : Vsa.While.St) (d : Nat) (env : Addr) (el er : Expr) (vl vr : Value)
    (sp r sret aEnv aExpr : BitVec 64) (m0 : Mem) (c : Vsa.Machine.Config),
    EvalEntry g N A SL φf φc st d env (.binary opTok el er) sp r sret aEnv aExpr m0 c →
    BinEqCellResid op opTok link jalPC jImm g N A SL φf φc st st' st'' el er vl vr sp r sret aExpr m0

/-- **`eval_binary_row`** — the `hBinary` dispatcher shell (see the section doc). -/
theorem eval_binary_row
    (hIAdd : BinIntCell .add Vsa.Sim.AddResid (fun _ _ => True))
    (hISub : BinIntCell .sub Vsa.Sim.SubResid (fun _ _ => True))
    (hIMul : BinIntCell .mul Vsa.Sim.MulResid (fun _ _ => True))
    (hIDiv : BinIntCell .div Vsa.Sim.DivResid (fun a b => ¬(a = -2^63 ∧ b = -1)))
    (hIMod : BinIntCell .mod Vsa.Sim.ModResid (fun _ _ => True))
    (hILt : BinIntCell .lt Vsa.Sim.LtResid (fun _ _ => True))
    (hILe : BinIntCell .le Vsa.Sim.LeResid (fun _ _ => True))
    (hIGt : BinIntCell .gt Vsa.Sim.GtResid (fun _ _ => True))
    (hIGe : BinIntCell .ge Vsa.Sim.GeResid (fun _ _ => True))
    (hEq : BinEqCell .eq .eq (0x80003720#64) (0x8000371c#64) (0x1ff140#21))
    (hNe : BinEqCell .ne .ne (0x80003770#64) (0x8000376c#64) (0x1ff0f0#21))
    (hStrAddL : ∀ st d env el er st'' (sl : String) (rv : Value),
        EvalIH st d env (.binary .add el er) st''
          (.str ((Value.str sl).catDisplay st''.store ++ rv.catDisplay st''.store)))
    (hStrAddR : ∀ st d env el er st'' (lv : Value) (sr : String),
        EvalIH st d env (.binary .add el er) st''
          (.str (lv.catDisplay st''.store ++ (Value.str sr).catDisplay st''.store)))
    (hStrLt : ∀ st d env el er st'' (sl sr : String),
        EvalIH st d env (.binary .lt el er) st'' (.bool (sl < sr)))
    (hStrLe : ∀ st d env el er st'' (sl sr : String),
        EvalIH st d env (.binary .le el er) st'' (.bool (sl < sr || sl == sr)))
    (hStrGt : ∀ st d env el er st'' (sl sr : String),
        EvalIH st d env (.binary .gt el er) st'' (.bool (sr < sl)))
    (hStrGe : ∀ st d env el er st'' (sl sr : String),
        EvalIH st d env (.binary .ge el er) st'' (.bool (sr < sl || sl == sr)))
    (hDivOv : ∀ st d env el er st'',
        EvalIH st d env (.binary .div el er) st''
          (.int (wrap64 ((-2^63 : Int).tdiv (-1))))) :
    ∀ (st : Vsa.While.St) (d : Nat) (env : Addr) (op : BinOp) (l r : Expr)
      (st' st'' : Vsa.While.St) (lv rv v : Value)
      (a : EvalE st d env l st' lv) (a_1 : EvalE st' d env r st'' rv)
      (a_2 : binOpSem st''.store op lv rv = some v),
      mEvalE st d env l st' lv a →
      mEvalE st' d env r st'' rv a_1 →
      mEvalE st d env (.binary op l r) st'' v
        (EvalE.binary st d env op l r st' st'' lv rv v a a_1 a_2) := by
  intro st d env op el er st' st'' lv rv v hEl hEr hsem ihL ihR
  show EvalIH st d env (.binary op el er) st'' v
  have ihL' : EvalIH st d env el st' lv := ihL
  have ihR' : EvalIH st' d env er st'' rv := ihR
  cases op with
  | add =>
    match lv, rv, hsem with
    | .str sl, rv, hsem =>
      simp only [binOpSem] at hsem; cases hsem; exact hStrAddL st d env el er st'' sl rv
    | .int a, .str sr, hsem =>
      simp only [binOpSem] at hsem; cases hsem; exact hStrAddR st d env el er st'' (.int a) sr
    | .bool bb, .str sr, hsem =>
      simp only [binOpSem] at hsem; cases hsem; exact hStrAddR st d env el er st'' (.bool bb) sr
    | .null, .str sr, hsem =>
      simp only [binOpSem] at hsem; cases hsem; exact hStrAddR st d env el er st'' .null sr
    | .closure aa, .str sr, hsem =>
      simp only [binOpSem] at hsem; cases hsem; exact hStrAddR st d env el er st'' (.closure aa) sr
    | .native ff, .str sr, hsem =>
      simp only [binOpSem] at hsem; cases hsem; exact hStrAddR st d env el er st'' (.native ff) sr
    | .int a, .int b, hsem =>
      simp only [binOpSem] at hsem; cases hsem
      intro g N A SL φf φc sp r sret aEnv aExpr m0 c hc
      obtain ⟨hSF, hSC, hSB, aLOp, aROp, Wl, hX, hP⟩ :=
        hIAdd g N A SL φf φc st st' st'' d env el er a b trivial sp r sret aEnv aExpr m0 c hc
      exact binRow_add g N A SL φf φc st st' st'' d env el er a b
        sp r sret aEnv aExpr aLOp aROp Wl m0 hX ihL' ihR'
        (EvalE.binary st d env .add el er st' st'' (.int a) (.int b) _ hEl hEr (by simp [binOpSem]))
        hSF hSC hSB hP c hc
  | sub =>
    match lv, rv, hsem with
    | .int a, .int b, hsem =>
      simp only [binOpSem] at hsem; cases hsem
      intro g N A SL φf φc sp r sret aEnv aExpr m0 c hc
      obtain ⟨hSF, hSC, hSB, aLOp, aROp, Wl, hX, hP⟩ :=
        hISub g N A SL φf φc st st' st'' d env el er a b trivial sp r sret aEnv aExpr m0 c hc
      exact binRow_sub g N A SL φf φc st st' st'' d env el er a b
        sp r sret aEnv aExpr aLOp aROp Wl m0 hX ihL' ihR'
        (EvalE.binary st d env .sub el er st' st'' (.int a) (.int b) _ hEl hEr (by simp [binOpSem]))
        hSF hSC hSB hP c hc
  | mul =>
    match lv, rv, hsem with
    | .int a, .int b, hsem =>
      simp only [binOpSem] at hsem; cases hsem
      intro g N A SL φf φc sp r sret aEnv aExpr m0 c hc
      obtain ⟨hSF, hSC, hSB, aLOp, aROp, Wl, hX, hP⟩ :=
        hIMul g N A SL φf φc st st' st'' d env el er a b trivial sp r sret aEnv aExpr m0 c hc
      exact binRow_mul g N A SL φf φc st st' st'' d env el er a b
        sp r sret aEnv aExpr aLOp aROp Wl m0 hX ihL' ihR'
        (EvalE.binary st d env .mul el er st' st'' (.int a) (.int b) _ hEl hEr (by simp [binOpSem]))
        hSF hSC hSB hP c hc
  | div =>
    match lv, rv, hsem with
    | .int a, .int b, hsem =>
      simp only [binOpSem] at hsem
      by_cases hb0 : b = 0
      · subst hb0; simp at hsem
      · rw [if_neg (by simpa using hb0)] at hsem; cases hsem
        intro g N A SL φf φc sp r sret aEnv aExpr m0 c hc
        by_cases hov : (a = -2^63 ∧ b = -1)
        · obtain ⟨ha, hbm⟩ := hov; subst ha; subst hbm
          exact hDivOv st d env el er st'' g N A SL φf φc sp r sret aEnv aExpr m0 c hc
        · obtain ⟨hSF, hSC, hSB, aLOp, aROp, Wl, hX, hP⟩ :=
            hIDiv g N A SL φf φc st st' st'' d env el er a b hov sp r sret aEnv aExpr m0 c hc
          exact binRow_div g N A SL φf φc st st' st'' d env el er a b
            sp r sret aEnv aExpr aLOp aROp Wl m0 hb0 hov hX ihL' ihR'
            (EvalE.binary st d env .div el er st' st'' (.int a) (.int b) _ hEl hEr
              (by simp [binOpSem, hb0]))
            hSF hSC hSB hP c hc
  | mod =>
    match lv, rv, hsem with
    | .int a, .int b, hsem =>
      simp only [binOpSem] at hsem
      by_cases hb0 : b = 0
      · subst hb0; simp at hsem
      · rw [if_neg (by simpa using hb0)] at hsem; cases hsem
        intro g N A SL φf φc sp r sret aEnv aExpr m0 c hc
        obtain ⟨hSF, hSC, hSB, aLOp, aROp, Wl, hX, hP⟩ :=
          hIMod g N A SL φf φc st st' st'' d env el er a b trivial sp r sret aEnv aExpr m0 c hc
        exact binRow_mod g N A SL φf φc st st' st'' d env el er a b
          sp r sret aEnv aExpr aLOp aROp Wl m0 hb0 hX ihL' ihR'
          (EvalE.binary st d env .mod el er st' st'' (.int a) (.int b) _ hEl hEr
            (by simp [binOpSem, hb0]))
          hSF hSC hSB hP c hc
  | lt =>
    match lv, rv, hsem with
    | .str sl, .str sr, hsem =>
      simp only [binOpSem] at hsem; cases hsem; exact hStrLt st d env el er st'' sl sr
    | .int a, .int b, hsem =>
      simp only [binOpSem] at hsem; cases hsem
      intro g N A SL φf φc sp r sret aEnv aExpr m0 c hc
      obtain ⟨hSF, hSC, hSB, aLOp, aROp, Wl, hX, hP⟩ :=
        hILt g N A SL φf φc st st' st'' d env el er a b trivial sp r sret aEnv aExpr m0 c hc
      exact binRow_lt g N A SL φf φc st st' st'' d env el er a b
        sp r sret aEnv aExpr aLOp aROp Wl m0 hX ihL' ihR'
        (EvalE.binary st d env .lt el er st' st'' (.int a) (.int b) _ hEl hEr (by simp [binOpSem]))
        hSF hSC hSB hP c hc
  | le =>
    match lv, rv, hsem with
    | .str sl, .str sr, hsem =>
      simp only [binOpSem] at hsem; cases hsem; exact hStrLe st d env el er st'' sl sr
    | .int a, .int b, hsem =>
      simp only [binOpSem] at hsem; cases hsem
      intro g N A SL φf φc sp r sret aEnv aExpr m0 c hc
      obtain ⟨hSF, hSC, hSB, aLOp, aROp, Wl, hX, hP⟩ :=
        hILe g N A SL φf φc st st' st'' d env el er a b trivial sp r sret aEnv aExpr m0 c hc
      exact binRow_le g N A SL φf φc st st' st'' d env el er a b
        sp r sret aEnv aExpr aLOp aROp Wl m0 hX ihL' ihR'
        (EvalE.binary st d env .le el er st' st'' (.int a) (.int b) _ hEl hEr (by simp [binOpSem]))
        hSF hSC hSB hP c hc
  | gt =>
    match lv, rv, hsem with
    | .str sl, .str sr, hsem =>
      simp only [binOpSem] at hsem; cases hsem; exact hStrGt st d env el er st'' sl sr
    | .int a, .int b, hsem =>
      simp only [binOpSem] at hsem; cases hsem
      intro g N A SL φf φc sp r sret aEnv aExpr m0 c hc
      obtain ⟨hSF, hSC, hSB, aLOp, aROp, Wl, hX, hP⟩ :=
        hIGt g N A SL φf φc st st' st'' d env el er a b trivial sp r sret aEnv aExpr m0 c hc
      exact binRow_gt g N A SL φf φc st st' st'' d env el er a b
        sp r sret aEnv aExpr aLOp aROp Wl m0 hX ihL' ihR'
        (EvalE.binary st d env .gt el er st' st'' (.int a) (.int b) _ hEl hEr (by simp [binOpSem]))
        hSF hSC hSB hP c hc
  | ge =>
    match lv, rv, hsem with
    | .str sl, .str sr, hsem =>
      simp only [binOpSem] at hsem; cases hsem; exact hStrGe st d env el er st'' sl sr
    | .int a, .int b, hsem =>
      simp only [binOpSem] at hsem; cases hsem
      intro g N A SL φf φc sp r sret aEnv aExpr m0 c hc
      obtain ⟨hSF, hSC, hSB, aLOp, aROp, Wl, hX, hP⟩ :=
        hIGe g N A SL φf φc st st' st'' d env el er a b trivial sp r sret aEnv aExpr m0 c hc
      exact binRow_ge g N A SL φf φc st st' st'' d env el er a b
        sp r sret aEnv aExpr aLOp aROp Wl m0 hX ihL' ihR'
        (EvalE.binary st d env .ge el er st' st'' (.int a) (.int b) _ hEl hEr (by simp [binOpSem]))
        hSF hSC hSB hP c hc
  | eq =>
    simp only [binOpSem] at hsem; cases hsem
    intro g N A SL φf φc sp r sret aEnv aExpr m0 c hc
    obtain ⟨hSF, hSC, hSB, aLOp, aROp, w19, hX, hVl, hRes⟩ :=
      hEq g N A SL φf φc st st' st'' d env el er lv rv sp r sret aEnv aExpr m0 c hc
    exact binRow_eq g N A SL φf φc st st' st'' d env el er lv rv
      sp r sret aEnv aExpr aLOp aROp w19 m0 hX ihL' ihR'
      (EvalE.binary st d env .eq el er st' st'' lv rv _ hEl hEr (by simp [binOpSem]))
      hSF hSC hSB hVl hRes c hc
  | ne =>
    simp only [binOpSem] at hsem; cases hsem
    intro g N A SL φf φc sp r sret aEnv aExpr m0 c hc
    obtain ⟨hSF, hSC, hSB, aLOp, aROp, w19, hX, hVl, hRes⟩ :=
      hNe g N A SL φf φc st st' st'' d env el er lv rv sp r sret aEnv aExpr m0 c hc
    exact binRow_ne g N A SL φf φc st st' st'' d env el er lv rv
      sp r sret aEnv aExpr aLOp aROp w19 m0 hX ihL' ihR'
      (EvalE.binary st d env .ne el er st' st'' lv rv _ hEl hEr (by simp [binOpSem]))
      hSF hSC hSB hVl hRes c hc
'''

if __name__ == "__main__":
    emit()
