#!/usr/bin/env python3
"""Generate VsaIris/Vsa/MallocFastImage.lean: `pathLoaded_of_image`, the fast
paths' code bytes (`pathText`, VsaIris/Vsa/MallocFastCode.lean) from the
approved image: .text bytes from `FixedTextLoaded`, the `_impure_ptr` word
from `ImageStaticsLoaded`. One conjunction per `pathChunk<i>`.

Usage: python3 scripts/gen_malloc_path_image.py
"""
import re, pathlib
src = pathlib.Path('VsaIris/Vsa/MallocFastCode.lean').read_text()
chunks = {}
for m in re.finditer(r'def pathChunk(\d+) : List \(Nat × BitVec 8\) :=\n  \[(.*?)\]\n', src):
    chunks[int(m.group(1))] = [(int(a, 16), int(b, 16)) for a, b in
                               re.findall(r'\(0x([0-9a-f]+), 0x([0-9a-f]+)#8\)', m.group(2))]
TEXT_BASE, TEXT_SIZE = 0x80000000, 101344
IMPURE = 0x8001b970
L = ['-- Generated by scripts/gen_malloc_path_image.py; do not edit.',
     'import VsaIris.Vsa.MallocFastCode', 'import Vsa.Sim.Code.FixedImage', 'import Vsa.Sim.Code.ImageStatics', '',
     '/-! The fast paths\' code bytes from the approved image. -/', '',
     'namespace VsaIris.MallocFast', '', 'open Vsa.Sim.Code', '']
for i in sorted(chunks):
    terms = []
    for a, b in chunks[i]:
        if TEXT_BASE <= a < TEXT_BASE + TEXT_SIZE:
            terms.append(f'ht {a - TEXT_BASE} (by decide)')
        else:
            assert IMPURE <= a < IMPURE + 8, hex(a)
            terms.append(f'i{a - IMPURE}')
    uses_i = any(t.startswith('i') for t in terms)
    L.append(f'theorem pathChunk{i}_image {{mem : Std.ExtHashMap Nat (BitVec 8)}} (ht : FixedTextLoaded mem)')
    hs = 'hs' if uses_i else '_hs'
    L.append(f'    ({hs} : ImageStaticsLoaded mem) : ∀ p ∈ pathChunk{i}, mem[p.1]? = some p.2 := by')
    if uses_i:
        L.append('  obtain ⟨i0, i1, i2, i3, i4, i5, i6, i7⟩ := imageStatics_impurePtr_range hs')
    L.append(f'  simp only [pathChunk{i}, List.forall_mem_cons]')
    L.append('  exact ⟨' + ',\n    '.join(terms) + ',\n    fun _ h => by cases h⟩\n')
n = max(chunks) + 1
L.append('/-- **The fast paths\' code is the approved image\'s.** -/')
L.append('theorem pathLoaded_of_image {mem : Std.ExtHashMap Nat (BitVec 8)} (ht : FixedTextLoaded mem)')
L.append('    (hs : ImageStaticsLoaded mem) : PathLoaded mem := by')
L.append('  intro p hp')
L.append('  simp only [pathText, List.mem_append] at hp')
L.append('  rcases hp with ' + ' | '.join(f'h{i}' for i in range(n)))
for i in range(n):
    L.append(f'  · exact pathChunk{i}_image ht hs p h{i}')
L.append('\nend VsaIris.MallocFast\n')
pathlib.Path('VsaIris/Vsa/MallocFastImage.lean').write_text('\n'.join(L))
print(n, 'chunks')
