import Vsa.Sim.ValueSites
import Vsa.Sim.StrcmpSites
import Vsa.Sim.Code.Exec_stmt
import Vsa.Sim.DecodeTable.Batch03Part07
import Vsa.Sim.DecodeTable.Batch01Part01
import Vsa.Sim.DecodeTable.Batch01Part14
import Vsa.Sim.DecodeTable.Batch01Part32
import Vsa.Sim.DecodeTable.Batch02Part02
import Vsa.Sim.DecodeTable.Batch02Part03
import Vsa.Sim.DecodeTable.Batch02Part04
import Vsa.Sim.DecodeTable.Batch02Part28
import Vsa.Sim.DecodeTable.Batch03Part18
import Vsa.Sim.DecodeTable.Batch03Part19
import Vsa.Sim.DecodeTable.Batch04Part24
import Vsa.Sim.DecodeTable.Batch05Part11
import Vsa.Sim.DecodeTable.Batch05Part13
import Vsa.Sim.DecodeTable.Batch15Part06
import Vsa.Sim.DecodeTable.Batch15Part12
import Vsa.Sim.DecodeTable.Batch15Part13
import Vsa.Sim.DecodeTable.Batch16Part06

/-!
# Layer 4 — M4 statement family: block do-while loop-body sites (generated)

Per-site `StepObs` battery for the `exec_stmt` **block** arm (kind 2, arm
`0x8000418c`) do-while loop body at `0x800041a4`, generated by
`scripts/gen_sites.py` from `scripts/exec_stmt_block_sites.tsv` against
`Vsa.Sim.Code.Exec_stmtLoaded`.  Covers the per-iteration setup
(`ld`/`mv`/`add`/`ld`/`mv`/`mv`/`sd`), the recursive `jal exec_stmt`
(`0x800041c4`), the `bnez a0` status check (both variants), the loop control
(`ld`/`lw`/`addi`/`sext.w`), the `blt` back-edge (both variants), and the
normal-exit `li a0,0`/`j 0x8000409c`.  The `slli a4,a6,0x3` at `0x800041a8` is
HAND-written at the tail (`exec_slli_gen`), the only site the generator's class
set does not cover.  Do not hand-edit the generated site bodies; regenerate
instead.

These are the machine-decode residual consumed by the block-arm loop-body glue
(`ExecSeqStep`/`hstep`).

NO `sorry`/`axiom`/`native_decide`/`bv_decide`.
-/
open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail ConcurrencyInterfaceV1 Vsa
open Register
open Sail.ConcurrencyInterfaceV1.PreSail
open Vsa.Machine (MState Config Step Steps)

set_option maxHeartbeats 8000000
set_option maxRecDepth 1000000

namespace Vsa.Sim

/-- 0x800041a4: `ld x15,0x8(x8)`. -/
theorem site_800041a4_es (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v8 : BitVec 64)
    (b0 b1 b2 b3 b4 b5 b6 b7 : BitVec 8)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx8 : σ.regs.get? Register.x8 = some v8)
    (hmem : Vsa.Sim.Code.Exec_stmtLoaded σ.mem)
    (hpcv : pc = (0x800041a4#64 : BitVec 64))
    (hlo : 0x80000000 ≤ (v8 + sign_extend (m := 64) (0x008#12)).toNat)
    (hhiram : (v8 + sign_extend (m := 64) (0x008#12)).toNat + 8 ≤ 0x100000000)
    (hhtif : (v8 + sign_extend (m := 64) (0x008#12)).toNat + 8 ≤ tohostAddr
      ∨ tohostAddr + 8 ≤ (v8 + sign_extend (m := 64) (0x008#12)).toNat)
    (halign : (v8 + sign_extend (m := 64) (0x008#12)).toNat % 8 = 0)
    (h0 : σ.mem[(v8 + sign_extend (m := 64) (0x008#12)).toNat]? = some b0)
    (h1 : σ.mem[(v8 + sign_extend (m := 64) (0x008#12)).toNat + 1]? = some b1)
    (h2 : σ.mem[(v8 + sign_extend (m := 64) (0x008#12)).toNat + 2]? = some b2)
    (h3 : σ.mem[(v8 + sign_extend (m := 64) (0x008#12)).toNat + 3]? = some b3)
    (h4 : σ.mem[(v8 + sign_extend (m := 64) (0x008#12)).toNat + 4]? = some b4)
    (h5 : σ.mem[(v8 + sign_extend (m := 64) (0x008#12)).toNat + 5]? = some b5)
    (h6 : σ.mem[(v8 + sign_extend (m := 64) (0x008#12)).toNat + 6]? = some b6)
    (h7 : σ.mem[(v8 + sign_extend (m := 64) (0x008#12)).toNat + 7]? = some b7)
    (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x15
        (sign_extend (m := 64)
          ((((((((b7.append b6).append b5).append b4).append b3).append b2).append b1).append b0) : BitVec (8 * 8)))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.exec_stmt_at_800041a4 hmem
  exact stepObs_alu σ i u (0x800041a4#64) vminstret (0x00843783#32)
    (instruction.LOAD (0x008#12, regidx.Regidx 0x08#5, regidx.Regidx 0x0f#5, false, 8))
    Register.x15 (sign_extend (m := 64) ((((((((b7.append b6).append b5).append b4).append b3).append b2).append b1).append b0) : BitVec (8 * 8)))
    (0x83#8) (0x37#8) (0x84#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_00843783 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (exec_ld σ (0x800041a4#64) (0x008#12) (regidx.Regidx 0x08#5) (regidx.Regidx 0x0f#5)
      (sigma3_alu σ (0x800041a4#64) Register.x15 (sign_extend (m := 64) ((((((((b7.append b6).append b5).append b4).append b3).append b2).append b1).append b0) : BitVec (8 * 8))))
      v8 b0 b1 b2 b3 b4 b5 b6 b7 hG
      (rX_bits_x8 _ v8
        (by rw [get?_afterNextPC σ (0x800041a4#64) _ (by decide) (by decide)]; exact hx8))
      (wX_bits_x15 _ (sign_extend (m := 64) ((((((((b7.append b6).append b5).append b4).append b3).append b2).append b1).append b0) : BitVec (8 * 8))))
      hlo hhiram hhtif halign h0 h1 h2 h3 h4 h5 h6 h7)
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x800041ac: `addi x13,x18,0x0`. -/
theorem site_800041ac_es (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v18 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx18 : σ.regs.get? Register.x18 = some v18)
    (hmem : Vsa.Sim.Code.Exec_stmtLoaded σ.mem)
    (hpcv : pc = (0x800041ac#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x13
        (v18 + sign_extend (m := 64) (0x000#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.exec_stmt_at_800041ac hmem
  exact stepObs_alu σ i u (0x800041ac#64) vminstret (0x00090693#32)
    (instruction.ITYPE (0x000#12, regidx.Regidx 0x12#5, regidx.Regidx 0x0d#5, iop.ADDI))
    Register.x13 (v18 + sign_extend (m := 64) (0x000#12))
    (0x93#8) (0x06#8) (0x09#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_00090693 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_addi_char (0x000#12) (regidx.Regidx 0x12#5) (regidx.Regidx 0x0d#5) v18
      (afterNextPC (afterPrelude σ) (0x800041ac#64))
      (sigma3_alu σ (0x800041ac#64) Register.x13 (v18 + sign_extend (m := 64) (0x000#12)))
      (rX_bits_x18 _ v18
        (by rw [get?_afterNextPC σ (0x800041ac#64) _ (by decide) (by decide)]; exact hx18))
      (wX_bits_x13 _ (v18 + sign_extend (m := 64) (0x000#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x800041b0: `add x15,x15,x14`. -/
theorem site_800041b0_es (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v15 v14 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hx14 : σ.regs.get? Register.x14 = some v14)
    (hmem : Vsa.Sim.Code.Exec_stmtLoaded σ.mem)
    (hpcv : pc = (0x800041b0#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x15 (v15 + v14)) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.exec_stmt_at_800041b0 hmem
  exact stepObs_alu σ i u (0x800041b0#64) vminstret (0x00e787b3#32)
    (instruction.RTYPE (regidx.Regidx 0x0e#5, regidx.Regidx 0x0f#5, regidx.Regidx 0x0f#5, rop.ADD))
    Register.x15 (v15 + v14)
    (0xb3#8) (0x87#8) (0xe7#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_00e787b3 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_rtype_add_char (regidx.Regidx 0x0e#5) (regidx.Regidx 0x0f#5) (regidx.Regidx 0x0f#5)
      v15 v14 (afterNextPC (afterPrelude σ) (0x800041b0#64))
      (sigma3_alu σ (0x800041b0#64) Register.x15 (v15 + v14))
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x800041b0#64) _ (by decide) (by decide)]; exact hx15))
      (rX_bits_x14 _ v14
        (by rw [get?_afterNextPC σ (0x800041b0#64) _ (by decide) (by decide)]; exact hx14))
      (wX_bits_x15 _ (v15 + v14)))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x800041b4: `ld x11,0x0(x15)`. -/
theorem site_800041b4_es (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v15 : BitVec 64)
    (b0 b1 b2 b3 b4 b5 b6 b7 : BitVec 8)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hmem : Vsa.Sim.Code.Exec_stmtLoaded σ.mem)
    (hpcv : pc = (0x800041b4#64 : BitVec 64))
    (hlo : 0x80000000 ≤ (v15 + sign_extend (m := 64) (0x000#12)).toNat)
    (hhiram : (v15 + sign_extend (m := 64) (0x000#12)).toNat + 8 ≤ 0x100000000)
    (hhtif : (v15 + sign_extend (m := 64) (0x000#12)).toNat + 8 ≤ tohostAddr
      ∨ tohostAddr + 8 ≤ (v15 + sign_extend (m := 64) (0x000#12)).toNat)
    (halign : (v15 + sign_extend (m := 64) (0x000#12)).toNat % 8 = 0)
    (h0 : σ.mem[(v15 + sign_extend (m := 64) (0x000#12)).toNat]? = some b0)
    (h1 : σ.mem[(v15 + sign_extend (m := 64) (0x000#12)).toNat + 1]? = some b1)
    (h2 : σ.mem[(v15 + sign_extend (m := 64) (0x000#12)).toNat + 2]? = some b2)
    (h3 : σ.mem[(v15 + sign_extend (m := 64) (0x000#12)).toNat + 3]? = some b3)
    (h4 : σ.mem[(v15 + sign_extend (m := 64) (0x000#12)).toNat + 4]? = some b4)
    (h5 : σ.mem[(v15 + sign_extend (m := 64) (0x000#12)).toNat + 5]? = some b5)
    (h6 : σ.mem[(v15 + sign_extend (m := 64) (0x000#12)).toNat + 6]? = some b6)
    (h7 : σ.mem[(v15 + sign_extend (m := 64) (0x000#12)).toNat + 7]? = some b7)
    (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x11
        (sign_extend (m := 64)
          ((((((((b7.append b6).append b5).append b4).append b3).append b2).append b1).append b0) : BitVec (8 * 8)))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.exec_stmt_at_800041b4 hmem
  exact stepObs_alu σ i u (0x800041b4#64) vminstret (0x0007b583#32)
    (instruction.LOAD (0x000#12, regidx.Regidx 0x0f#5, regidx.Regidx 0x0b#5, false, 8))
    Register.x11 (sign_extend (m := 64) ((((((((b7.append b6).append b5).append b4).append b3).append b2).append b1).append b0) : BitVec (8 * 8)))
    (0x83#8) (0xb5#8) (0x07#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_0007b583 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (exec_ld σ (0x800041b4#64) (0x000#12) (regidx.Regidx 0x0f#5) (regidx.Regidx 0x0b#5)
      (sigma3_alu σ (0x800041b4#64) Register.x11 (sign_extend (m := 64) ((((((((b7.append b6).append b5).append b4).append b3).append b2).append b1).append b0) : BitVec (8 * 8))))
      v15 b0 b1 b2 b3 b4 b5 b6 b7 hG
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x800041b4#64) _ (by decide) (by decide)]; exact hx15))
      (wX_bits_x11 _ (sign_extend (m := 64) ((((((((b7.append b6).append b5).append b4).append b3).append b2).append b1).append b0) : BitVec (8 * 8))))
      hlo hhiram hhtif halign h0 h1 h2 h3 h4 h5 h6 h7)
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x800041b8: `addi x12,x19,0x0`. -/
theorem site_800041b8_es (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v19 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx19 : σ.regs.get? Register.x19 = some v19)
    (hmem : Vsa.Sim.Code.Exec_stmtLoaded σ.mem)
    (hpcv : pc = (0x800041b8#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x12
        (v19 + sign_extend (m := 64) (0x000#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.exec_stmt_at_800041b8 hmem
  exact stepObs_alu σ i u (0x800041b8#64) vminstret (0x00098613#32)
    (instruction.ITYPE (0x000#12, regidx.Regidx 0x13#5, regidx.Regidx 0x0c#5, iop.ADDI))
    Register.x12 (v19 + sign_extend (m := 64) (0x000#12))
    (0x13#8) (0x86#8) (0x09#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_00098613 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_addi_char (0x000#12) (regidx.Regidx 0x13#5) (regidx.Regidx 0x0c#5) v19
      (afterNextPC (afterPrelude σ) (0x800041b8#64))
      (sigma3_alu σ (0x800041b8#64) Register.x12 (v19 + sign_extend (m := 64) (0x000#12)))
      (rX_bits_x19 _ v19
        (by rw [get?_afterNextPC σ (0x800041b8#64) _ (by decide) (by decide)]; exact hx19))
      (wX_bits_x12 _ (v19 + sign_extend (m := 64) (0x000#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x800041bc: `addi x10,x9,0x0`. -/
theorem site_800041bc_es (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v9 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx9 : σ.regs.get? Register.x9 = some v9)
    (hmem : Vsa.Sim.Code.Exec_stmtLoaded σ.mem)
    (hpcv : pc = (0x800041bc#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x10
        (v9 + sign_extend (m := 64) (0x000#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.exec_stmt_at_800041bc hmem
  exact stepObs_alu σ i u (0x800041bc#64) vminstret (0x00048513#32)
    (instruction.ITYPE (0x000#12, regidx.Regidx 0x09#5, regidx.Regidx 0x0a#5, iop.ADDI))
    Register.x10 (v9 + sign_extend (m := 64) (0x000#12))
    (0x13#8) (0x85#8) (0x04#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_00048513 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_addi_char (0x000#12) (regidx.Regidx 0x09#5) (regidx.Regidx 0x0a#5) v9
      (afterNextPC (afterPrelude σ) (0x800041bc#64))
      (sigma3_alu σ (0x800041bc#64) Register.x10 (v9 + sign_extend (m := 64) (0x000#12)))
      (rX_bits_x9 _ v9
        (by rw [get?_afterNextPC σ (0x800041bc#64) _ (by decide) (by decide)]; exact hx9))
      (wX_bits_x10 _ (v9 + sign_extend (m := 64) (0x000#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x800041c0: `sd x16,0x8(x2)`. -/
theorem site_800041c0_es (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v2 v16 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx2 : σ.regs.get? Register.x2 = some v2)
    (hx16 : σ.regs.get? Register.x16 = some v16)
    (hmem : Vsa.Sim.Code.Exec_stmtLoaded σ.mem)
    (hpcv : pc = (0x800041c0#64 : BitVec 64))
    (halo : 0x80000000 ≤ (v2 + sign_extend (m := 64) (0x008#12)).toNat)
    (hahiram : (v2 + sign_extend (m := 64) (0x008#12)).toNat + 8 ≤ 0x100000000)
    (hahiwin : tohostAddr + 16 ≤ (v2 + sign_extend (m := 64) (0x008#12)).toNat)
    (haalign : (v2 + sign_extend (m := 64) (0x008#12)).toNat % 8 = 0) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = writeMap8 (afterNextPC (afterPrelude σ) (0x800041c0#64)).mem
        (v2 + sign_extend (m := 64) (0x008#12)).toNat (sdData_val v16) ∧
      ReadsLikePost σ' (sigmaPost_store σ pc vminstret
        (writeMap8 (afterNextPC (afterPrelude σ) (0x800041c0#64)).mem (v2 + sign_extend (m := 64) (0x008#12)).toNat (sdData_val v16))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.exec_stmt_at_800041c0 hmem
  exact stepObs_store σ i u (0x800041c0#64) vminstret (0x01013423#32)
    (instruction.STORE (0x008#12, regidx.Regidx 0x10#5, regidx.Regidx 0x02#5, 8))
    (writeMap8 (afterNextPC (afterPrelude σ) (0x800041c0#64)).mem (v2 + sign_extend (m := 64) (0x008#12)).toNat (sdData_val v16))
    (0x23#8) (0x34#8) (0x01#8) (0x01#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_01013423 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (exec_sd_val σ (0x800041c0#64) (0x008#12) (regidx.Regidx 0x10#5) (regidx.Regidx 0x02#5)
      v2 v16 hG
      (rX_bits_x2 _ v2
        (by rw [get?_afterNextPC σ (0x800041c0#64) _ (by decide) (by decide)]; exact hx2))
      (rX_bits_x16 _ v16
        (by rw [get?_afterNextPC σ (0x800041c0#64) _ (by decide) (by decide)]; exact hx16))
      halo hahiram hahiwin haalign)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x800041c4: `jal x1,0x80003fe0` (link `x1 := 0x800041c8`). -/
theorem site_800041c4_es (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hmem : Vsa.Sim.Code.Exec_stmtLoaded σ.mem)
    (hpcv : pc = (0x800041c4#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_jal σ pc vminstret (0x1ffe1c#21) Register.x1 (BitVec.addInt pc 4)) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.exec_stmt_at_800041c4 hmem
  refine stepObs_jal σ i u (0x800041c4#64) vminstret (0xe1dff0ef#32) (0x1ffe1c#21)
    (regidx.Regidx 0x01#5) Register.x1 (BitVec.addInt (0x800041c4#64) 4)
    (0xef#8) (0xf0#8) (0xdf#8) (0xe1#8)
    hG hpc hminstret hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide)
    (by apply BitVec.eq_of_toNat_eq; decide) (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_e1dff0ef (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (by decide)
    (by decide) (by decide) (by decide) (by decide) (by decide) ?_ hi
  exact wX_bits_x1 _ (BitVec.addInt (0x800041c4#64) 4)

/-- Branch target of the taken site at 0x800041c8. -/
theorem site_800041c8_taken_es_tgt :
    (0x800041c8#64 + sign_extend (m := 64) (0x1ed4#13)) = (0x8000409c#64 : BitVec 64) := by
  apply BitVec.eq_of_toNat_eq; decide

/-- 0x800041c8: `bne x10,x0 → 0x8000409c` (TAKEN). -/
theorem site_800041c8_taken_es (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v10 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx10 : σ.regs.get? Register.x10 = some v10)
    (hmem : Vsa.Sim.Code.Exec_stmtLoaded σ.mem)
    (hpcv : pc = (0x800041c8#64 : BitVec 64))
    (hv : (v10 != (0#64)) = true) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_branch_taken σ pc vminstret (0x1ed4#13)) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.exec_stmt_at_800041c8 hmem
  exact stepObs_branch_taken σ i u (0x800041c8#64) vminstret (0x1ed4#13)
    (regidx.Regidx 0x0a#5) (regidx.Regidx 0x00#5) bop.BNE (0xec051ae3#32)
    (0xe3#8) (0x1a#8) (0x05#8) (0xec#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_ec051ae3 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_btype_bne_taken (0x1ed4#13) (regidx.Regidx 0x0a#5) (regidx.Regidx 0x00#5)
      v10 (0#64) (0x800041c8#64) initMisa (afterNextPC (afterPrelude σ) (0x800041c8#64))
      (rX_bits_x10 _ v10
        (by rw [get?_afterNextPC σ (0x800041c8#64) _ (by decide) (by decide)]; exact hx10))
      (rX_bits_zero _)
      (by rw [get?_afterNextPC σ (0x800041c8#64) _ (by decide) (by decide)]; exact hpc)
      (by rw [get?_afterNextPC σ (0x800041c8#64) _ (by decide) (by decide)]; exact hG.misa)
      (by rw [site_800041c8_taken_es_tgt]; decide) hv)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x800041c8: `bne x10,x0` (NOT taken). -/
theorem site_800041c8_nottaken_es (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v10 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx10 : σ.regs.get? Register.x10 = some v10)
    (hmem : Vsa.Sim.Code.Exec_stmtLoaded σ.mem)
    (hpcv : pc = (0x800041c8#64 : BitVec 64))
    (hv : (v10 != (0#64)) = false) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_branch_nottaken σ pc vminstret) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.exec_stmt_at_800041c8 hmem
  exact stepObs_branch_nottaken σ i u (0x800041c8#64) vminstret (0x1ed4#13)
    (regidx.Regidx 0x0a#5) (regidx.Regidx 0x00#5) bop.BNE (0xec051ae3#32)
    (0xe3#8) (0x1a#8) (0x05#8) (0xec#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_ec051ae3 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_btype_bne_nottaken (0x1ed4#13) (regidx.Regidx 0x0a#5) (regidx.Regidx 0x00#5)
      v10 (0#64) (afterNextPC (afterPrelude σ) (0x800041c8#64))
      (rX_bits_x10 _ v10
        (by rw [get?_afterNextPC σ (0x800041c8#64) _ (by decide) (by decide)]; exact hx10))
      (rX_bits_zero _)
      hv)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x800041cc: `ld x16,0x8(x2)`. -/
theorem site_800041cc_es (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v2 : BitVec 64)
    (b0 b1 b2 b3 b4 b5 b6 b7 : BitVec 8)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx2 : σ.regs.get? Register.x2 = some v2)
    (hmem : Vsa.Sim.Code.Exec_stmtLoaded σ.mem)
    (hpcv : pc = (0x800041cc#64 : BitVec 64))
    (hlo : 0x80000000 ≤ (v2 + sign_extend (m := 64) (0x008#12)).toNat)
    (hhiram : (v2 + sign_extend (m := 64) (0x008#12)).toNat + 8 ≤ 0x100000000)
    (hhtif : (v2 + sign_extend (m := 64) (0x008#12)).toNat + 8 ≤ tohostAddr
      ∨ tohostAddr + 8 ≤ (v2 + sign_extend (m := 64) (0x008#12)).toNat)
    (halign : (v2 + sign_extend (m := 64) (0x008#12)).toNat % 8 = 0)
    (h0 : σ.mem[(v2 + sign_extend (m := 64) (0x008#12)).toNat]? = some b0)
    (h1 : σ.mem[(v2 + sign_extend (m := 64) (0x008#12)).toNat + 1]? = some b1)
    (h2 : σ.mem[(v2 + sign_extend (m := 64) (0x008#12)).toNat + 2]? = some b2)
    (h3 : σ.mem[(v2 + sign_extend (m := 64) (0x008#12)).toNat + 3]? = some b3)
    (h4 : σ.mem[(v2 + sign_extend (m := 64) (0x008#12)).toNat + 4]? = some b4)
    (h5 : σ.mem[(v2 + sign_extend (m := 64) (0x008#12)).toNat + 5]? = some b5)
    (h6 : σ.mem[(v2 + sign_extend (m := 64) (0x008#12)).toNat + 6]? = some b6)
    (h7 : σ.mem[(v2 + sign_extend (m := 64) (0x008#12)).toNat + 7]? = some b7)
    (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x16
        (sign_extend (m := 64)
          ((((((((b7.append b6).append b5).append b4).append b3).append b2).append b1).append b0) : BitVec (8 * 8)))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.exec_stmt_at_800041cc hmem
  exact stepObs_alu σ i u (0x800041cc#64) vminstret (0x00813803#32)
    (instruction.LOAD (0x008#12, regidx.Regidx 0x02#5, regidx.Regidx 0x10#5, false, 8))
    Register.x16 (sign_extend (m := 64) ((((((((b7.append b6).append b5).append b4).append b3).append b2).append b1).append b0) : BitVec (8 * 8)))
    (0x03#8) (0x38#8) (0x81#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_00813803 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (exec_ld σ (0x800041cc#64) (0x008#12) (regidx.Regidx 0x02#5) (regidx.Regidx 0x10#5)
      (sigma3_alu σ (0x800041cc#64) Register.x16 (sign_extend (m := 64) ((((((((b7.append b6).append b5).append b4).append b3).append b2).append b1).append b0) : BitVec (8 * 8))))
      v2 b0 b1 b2 b3 b4 b5 b6 b7 hG
      (rX_bits_x2 _ v2
        (by rw [get?_afterNextPC σ (0x800041cc#64) _ (by decide) (by decide)]; exact hx2))
      (wX_bits_x16 _ (sign_extend (m := 64) ((((((((b7.append b6).append b5).append b4).append b3).append b2).append b1).append b0) : BitVec (8 * 8))))
      hlo hhiram hhtif halign h0 h1 h2 h3 h4 h5 h6 h7)
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x800041d0: `lw x14,0x10(x8)`. -/
theorem site_800041d0_es (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v8 : BitVec 64)
    (b0 b1 b2 b3 : BitVec 8)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx8 : σ.regs.get? Register.x8 = some v8)
    (hmem : Vsa.Sim.Code.Exec_stmtLoaded σ.mem)
    (hpcv : pc = (0x800041d0#64 : BitVec 64))
    (hlo : 0x80000000 ≤ (v8 + sign_extend (m := 64) (0x010#12)).toNat)
    (hhiram : (v8 + sign_extend (m := 64) (0x010#12)).toNat + 4 ≤ 0x100000000)
    (hhtif : (v8 + sign_extend (m := 64) (0x010#12)).toNat + 4 ≤ tohostAddr
      ∨ tohostAddr + 8 ≤ (v8 + sign_extend (m := 64) (0x010#12)).toNat)
    (halign : (v8 + sign_extend (m := 64) (0x010#12)).toNat % 4 = 0)
    (h0 : σ.mem[(v8 + sign_extend (m := 64) (0x010#12)).toNat]? = some b0)
    (h1 : σ.mem[(v8 + sign_extend (m := 64) (0x010#12)).toNat + 1]? = some b1)
    (h2 : σ.mem[(v8 + sign_extend (m := 64) (0x010#12)).toNat + 2]? = some b2)
    (h3 : σ.mem[(v8 + sign_extend (m := 64) (0x010#12)).toNat + 3]? = some b3)
    (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x14
        (sign_extend (m := 64)
          ((((b3.append b2).append b1).append b0) : BitVec (8 * 4)))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.exec_stmt_at_800041d0 hmem
  exact stepObs_alu σ i u (0x800041d0#64) vminstret (0x01042703#32)
    (instruction.LOAD (0x010#12, regidx.Regidx 0x08#5, regidx.Regidx 0x0e#5, false, 4))
    Register.x14 (sign_extend (m := 64) ((((b3.append b2).append b1).append b0) : BitVec (8 * 4)))
    (0x03#8) (0x27#8) (0x04#8) (0x01#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_01042703 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (exec_lw σ (0x800041d0#64) (0x010#12) (regidx.Regidx 0x08#5) (regidx.Regidx 0x0e#5)
      (sigma3_alu σ (0x800041d0#64) Register.x14 (sign_extend (m := 64) ((((b3.append b2).append b1).append b0) : BitVec (8 * 4))))
      v8 b0 b1 b2 b3 hG
      (rX_bits_x8 _ v8
        (by rw [get?_afterNextPC σ (0x800041d0#64) _ (by decide) (by decide)]; exact hx8))
      (wX_bits_x14 _ (sign_extend (m := 64) ((((b3.append b2).append b1).append b0) : BitVec (8 * 4))))
      hlo hhiram hhtif halign h0 h1 h2 h3)
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x800041d4: `addi x16,x16,0x1`. -/
theorem site_800041d4_es (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v16 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx16 : σ.regs.get? Register.x16 = some v16)
    (hmem : Vsa.Sim.Code.Exec_stmtLoaded σ.mem)
    (hpcv : pc = (0x800041d4#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x16
        (v16 + sign_extend (m := 64) (0x001#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.exec_stmt_at_800041d4 hmem
  exact stepObs_alu σ i u (0x800041d4#64) vminstret (0x00180813#32)
    (instruction.ITYPE (0x001#12, regidx.Regidx 0x10#5, regidx.Regidx 0x10#5, iop.ADDI))
    Register.x16 (v16 + sign_extend (m := 64) (0x001#12))
    (0x13#8) (0x08#8) (0x18#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_00180813 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_addi_char (0x001#12) (regidx.Regidx 0x10#5) (regidx.Regidx 0x10#5) v16
      (afterNextPC (afterPrelude σ) (0x800041d4#64))
      (sigma3_alu σ (0x800041d4#64) Register.x16 (v16 + sign_extend (m := 64) (0x001#12)))
      (rX_bits_x16 _ v16
        (by rw [get?_afterNextPC σ (0x800041d4#64) _ (by decide) (by decide)]; exact hx16))
      (wX_bits_x16 _ (v16 + sign_extend (m := 64) (0x001#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x800041d8: `addiw x15,x16,0x0`. -/
theorem site_800041d8_es (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v16 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx16 : σ.regs.get? Register.x16 = some v16)
    (hmem : Vsa.Sim.Code.Exec_stmtLoaded σ.mem)
    (hpcv : pc = (0x800041d8#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x15
        (sign_extend (m := 64)
          (Sail.BitVec.extractLsb (v16 + sign_extend (m := 64) (0x000#12)) 31 0))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.exec_stmt_at_800041d8 hmem
  exact stepObs_alu σ i u (0x800041d8#64) vminstret (0x0008079b#32)
    (instruction.ADDIW (0x000#12, regidx.Regidx 0x10#5, regidx.Regidx 0x0f#5))
    Register.x15 (sign_extend (m := 64) (Sail.BitVec.extractLsb (v16 + sign_extend (m := 64) (0x000#12)) 31 0))
    (0x9b#8) (0x07#8) (0x08#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_0008079b (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_addiw_char (0x000#12) (regidx.Regidx 0x10#5) (regidx.Regidx 0x0f#5) v16
      (afterNextPC (afterPrelude σ) (0x800041d8#64))
      (sigma3_alu σ (0x800041d8#64) Register.x15 (sign_extend (m := 64) (Sail.BitVec.extractLsb (v16 + sign_extend (m := 64) (0x000#12)) 31 0)))
      (rX_bits_x16 _ v16
        (by rw [get?_afterNextPC σ (0x800041d8#64) _ (by decide) (by decide)]; exact hx16))
      (wX_bits_x15 _ (sign_extend (m := 64) (Sail.BitVec.extractLsb (v16 + sign_extend (m := 64) (0x000#12)) 31 0))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- Branch target of the taken site at 0x800041dc. -/
theorem site_800041dc_taken_es_tgt :
    (0x800041dc#64 + sign_extend (m := 64) (0x1fc8#13)) = (0x800041a4#64 : BitVec 64) := by
  apply BitVec.eq_of_toNat_eq; decide

/-- 0x800041dc: `blt x15,x14 → 0x800041a4` (TAKEN). -/
theorem site_800041dc_taken_es (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v15 v14 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hx14 : σ.regs.get? Register.x14 = some v14)
    (hmem : Vsa.Sim.Code.Exec_stmtLoaded σ.mem)
    (hpcv : pc = (0x800041dc#64 : BitVec 64))
    (hv : zopz0zI_s v15 v14 = true) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_branch_taken σ pc vminstret (0x1fc8#13)) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.exec_stmt_at_800041dc hmem
  exact stepObs_branch_taken σ i u (0x800041dc#64) vminstret (0x1fc8#13)
    (regidx.Regidx 0x0f#5) (regidx.Regidx 0x0e#5) bop.BLT (0xfce7c4e3#32)
    (0xe3#8) (0xc4#8) (0xe7#8) (0xfc#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_fce7c4e3 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_btype_blt_taken (0x1fc8#13) (regidx.Regidx 0x0f#5) (regidx.Regidx 0x0e#5)
      v15 v14 (0x800041dc#64) initMisa (afterNextPC (afterPrelude σ) (0x800041dc#64))
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x800041dc#64) _ (by decide) (by decide)]; exact hx15))
      (rX_bits_x14 _ v14
        (by rw [get?_afterNextPC σ (0x800041dc#64) _ (by decide) (by decide)]; exact hx14))
      (by rw [get?_afterNextPC σ (0x800041dc#64) _ (by decide) (by decide)]; exact hpc)
      (by rw [get?_afterNextPC σ (0x800041dc#64) _ (by decide) (by decide)]; exact hG.misa)
      (by rw [site_800041dc_taken_es_tgt]; decide) hv)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x800041dc: `blt x15,x14` (NOT taken). -/
theorem site_800041dc_nottaken_es (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v15 v14 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hx14 : σ.regs.get? Register.x14 = some v14)
    (hmem : Vsa.Sim.Code.Exec_stmtLoaded σ.mem)
    (hpcv : pc = (0x800041dc#64 : BitVec 64))
    (hv : zopz0zI_s v15 v14 = false) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_branch_nottaken σ pc vminstret) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.exec_stmt_at_800041dc hmem
  exact stepObs_branch_nottaken σ i u (0x800041dc#64) vminstret (0x1fc8#13)
    (regidx.Regidx 0x0f#5) (regidx.Regidx 0x0e#5) bop.BLT (0xfce7c4e3#32)
    (0xe3#8) (0xc4#8) (0xe7#8) (0xfc#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_fce7c4e3 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_btype_blt_nottaken (0x1fc8#13) (regidx.Regidx 0x0f#5) (regidx.Regidx 0x0e#5)
      v15 v14 (afterNextPC (afterPrelude σ) (0x800041dc#64))
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x800041dc#64) _ (by decide) (by decide)]; exact hx15))
      (rX_bits_x14 _ v14
        (by rw [get?_afterNextPC σ (0x800041dc#64) _ (by decide) (by decide)]; exact hx14))
      hv)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x800041e0: `addi x10,x0,0x0`. -/
theorem site_800041e0_es (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hmem : Vsa.Sim.Code.Exec_stmtLoaded σ.mem)
    (hpcv : pc = (0x800041e0#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x10
        ((0#64) + sign_extend (m := 64) (0x000#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.exec_stmt_at_800041e0 hmem
  exact stepObs_alu σ i u (0x800041e0#64) vminstret (0x00000513#32)
    (instruction.ITYPE (0x000#12, regidx.Regidx 0x00#5, regidx.Regidx 0x0a#5, iop.ADDI))
    Register.x10 ((0#64) + sign_extend (m := 64) (0x000#12))
    (0x13#8) (0x05#8) (0x00#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_00000513 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_addi_char (0x000#12) (regidx.Regidx 0x00#5) (regidx.Regidx 0x0a#5) (0#64)
      (afterNextPC (afterPrelude σ) (0x800041e0#64))
      (sigma3_alu σ (0x800041e0#64) Register.x10 ((0#64) + sign_extend (m := 64) (0x000#12)))
      (rX_bits_zero _)
      (wX_bits_x10 _ ((0#64) + sign_extend (m := 64) (0x000#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x800041e4: `j 0x8000409c`. -/
theorem site_800041e4_es (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hmem : Vsa.Sim.Code.Exec_stmtLoaded σ.mem)
    (hpcv : pc = (0x800041e4#64 : BitVec 64))
    (htgt : (pc + sign_extend (m := 64) (0x1ffeb8#21)).toNat % 4 = 0) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_jump_x0 σ pc vminstret (pc + sign_extend (m := 64) (0x1ffeb8#21))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.exec_stmt_at_800041e4 hmem
  exact stepObs_j σ i u (0x800041e4#64) vminstret (0xeb9ff06f#32) (0x1ffeb8#21)
    (0x6f#8) (0xf0#8) (0x9f#8) (0xeb#8)
    hG hpc hminstret hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) (by decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_eb9ff06f (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    htgt hi


/-! ### 0x800041a8 — `slli a4,a6,0x3` (rd=x14, rs1=x16, shamt=3) — HAND-written.

The only loop-body site outside the generator's class set (no `slli` emitter).
Mirrors `site_80004020_es` (the dispatch `slli`), using the generic
`exec_slli_gen` (`StrcmpSites.lean`) with `rX_bits_x16`/`wX_bits_x14`. -/
theorem site_800041a8_es
    (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v16 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx16 : σ.regs.get? Register.x16 = some v16)
    (hmem : Vsa.Sim.Code.Exec_stmtLoaded σ.mem)
    (hpcv : pc = (0x800041a8#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧ σ'.mem = σ.mem ∧
      ReadsLikePost σ'
        (sigmaPost_alu σ pc vminstret Register.x14
          (shift_bits_left v16 (Sail.BitVec.extractLsb (0x03#6) 5 0))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.exec_stmt_at_800041a8 hmem
  exact stepObs_alu σ i u (0x800041a8#64) vminstret (0x00381713#32)
    (instruction.SHIFTIOP (0x03#6, regidx.Regidx 0x10#5, regidx.Regidx 0x0e#5, sop.SLLI))
    Register.x14 (shift_bits_left v16 (Sail.BitVec.extractLsb (0x03#6) 5 0))
    (0x13#8) (0x17#8) (0x38#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide) (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_00381713 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (exec_slli_gen σ (0x800041a8#64) (0x03#6) (regidx.Regidx 0x10#5) (regidx.Regidx 0x0e#5) v16
      (sigma3_alu σ (0x800041a8#64) Register.x14
        (shift_bits_left v16 (Sail.BitVec.extractLsb (0x03#6) 5 0)))
      (rX_bits_x16 _ v16
        (by rw [get?_afterNextPC σ (0x800041a8#64) _ (by decide) (by decide)]; exact hx16))
      (wX_bits_x14 _ (shift_bits_left v16 (Sail.BitVec.extractLsb (0x03#6) 5 0))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

end Vsa.Sim
