import Vsa.Sim.ValueSites
import Vsa.Sim.StrcpySites
import Vsa.Sim.Code.ArmPins
import Vsa.Sim.DecodeTable.Batch01Part02
import Vsa.Sim.DecodeTable.Batch02Part20
import Vsa.Sim.DecodeTable.Batch02Part21
import Vsa.Sim.DecodeTable.Batch09Part10
import Vsa.Sim.DecodeTable.Batch10Part06
import Vsa.Sim.DecodeTable.Batch11Part29
import Vsa.Sim.DecodeTable.Batch13Part30
import Vsa.Sim.DecodeTable.Batch14Part10

/-!
Per-site `StepObs` battery generated by scripts/gen_sites.py from
fs_b.tsv against `Vsa.Sim.Code.ArmPinsLoaded`.
Do not hand-edit; regenerate instead.
-/

open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail ConcurrencyInterfaceV1 Vsa
open Register
open Sail.ConcurrencyInterfaceV1.PreSail
open Vsa.Machine (MState Config Step Steps)

set_option maxHeartbeats 8000000
set_option maxRecDepth 1000000

namespace Vsa.Sim

/-- 0x80008ea4: `lbu x30,0xa7(x2)`. -/
theorem site_80008ea4_fs2 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v2 : BitVec 64)
    (b : BitVec 8)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx2 : σ.regs.get? Register.x2 = some v2)
    (hmem : Vsa.Sim.Code.ArmPinsLoaded σ.mem)
    (hpcv : pc = (0x80008ea4#64 : BitVec 64))
    (hlo : 0x80000000 ≤ (v2 + sign_extend (m := 64) (0x0a7#12)).toNat)
    (hhiram : (v2 + sign_extend (m := 64) (0x0a7#12)).toNat + 1 ≤ 0x100000000)
    (hhtif : (v2 + sign_extend (m := 64) (0x0a7#12)).toNat + 1 ≤ tohostAddr
      ∨ tohostAddr + 8 ≤ (v2 + sign_extend (m := 64) (0x0a7#12)).toNat)
    (hb : σ.mem[(v2 + sign_extend (m := 64) (0x0a7#12)).toNat]? = some b)
    (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x30 (zero_extend (m := 64) b)) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.armPins_at_80008ea4 hmem
  exact stepObs_alu σ i u (0x80008ea4#64) vminstret (0x0a714f03#32)
    (instruction.LOAD (0x0a7#12, regidx.Regidx 0x02#5, regidx.Regidx 0x1e#5, true, 1))
    Register.x30 (zero_extend (m := 64) b)
    (0x03#8) (0x4f#8) (0x71#8) (0x0a#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_0a714f03 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (exec_lbu_gen σ (0x80008ea4#64) (0x0a7#12) (regidx.Regidx 0x02#5) (regidx.Regidx 0x1e#5)
      v2 b (sigma3_alu σ (0x80008ea4#64) Register.x30 (zero_extend (m := 64) b)) hG
      (rX_bits_x2 _ v2
        (by rw [get?_afterNextPC σ (0x80008ea4#64) _ (by decide) (by decide)]; exact hx2))
      (wX_bits_x30 _ (zero_extend (m := 64) b))
      hlo hhiram hhtif hb)
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x80008ea8: `addi x16,x0,0x1`. -/
theorem site_80008ea8_fs2 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hmem : Vsa.Sim.Code.ArmPinsLoaded σ.mem)
    (hpcv : pc = (0x80008ea8#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x16
        ((0#64) + sign_extend (m := 64) (0x001#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.armPins_at_80008ea8 hmem
  exact stepObs_alu σ i u (0x80008ea8#64) vminstret (0x00100813#32)
    (instruction.ITYPE (0x001#12, regidx.Regidx 0x00#5, regidx.Regidx 0x10#5, iop.ADDI))
    Register.x16 ((0#64) + sign_extend (m := 64) (0x001#12))
    (0x13#8) (0x08#8) (0x10#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_00100813 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_addi_char (0x001#12) (regidx.Regidx 0x00#5) (regidx.Regidx 0x10#5) (0#64)
      (afterNextPC (afterPrelude σ) (0x80008ea8#64))
      (sigma3_alu σ (0x80008ea8#64) Register.x16 ((0#64) + sign_extend (m := 64) (0x001#12)))
      (rX_bits_zero _)
      (wX_bits_x16 _ ((0#64) + sign_extend (m := 64) (0x001#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x80008eac: `addi x31,x0,0x0`. -/
theorem site_80008eac_fs2 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hmem : Vsa.Sim.Code.ArmPinsLoaded σ.mem)
    (hpcv : pc = (0x80008eac#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x31
        ((0#64) + sign_extend (m := 64) (0x000#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.armPins_at_80008eac hmem
  exact stepObs_alu σ i u (0x80008eac#64) vminstret (0x00000f93#32)
    (instruction.ITYPE (0x000#12, regidx.Regidx 0x00#5, regidx.Regidx 0x1f#5, iop.ADDI))
    Register.x31 ((0#64) + sign_extend (m := 64) (0x000#12))
    (0x93#8) (0x0f#8) (0x00#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_00000f93 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_addi_char (0x000#12) (regidx.Regidx 0x00#5) (regidx.Regidx 0x1f#5) (0#64)
      (afterNextPC (afterPrelude σ) (0x80008eac#64))
      (sigma3_alu σ (0x80008eac#64) Register.x31 ((0#64) + sign_extend (m := 64) (0x000#12)))
      (rX_bits_zero _)
      (wX_bits_x31 _ ((0#64) + sign_extend (m := 64) (0x000#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x80008eb0: `addi x22,x0,0x1`. -/
theorem site_80008eb0_fs2 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hmem : Vsa.Sim.Code.ArmPinsLoaded σ.mem)
    (hpcv : pc = (0x80008eb0#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x22
        ((0#64) + sign_extend (m := 64) (0x001#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.armPins_at_80008eb0 hmem
  exact stepObs_alu σ i u (0x80008eb0#64) vminstret (0x00100b13#32)
    (instruction.ITYPE (0x001#12, regidx.Regidx 0x00#5, regidx.Regidx 0x16#5, iop.ADDI))
    Register.x22 ((0#64) + sign_extend (m := 64) (0x001#12))
    (0x13#8) (0x0b#8) (0x10#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_00100b13 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_addi_char (0x001#12) (regidx.Regidx 0x00#5) (regidx.Regidx 0x16#5) (0#64)
      (afterNextPC (afterPrelude σ) (0x80008eb0#64))
      (sigma3_alu σ (0x80008eb0#64) Register.x22 ((0#64) + sign_extend (m := 64) (0x001#12)))
      (rX_bits_zero _)
      (wX_bits_x22 _ ((0#64) + sign_extend (m := 64) (0x001#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x80008eb4: `addi x26,x2,0x15b`. -/
theorem site_80008eb4_fs2 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v2 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx2 : σ.regs.get? Register.x2 = some v2)
    (hmem : Vsa.Sim.Code.ArmPinsLoaded σ.mem)
    (hpcv : pc = (0x80008eb4#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x26
        (v2 + sign_extend (m := 64) (0x15b#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.armPins_at_80008eb4 hmem
  exact stepObs_alu σ i u (0x80008eb4#64) vminstret (0x15b10d13#32)
    (instruction.ITYPE (0x15b#12, regidx.Regidx 0x02#5, regidx.Regidx 0x1a#5, iop.ADDI))
    Register.x26 (v2 + sign_extend (m := 64) (0x15b#12))
    (0x13#8) (0x0d#8) (0xb1#8) (0x15#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_15b10d13 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_addi_char (0x15b#12) (regidx.Regidx 0x02#5) (regidx.Regidx 0x1a#5) v2
      (afterNextPC (afterPrelude σ) (0x80008eb4#64))
      (sigma3_alu σ (0x80008eb4#64) Register.x26 (v2 + sign_extend (m := 64) (0x15b#12)))
      (rX_bits_x2 _ v2
        (by rw [get?_afterNextPC σ (0x80008eb4#64) _ (by decide) (by decide)]; exact hx2))
      (wX_bits_x26 _ (v2 + sign_extend (m := 64) (0x15b#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x80008eb8: `j 0x80008128`. -/
theorem site_80008eb8_fs2 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hmem : Vsa.Sim.Code.ArmPinsLoaded σ.mem)
    (hpcv : pc = (0x80008eb8#64 : BitVec 64))
    (htgt : (pc + sign_extend (m := 64) (0x1ff270#21)).toNat % 4 = 0) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_jump_x0 σ pc vminstret (pc + sign_extend (m := 64) (0x1ff270#21))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.armPins_at_80008eb8 hmem
  exact stepObs_j σ i u (0x80008eb8#64) vminstret (0xa70ff06f#32) (0x1ff270#21)
    (0x6f#8) (0xf0#8) (0x0f#8) (0xa7#8)
    hG hpc hminstret hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) (by decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_a70ff06f (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    htgt hi

/-- 0x80007ce4: `subw x20,x20,x22`. -/
theorem site_80007ce4_fs2 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v20 v22 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx20 : σ.regs.get? Register.x20 = some v20)
    (hx22 : σ.regs.get? Register.x22 = some v22)
    (hmem : Vsa.Sim.Code.ArmPinsLoaded σ.mem)
    (hpcv : pc = (0x80007ce4#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x20 (sign_extend (m := 64)
          ((Sail.BitVec.extractLsb v20 31 0) - (Sail.BitVec.extractLsb v22 31 0)))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.armPins_at_80007ce4 hmem
  exact stepObs_alu σ i u (0x80007ce4#64) vminstret (0x416a0a3b#32)
    (instruction.RTYPEW (regidx.Regidx 0x16#5, regidx.Regidx 0x14#5, regidx.Regidx 0x14#5, ropw.SUBW))
    Register.x20 (sign_extend (m := 64) ((Sail.BitVec.extractLsb v20 31 0) - (Sail.BitVec.extractLsb v22 31 0)))
    (0x3b#8) (0x0a#8) (0x6a#8) (0x41#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_416a0a3b (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_rtypew_subw_char (regidx.Regidx 0x16#5) (regidx.Regidx 0x14#5) (regidx.Regidx 0x14#5)
      v20 v22 (afterNextPC (afterPrelude σ) (0x80007ce4#64))
      (sigma3_alu σ (0x80007ce4#64) Register.x20 (sign_extend (m := 64) ((Sail.BitVec.extractLsb v20 31 0) - (Sail.BitVec.extractLsb v22 31 0))))
      (rX_bits_x20 _ v20
        (by rw [get?_afterNextPC σ (0x80007ce4#64) _ (by decide) (by decide)]; exact hx20))
      (rX_bits_x22 _ v22
        (by rw [get?_afterNextPC σ (0x80007ce4#64) _ (by decide) (by decide)]; exact hx22))
      (wX_bits_x20 _ (sign_extend (m := 64) ((Sail.BitVec.extractLsb v20 31 0) - (Sail.BitVec.extractLsb v22 31 0)))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- Branch target of the taken site at 0x80007ce8. -/
theorem site_80007ce8_taken_fs2_tgt :
    (0x80007ce8#64 + sign_extend (m := 64) (0x1bd4#13)) = (0x800078bc#64 : BitVec 64) := by
  apply BitVec.eq_of_toNat_eq; decide

/-- 0x80007ce8: `bge x0,x20 → 0x800078bc` (TAKEN). -/
theorem site_80007ce8_taken_fs2 (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v20 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx20 : σ.regs.get? Register.x20 = some v20)
    (hmem : Vsa.Sim.Code.ArmPinsLoaded σ.mem)
    (hpcv : pc = (0x80007ce8#64 : BitVec 64))
    (hv : zopz0zKzJ_s (0#64) v20 = true) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_branch_taken σ pc vminstret (0x1bd4#13)) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.armPins_at_80007ce8 hmem
  exact stepObs_branch_taken σ i u (0x80007ce8#64) vminstret (0x1bd4#13)
    (regidx.Regidx 0x00#5) (regidx.Regidx 0x14#5) bop.BGE (0xbd405ae3#32)
    (0xe3#8) (0x5a#8) (0x40#8) (0xbd#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.DecodeTable.decode_bd405ae3 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_btype_bge_taken (0x1bd4#13) (regidx.Regidx 0x00#5) (regidx.Regidx 0x14#5)
      (0#64) v20 (0x80007ce8#64) initMisa (afterNextPC (afterPrelude σ) (0x80007ce8#64))
      (rX_bits_zero _)
      (rX_bits_x20 _ v20
        (by rw [get?_afterNextPC σ (0x80007ce8#64) _ (by decide) (by decide)]; exact hx20))
      (by rw [get?_afterNextPC σ (0x80007ce8#64) _ (by decide) (by decide)]; exact hpc)
      (by rw [get?_afterNextPC σ (0x80007ce8#64) _ (by decide) (by decide)]; exact hG.misa)
      (by rw [site_80007ce8_taken_fs2_tgt]; decide) hv)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

end Vsa.Sim
