import Vsa.Elf
import Vsa.Sim.InitValues

/-! Decode table batch 08/16, part 31/32
(generated by experiments/gen_decode_table.py —
regenerate, do not hand-edit). One lemma per unique 32-bit instruction word
reachable from `interp_run` (PLAN-InterpSim.md Layer 0 item 4), uniform
template stabilized in Vsa/Sim/DecodePilot.lean. -/

open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail ConcurrencyInterfaceV1 Vsa
open Register

set_option maxHeartbeats 16000000
set_option maxRecDepth 1000000
set_option linter.unusedSimpArgs false

namespace Vsa.Sim.DecodeTable

theorem decode_08113c23
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x08113c23#32).run σ =
      .ok (LeanRV64DExecutable.instruction.STORE (0x098#12, LeanRV64DExecutable.regidx.Regidx 0x01#5, LeanRV64DExecutable.regidx.Regidx 0x02#5, 8)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_08410593
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x08410593#32).run σ =
      .ok (LeanRV64DExecutable.instruction.ITYPE (0x084#12, LeanRV64DExecutable.regidx.Regidx 0x02#5, LeanRV64DExecutable.regidx.Regidx 0x0b#5, LeanRV64DExecutable.iop.ADDI)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_08412783
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x08412783#32).run σ =
      .ok (LeanRV64DExecutable.instruction.LOAD (0x084#12, LeanRV64DExecutable.regidx.Regidx 0x02#5, LeanRV64DExecutable.regidx.Regidx 0x0f#5, false, 4)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_08437293
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x08437293#32).run σ =
      .ok (LeanRV64DExecutable.instruction.ITYPE (0x084#12, LeanRV64DExecutable.regidx.Regidx 0x06#5, LeanRV64DExecutable.regidx.Regidx 0x05#5, LeanRV64DExecutable.iop.ANDI)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_08437f93
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x08437f93#32).run σ =
      .ok (LeanRV64DExecutable.instruction.ITYPE (0x084#12, LeanRV64DExecutable.regidx.Regidx 0x06#5, LeanRV64DExecutable.regidx.Regidx 0x1f#5, LeanRV64DExecutable.iop.ANDI)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_084e7d13
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x084e7d13#32).run σ =
      .ok (LeanRV64DExecutable.instruction.ITYPE (0x084#12, LeanRV64DExecutable.regidx.Regidx 0x1c#5, LeanRV64DExecutable.regidx.Regidx 0x1a#5, LeanRV64DExecutable.iop.ANDI)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_08513423
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x08513423#32).run σ =
      .ok (LeanRV64DExecutable.instruction.STORE (0x088#12, LeanRV64DExecutable.regidx.Regidx 0x05#5, LeanRV64DExecutable.regidx.Regidx 0x02#5, 8)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_08613023
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x08613023#32).run σ =
      .ok (LeanRV64DExecutable.instruction.STORE (0x080#12, LeanRV64DExecutable.regidx.Regidx 0x06#5, LeanRV64DExecutable.regidx.Regidx 0x02#5, 8)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_08613423
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x08613423#32).run σ =
      .ok (LeanRV64DExecutable.instruction.STORE (0x088#12, LeanRV64DExecutable.regidx.Regidx 0x06#5, LeanRV64DExecutable.regidx.Regidx 0x02#5, 8)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_08613823
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x08613823#32).run σ =
      .ok (LeanRV64DExecutable.instruction.STORE (0x090#12, LeanRV64DExecutable.regidx.Regidx 0x06#5, LeanRV64DExecutable.regidx.Regidx 0x02#5, 8)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_08678e63
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x08678e63#32).run σ =
      .ok (LeanRV64DExecutable.instruction.BTYPE (0x009c#13, LeanRV64DExecutable.regidx.Regidx 0x06#5, LeanRV64DExecutable.regidx.Regidx 0x0f#5, LeanRV64DExecutable.bop.BEQ)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_088040ef
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x088040ef#32).run σ =
      .ok (LeanRV64DExecutable.instruction.JAL (0x004088#21, LeanRV64DExecutable.regidx.Regidx 0x01#5)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_08810513
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x08810513#32).run σ =
      .ok (LeanRV64DExecutable.instruction.ITYPE (0x088#12, LeanRV64DExecutable.regidx.Regidx 0x02#5, LeanRV64DExecutable.regidx.Regidx 0x0a#5, LeanRV64DExecutable.iop.ADDI)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_08810713
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x08810713#32).run σ =
      .ok (LeanRV64DExecutable.instruction.ITYPE (0x088#12, LeanRV64DExecutable.regidx.Regidx 0x02#5, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.iop.ADDI)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_08813023
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x08813023#32).run σ =
      .ok (LeanRV64DExecutable.instruction.STORE (0x080#12, LeanRV64DExecutable.regidx.Regidx 0x08#5, LeanRV64DExecutable.regidx.Regidx 0x02#5, 8)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_08813083
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x08813083#32).run σ =
      .ok (LeanRV64DExecutable.instruction.LOAD (0x088#12, LeanRV64DExecutable.regidx.Regidx 0x02#5, LeanRV64DExecutable.regidx.Regidx 0x01#5, false, 8)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

end Vsa.Sim.DecodeTable
