import Vsa.Elf
import Vsa.Sim.InitValues

/-! Decode table batch 16/16, part 28/32
(generated by experiments/gen_decode_table.py —
regenerate, do not hand-edit). One lemma per unique 32-bit instruction word
reachable from `interp_run` (PLAN-InterpSim.md Layer 0 item 4), uniform
template stabilized in Vsa/Sim/DecodePilot.lean. -/

open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail ConcurrencyInterfaceV1 Vsa
open Register

set_option maxHeartbeats 16000000
set_option maxRecDepth 1000000
set_option linter.unusedSimpArgs false

namespace Vsa.Sim.DecodeTable

theorem decode_fff60693
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0xfff60693#32).run σ =
      .ok (LeanRV64DExecutable.instruction.ITYPE (0xfff#12, LeanRV64DExecutable.regidx.Regidx 0x0c#5, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.iop.ADDI)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_fff60813
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0xfff60813#32).run σ =
      .ok (LeanRV64DExecutable.instruction.ITYPE (0xfff#12, LeanRV64DExecutable.regidx.Regidx 0x0c#5, LeanRV64DExecutable.regidx.Regidx 0x10#5, LeanRV64DExecutable.iop.ADDI)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_fff6081b
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0xfff6081b#32).run σ =
      .ok (LeanRV64DExecutable.instruction.ADDIW (0xfff#12, LeanRV64DExecutable.regidx.Regidx 0x0c#5, LeanRV64DExecutable.regidx.Regidx 0x10#5)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_fff64613
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0xfff64613#32).run σ =
      .ok (LeanRV64DExecutable.instruction.ITYPE (0xfff#12, LeanRV64DExecutable.regidx.Regidx 0x0c#5, LeanRV64DExecutable.regidx.Regidx 0x0c#5, LeanRV64DExecutable.iop.XORI)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_fff68693
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0xfff68693#32).run σ =
      .ok (LeanRV64DExecutable.instruction.ITYPE (0xfff#12, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.iop.ADDI)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_fff6869b
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0xfff6869b#32).run σ =
      .ok (LeanRV64DExecutable.instruction.ADDIW (0xfff#12, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.regidx.Regidx 0x0d#5)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_fff68713
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0xfff68713#32).run σ =
      .ok (LeanRV64DExecutable.instruction.ITYPE (0xfff#12, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.iop.ADDI)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_fff6c813
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0xfff6c813#32).run σ =
      .ok (LeanRV64DExecutable.instruction.ITYPE (0xfff#12, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.regidx.Regidx 0x10#5, LeanRV64DExecutable.iop.XORI)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_fff70513
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0xfff70513#32).run σ =
      .ok (LeanRV64DExecutable.instruction.ITYPE (0xfff#12, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.regidx.Regidx 0x0a#5, LeanRV64DExecutable.iop.ADDI)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_fff70693
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0xfff70693#32).run σ =
      .ok (LeanRV64DExecutable.instruction.ITYPE (0xfff#12, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.iop.ADDI)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_fff70713
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0xfff70713#32).run σ =
      .ok (LeanRV64DExecutable.instruction.ITYPE (0xfff#12, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.iop.ADDI)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_fff7071b
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0xfff7071b#32).run σ =
      .ok (LeanRV64DExecutable.instruction.ADDIW (0xfff#12, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.regidx.Regidx 0x0e#5)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_fff70793
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0xfff70793#32).run σ =
      .ok (LeanRV64DExecutable.instruction.ITYPE (0xfff#12, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.regidx.Regidx 0x0f#5, LeanRV64DExecutable.iop.ADDI)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_fff70b1b
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0xfff70b1b#32).run σ =
      .ok (LeanRV64DExecutable.instruction.ADDIW (0xfff#12, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.regidx.Regidx 0x16#5)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_fff74613
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0xfff74613#32).run σ =
      .ok (LeanRV64DExecutable.instruction.ITYPE (0xfff#12, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.regidx.Regidx 0x0c#5, LeanRV64DExecutable.iop.XORI)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_fff74683
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0xfff74683#32).run σ =
      .ok (LeanRV64DExecutable.instruction.LOAD (0xfff#12, LeanRV64DExecutable.regidx.Regidx 0x0e#5, LeanRV64DExecutable.regidx.Regidx 0x0d#5, true, 1)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

end Vsa.Sim.DecodeTable
