import Vsa.Elf
import Vsa.Sim.InitValues

/-! Decode table batch 05/16, part 02/32
(generated by experiments/gen_decode_table.py —
regenerate, do not hand-edit). One lemma per unique 32-bit instruction word
reachable from `interp_run` (PLAN-InterpSim.md Layer 0 item 4), uniform
template stabilized in Vsa/Sim/DecodePilot.lean. -/

open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail ConcurrencyInterfaceV1 Vsa
open Register

set_option maxHeartbeats 16000000
set_option maxRecDepth 1000000
set_option linter.unusedSimpArgs false

namespace Vsa.Sim.DecodeTable

theorem decode_00f68b3b
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x00f68b3b#32).run σ =
      .ok (LeanRV64DExecutable.instruction.RTYPEW (LeanRV64DExecutable.regidx.Regidx 0x0f#5, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.regidx.Regidx 0x16#5, LeanRV64DExecutable.ropw.ADDW)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_00f68c63
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x00f68c63#32).run σ =
      .ok (LeanRV64DExecutable.instruction.BTYPE (0x0018#13, LeanRV64DExecutable.regidx.Regidx 0x0f#5, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.bop.BEQ)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_00f69023
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x00f69023#32).run σ =
      .ok (LeanRV64DExecutable.instruction.STORE (0x000#12, LeanRV64DExecutable.regidx.Regidx 0x0f#5, LeanRV64DExecutable.regidx.Regidx 0x0d#5, 2)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_00f696b3
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x00f696b3#32).run σ =
      .ok (LeanRV64DExecutable.instruction.RTYPE (LeanRV64DExecutable.regidx.Regidx 0x0f#5, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.rop.SLL)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_00f697b3
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x00f697b3#32).run σ =
      .ok (LeanRV64DExecutable.instruction.RTYPE (LeanRV64DExecutable.regidx.Regidx 0x0f#5, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.regidx.Regidx 0x0f#5, LeanRV64DExecutable.rop.SLL)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_00f6a023
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x00f6a023#32).run σ =
      .ok (LeanRV64DExecutable.instruction.STORE (0x000#12, LeanRV64DExecutable.regidx.Regidx 0x0f#5, LeanRV64DExecutable.regidx.Regidx 0x0d#5, 4)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_00f6b023
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x00f6b023#32).run σ =
      .ok (LeanRV64DExecutable.instruction.STORE (0x000#12, LeanRV64DExecutable.regidx.Regidx 0x0f#5, LeanRV64DExecutable.regidx.Regidx 0x0d#5, 8)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_00f6bc23
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x00f6bc23#32).run σ =
      .ok (LeanRV64DExecutable.instruction.STORE (0x018#12, LeanRV64DExecutable.regidx.Regidx 0x0f#5, LeanRV64DExecutable.regidx.Regidx 0x0d#5, 8)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_00f6c463
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x00f6c463#32).run σ =
      .ok (LeanRV64DExecutable.instruction.BTYPE (0x0008#13, LeanRV64DExecutable.regidx.Regidx 0x0f#5, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.bop.BLT)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_00f6c7b3
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x00f6c7b3#32).run σ =
      .ok (LeanRV64DExecutable.instruction.RTYPE (LeanRV64DExecutable.regidx.Regidx 0x0f#5, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.regidx.Regidx 0x0f#5, LeanRV64DExecutable.rop.XOR)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_00f6d463
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x00f6d463#32).run σ =
      .ok (LeanRV64DExecutable.instruction.BTYPE (0x0008#13, LeanRV64DExecutable.regidx.Regidx 0x0f#5, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.bop.BGE)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_00f6de63
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x00f6de63#32).run σ =
      .ok (LeanRV64DExecutable.instruction.BTYPE (0x001c#13, LeanRV64DExecutable.regidx.Regidx 0x0f#5, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.bop.BGE)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_00f6e6b3
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x00f6e6b3#32).run σ =
      .ok (LeanRV64DExecutable.instruction.RTYPE (LeanRV64DExecutable.regidx.Regidx 0x0f#5, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.rop.OR)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_00f6e7b3
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x00f6e7b3#32).run σ =
      .ok (LeanRV64DExecutable.instruction.RTYPE (LeanRV64DExecutable.regidx.Regidx 0x0f#5, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.regidx.Regidx 0x0f#5, LeanRV64DExecutable.rop.OR)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_00f6f693
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x00f6f693#32).run σ =
      .ok (LeanRV64DExecutable.instruction.ITYPE (0x00f#12, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.iop.ANDI)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

theorem decode_00f6f6b3
    (σ : SequentialState RegisterType trivialChoiceSource)
    (_hmisa : σ.regs.get? Register.misa =
      some ((Vsa.Sim.initMisa) : RegisterType Register.misa))
    (hpriv : σ.regs.get? Register.cur_privilege =
      some (Privilege.Machine : RegisterType Register.cur_privilege))
    (hsec : σ.regs.get? Register.mseccfg =
      some ((0#64) : RegisterType Register.mseccfg)) :
    (ext_decode 0x00f6f6b3#32).run σ =
      .ok (LeanRV64DExecutable.instruction.RTYPE (LeanRV64DExecutable.regidx.Regidx 0x0f#5, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.regidx.Regidx 0x0d#5, LeanRV64DExecutable.rop.AND)) σ := by
  simp only [ext_decode, encdec_backwards]
  simp_all [simp_sail, bind, EStateM.bind, EStateM.run, pure, EStateM.pure,
    currentlyEnabled, hartSupports, get, getThe, MonadStateOf.get, EStateM.get,
    get_xLPE, readReg, Vsa.Sim.initMisa]
  simp +decide [encdec_reg_backwards_matches, encdec_iop_backwards_matches,
    encdec_bop_backwards_matches, encdec_uop_backwards_matches,
    encdec_csrop_backwards_matches, bool_bit_backwards_matches,
    width_enc_backwards_matches,
    encdec_reg_backwards, encdec_iop_backwards, encdec_bop_backwards,
    encdec_uop_backwards, encdec_csrop_backwards, encdec_cbop_backwards,
    encdec_sop_backwards, bool_bit_backwards, width_enc_backwards,
    EStateM.bind, pure, EStateM.pure]
  repeat' apply And.intro
  all_goals first
    | rfl
    | (apply BitVec.eq_of_toNat_eq; decide)
    | decide
    | omega

end Vsa.Sim.DecodeTable
